Repository microsoft/terminal, pull requests merged in 2019-08, with the labels that each got.

#2104 Added information on WxH character
  doc/ConsoleHostSettings.md
Labels: Needs-Second

#2195 Azure connector only shows up if available
  src/cascadia/TerminalApp/App.cpp
  src/cascadia/TerminalApp/CascadiaSettings.cpp
  src/cascadia/TerminalConnection/AzureConnection-ARM64.cpp
  src/cascadia/TerminalConnection/AzureConnection-ARM64.h
  src/cascadia/TerminalConnection/AzureConnection.cpp
  src/cascadia/TerminalConnection/AzureConnection.h
  src/cascadia/TerminalConnection/AzureConnection.idl
  src/cascadia/TerminalConnection/TerminalConnection.vcxproj
Labels: Needs-Second

#2235 Fixed Ctrl+Alt shortcuts conflicting with AltGr
  src/cascadia/TerminalControl/TermControl.cpp
  src/cascadia/TerminalControl/TermControl.h
  src/cascadia/TerminalCore/Terminal.cpp
Labels: Needs-Second

#2244 Prevent unwanted debug logs when calling _DoGetConsoleInput
  src/host/directio.cpp
Labels: AutoMerge, Needs-Second

#1899 - moving string parameter into data member instead of copying it.
  src/cascadia/TerminalApp/App.cpp
  src/cascadia/TerminalApp/CascadiaSettings.cpp
  src/cascadia/TerminalApp/ColorScheme.cpp
  src/cascadia/TerminalApp/Profile.cpp
  src/cascadia/TerminalApp/Profile.h
  src/cascadia/TerminalSettings/TerminalSettings.cpp
  src/cascadia/WindowsTerminal/WindowsTerminal.manifest
Labels: Needs-Attention

#2038 Refactor TextBuffer::GenHTML
  src/buffer/out/textBuffer.cpp
  src/buffer/out/textBuffer.hpp
  src/cascadia/TerminalControl/TermControl.cpp
  src/interactivity/win32/Clipboard.cpp
Labels: Needs-Attention

#2291 Add a note about the build required to the README
  README.md
Labels: AutoMerge, Issue-Docs

#2310 inbox: reflect changes from 20h1 branch
  src/host/cmdline.h
  src/propslib/RegistrySerialization.hpp
  src/terminal/parser/ft_fuzzer/fuzzing_directed.h
Labels: AutoMerge

#2298 Stop Roaming settings
  src/cascadia/TerminalApp/CascadiaSettings.h
  src/cascadia/TerminalApp/CascadiaSettingsSerialization.cpp
Labels: Area-Settings, Product-Terminal

#2347 Fix the ut_app build for VS 16.2, 16.3
  src/cascadia/TerminalApp/FixVisualStudioBug.targets
  src/cascadia/TerminalApp/TerminalApp.vcxproj
  src/cascadia/ut_app/TerminalApp.UnitTests.vcxproj
Labels: Needs-Second

#2290 Add info about adding copy/paste keybindings
  doc/user-docs/UsingJsonSettings.md
Labels: AutoMerge, Issue-Docs, Needs-Second

#2376 Only update the icon of a tab it the icon actually _changed_
  src/cascadia/TerminalApp/App.cpp
  src/cascadia/TerminalApp/Profile.cpp
  src/cascadia/TerminalApp/Profile.h
  src/cascadia/TerminalApp/Tab.cpp
  src/cascadia/TerminalApp/Tab.h
  src/cascadia/TerminalApp/Utils.cpp
  src/cascadia/TerminalApp/Utils.h
Labels: AutoMerge, Needs-Second

#2373 A better fix for #tab-titles-are-too-long
  doc/cascadia/SettingsSchema.md
  src/cascadia/TerminalApp/App.cpp
  src/cascadia/TerminalApp/Profile.cpp
  src/cascadia/TerminalApp/Profile.h
  src/cascadia/TerminalConnection/ConhostConnection.cpp
  src/cascadia/TerminalConnection/ConhostConnection.h
  src/cascadia/TerminalConnection/ConhostConnection.idl
  src/cascadia/TerminalSettings/IControlSettings.idl
  src/cascadia/TerminalSettings/TerminalSettings.cpp
  src/cascadia/TerminalSettings/terminalsettings.h
  src/inc/conpty-universal.h
  src/server/Entrypoints.cpp
Labels: Area-Settings, AutoMerge, Issue-Task, Product-Terminal

#2184 Chunk Selection Expansion for Double/Triple Click Selection
  src/cascadia/TerminalCore/Terminal.hpp
  src/cascadia/TerminalCore/TerminalSelection.cpp
  src/cascadia/UnitTests_TerminalCore/MockTermSettings.h
  src/cascadia/UnitTests_TerminalCore/ScreenSizeLimitsTest.cpp
  src/cascadia/UnitTests_TerminalCore/SelectionTest.cpp
  src/cascadia/UnitTests_TerminalCore/UnitTests.vcxproj
Labels: Area-Interaction

#2346 Add Dustin's comment from #632 to Niksa's Doc
  doc/Niksa.md
Labels: AutoMerge, Issue-Docs

#2368 Replace CodepointWidthDetector's runtime table with a static one
  src/host/ut_host/CodepointWidthDetectorTests.cpp
  src/types/CodepointWidthDetector.cpp
  src/types/inc/CodepointWidthDetector.hpp
Labels: Product-Conhost

#2457 Reduce scope of audit mode build...
  OpenConsole.sln
Labels: Area-Build, Issue-Bug, Needs-Second, Product-Meta

#2438 When the titlebar is clicked, dismiss the new tab flyout
  src/cascadia/TerminalApp/App.cpp
  src/cascadia/TerminalApp/App.h
  src/cascadia/TerminalApp/App.idl
  src/cascadia/WindowsTerminal/AppHost.cpp
  src/cascadia/WindowsTerminal/IslandWindow.cpp
  src/cascadia/WindowsTerminal/IslandWindow.h
  src/cascadia/WindowsTerminal/NonClientIslandWindow.cpp
  src/cascadia/WindowsTerminal/NonClientIslandWindow.h
  src/cascadia/inc/cppwinrt_utils.h
Labels: Area-User Interface, AutoMerge, Issue-Bug, Product-Terminal

#2422 Add Warnings during settings load
  src/cascadia/LocalTests_TerminalApp/SettingsTests.cpp
  src/cascadia/TerminalApp/App.cpp
  src/cascadia/TerminalApp/App.h
  src/cascadia/TerminalApp/App.xaml
  src/cascadia/TerminalApp/CascadiaSettings.cpp
  src/cascadia/TerminalApp/CascadiaSettings.h
  src/cascadia/TerminalApp/CascadiaSettingsSerialization.cpp
  src/cascadia/TerminalApp/Resources/en-US/Resources.resw
  src/cascadia/TerminalApp/TerminalWarnings.h
  src/cascadia/TerminalApp/lib/TerminalAppLib.vcxproj
  src/inc/LibraryIncludes.h
Labels: Area-Settings, Area-User Interface, AutoMerge, Issue-Task, Needs-Second, Product-Terminal

#2365 Add default keybinding for opening dropdown
  doc/cascadia/SettingsSchema.md
  src/cascadia/TerminalApp/App.cpp
  src/cascadia/TerminalApp/App.h
  src/cascadia/TerminalApp/AppKeyBindings.cpp
  src/cascadia/TerminalApp/AppKeyBindings.h
  src/cascadia/TerminalApp/AppKeyBindings.idl
  src/cascadia/TerminalApp/AppKeyBindingsSerialization.cpp
  src/cascadia/TerminalApp/CascadiaSettings.cpp
Labels: AutoMerge, Needs-Second

#1349 Add a spec draft for Keybindings Arguments
  doc/cascadia/Keybindings-Arguments.md
Labels: Area-Settings, Issue-Docs, Product-Terminal

#2296 Accessibility: Refactor IRenderData with IUiaData
  src/cascadia/TerminalControl/TermControl.cpp
  src/cascadia/TerminalControl/TermControl.h
  src/cascadia/TerminalControl/TermControlAutomationPeer.cpp
  src/cascadia/TerminalCore/Terminal.hpp
  src/cascadia/TerminalCore/terminalrenderdata.cpp
  src/host/renderData.cpp
  src/host/renderData.hpp
  src/interactivity/win32/ut_interactivity_win32/UiaTextRangeTests.cpp
  src/interactivity/win32/windowUiaProvider.cpp
  src/renderer/inc/IRenderData.hpp
  src/types/IBaseData.h
  src/types/IUiaData.h
  src/types/ScreenInfoUiaProvider.cpp
  src/types/ScreenInfoUiaProvider.h
  src/types/UiaTextRange.cpp
  src/types/UiaTextRange.hpp
  src/types/lib/types.vcxproj
  src/types/lib/types.vcxproj.filters
Labels: Area-Accessibility, Needs-Second

#1224 Add support for HTML copy
  src/buffer/out/textBuffer.cpp
  src/buffer/out/textBuffer.hpp
  src/cascadia/TerminalApp/App.cpp
  src/cascadia/TerminalApp/App.h
  src/cascadia/TerminalControl/TermControl.cpp
  src/cascadia/TerminalControl/TermControl.h
  src/cascadia/TerminalControl/TermControl.idl
  src/cascadia/TerminalCore/Terminal.hpp
  src/cascadia/TerminalCore/TerminalSelection.cpp
  src/interactivity/win32/Clipboard.cpp
  src/interactivity/win32/clipboard.hpp
Labels: Area-TerminalControl, AutoMerge, Product-Terminal

#1258 Draft Spec for Cascading Default + User Settings
  doc/cascadia/Cascading-Default-Settings.md
Labels: Area-Settings, Issue-Docs, Product-Terminal

#2152 Added CopyOnSelect as a Global Setting
  doc/cascadia/SettingsSchema.md
  src/cascadia/TerminalApp/GlobalAppSettings.cpp
  src/cascadia/TerminalApp/GlobalAppSettings.h
  src/cascadia/TerminalControl/TermControl.cpp
  src/cascadia/TerminalCore/Terminal.cpp
  src/cascadia/TerminalCore/Terminal.hpp
  src/cascadia/TerminalCore/TerminalSelection.cpp
  src/cascadia/TerminalSettings/ICoreSettings.idl
  src/cascadia/TerminalSettings/TerminalSettings.cpp
  src/cascadia/TerminalSettings/terminalsettings.h
  src/cascadia/UnitTests_TerminalCore/MockTermSettings.h
  src/cascadia/UnitTests_TerminalCore/SelectionTest.cpp
Labels: Area-Interaction, AutoMerge

#2481 TURNS OUT CASE SENSITIVITY IS IMPORTANT
  src/cascadia/LocalTests_TerminalApp/TerminalApp.LocalTests.manifest
  src/cascadia/WindowsTerminal/WindowsTerminal.manifest
Labels: Area-CodeHealth

#2450 Prevent splitting panes into 0 width/height #2401
  src/cascadia/TerminalApp/App.cpp
  src/cascadia/TerminalApp/Pane.cpp
  src/cascadia/TerminalApp/Pane.h
  src/cascadia/TerminalApp/Tab.cpp
  src/cascadia/TerminalApp/Tab.h
Labels: Needs-Second

#2475 Just never save the settings
  src/cascadia/TerminalApp/App.cpp
  src/cascadia/TerminalApp/App.h
  src/cascadia/TerminalApp/CascadiaSettings.h
  src/cascadia/TerminalApp/CascadiaSettingsSerialization.cpp
Labels: Needs-Second

#2414 Accessibility: Refactor Providers
  src/cascadia/TerminalControl/TermControlAutomationPeer.cpp
  src/cascadia/TerminalControl/TermControlAutomationPeer.h
  src/cascadia/TerminalControl/TermControlUiaProvider.cpp
  src/cascadia/TerminalControl/TermControlUiaProvider.hpp
  src/cascadia/TerminalControl/TerminalControl.vcxproj
  src/cascadia/TerminalControl/TerminalControl.vcxproj.filters
  src/cascadia/TerminalControl/UiaTextRange.cpp
  src/cascadia/TerminalControl/UiaTextRange.hpp
  src/cascadia/TerminalControl/XamlUiaTextRange.cpp
  src/cascadia/TerminalControl/XamlUiaTextRange.h
  src/cascadia/TerminalCore/Terminal.hpp
  src/cascadia/TerminalCore/terminalrenderdata.cpp
  src/cascadia/WindowsTerminal/WindowUiaProvider.cpp
  src/host/renderData.cpp
  src/host/renderData.hpp
  src/host/tracing.cpp
  src/interactivity/win32/lib/win32.LIB.vcxproj
  src/interactivity/win32/lib/win32.LIB.vcxproj.filters
  src/interactivity/win32/screenInfoUiaProvider.cpp
  src/interactivity/win32/screenInfoUiaProvider.hpp
  src/interactivity/win32/uiaTextRange.cpp
  src/interactivity/win32/uiaTextRange.hpp
  src/interactivity/win32/ut_interactivity_win32/UiaTextRangeTests.cpp
  src/interactivity/win32/windowUiaProvider.cpp
  src/interactivity/win32/windowUiaProvider.hpp
  src/types/IUiaData.h
  src/types/ScreenInfoUiaProviderBase.cpp
  src/types/ScreenInfoUiaProviderBase.h
  src/types/UiaTextRangeBase.cpp
  src/types/UiaTextRangeBase.hpp
  src/types/WindowUiaProviderBase.cpp
  src/types/WindowUiaProviderBase.hpp
  src/types/lib/types.vcxproj
  src/types/lib/types.vcxproj.filters
Labels: Area-Accessibility

#2443 SVG currently doesn't work; using .jpg instead
  doc/user-docs/UsingJsonSettings.md
Labels: Issue-Docs

#2423 Accessibility: Add BoundingRects to UiaTextRanges
  src/cascadia/TerminalControl/TermControl.cpp
  src/cascadia/TerminalControl/TermControl.h
  src/cascadia/TerminalControl/TermControlAutomationPeer.cpp
  src/cascadia/TerminalControl/TermControlUiaProvider.cpp
  src/cascadia/TerminalControl/TermControlUiaProvider.hpp
  src/cascadia/TerminalControl/UiaTextRange.cpp
  src/cascadia/TerminalControl/UiaTextRange.hpp
  src/types/UiaTextRangeBase.cpp
  src/types/UiaTextRangeBase.hpp
Labels: Area-Accessibility

#2492 AZ: Introduce a "credential version" to force old credentials to be deleted
  src/cascadia/TerminalConnection/AzureConnection.cpp
  src/cascadia/TerminalConnection/AzureConnectionStrings.h
Labels: Area-AzureShell

#2508 az: Don't fail when a tenant doesn't have a knowable name
  src/cascadia/TerminalConnection/AzureConnection.cpp
  src/cascadia/TerminalConnection/AzureConnectionStrings.h
Labels: Area-AzureShell

#2514 Fix win key resets scroll location
  src/cascadia/TerminalControl/TermControl.cpp
  src/cascadia/TerminalCore/Terminal.cpp
Labels: Needs-Second

#2590 Catch failure to open clipboard
  src/cascadia/TerminalApp/App.cpp
Labels: Product-Terminal, Severity-Crash

#2593 doc: move cascadia specs and rename them to spec format
  doc/specs/#1142 - Keybinding Arguments.md
  doc/specs/#532 - Panes and Split Windows.md
  doc/specs/#754 - Cascading Default Settings.md
Labels: Issue-Docs
