Repository microsoft/terminal, pull requests merged in 2019-09, with the labels that each got.

#2545 Fixes #1918 - Added docs for image/icon settings & paths
  doc/cascadia/SettingsSchema.md
  doc/images/custom-icon-and-background-image.jpg
Labels: Issue-Docs

#2208 Clean up boundary between terminal app and terminal page
  src/cascadia/TerminalApp/App.cpp
  src/cascadia/TerminalApp/App.h
  src/cascadia/TerminalApp/App.idl
  src/cascadia/TerminalApp/AppActionHandlers.cpp
  src/cascadia/TerminalApp/TerminalPage.cpp
  src/cascadia/TerminalApp/TerminalPage.h
  src/cascadia/TerminalApp/TerminalPage.idl
  src/cascadia/WindowsTerminal/AppHost.cpp
  src/cascadia/WindowsTerminal/AppHost.h
Labels: Needs-Second

#2666 Don't crash when restor-down'ing the alt buffer
  src/host/screenInfo.cpp
  src/host/ut_host/ScreenBufferTests.cpp
Labels: Needs-Second, Product-Conhost

#2663 Prevent "Options" propsheet from reverting cursor shape settings
  src/propsheet/OptionsPage.cpp
  src/propsheet/OptionsPage.h
  src/propsheet/TerminalPage.cpp
  src/propsheet/console.rc
  src/propsheet/dialogs.h
  src/propsheet/globals.cpp
  src/propsheet/globals.h
Labels: AutoMerge, Needs-Second

#2668 When inserting/deleting lines, preserve RGB/256 attributes
  src/host/getset.cpp
  src/host/ut_host/ScreenBufferTests.cpp
Labels: AutoMerge, Issue-Bug, Needs-Second, Product-Conhost

#2505 Correct the boundaries of the scrolling commands
  src/host/getset.cpp
  src/host/ut_host/ScreenBufferTests.cpp
  src/terminal/adapter/adaptDispatch.cpp
  src/terminal/adapter/ut_adapter/adapterTest.cpp
Labels: Needs-Author-Feedback

#2725 Update link to Background Images and Icons section
  doc/cascadia/SettingsSchema.md
Labels: Issue-Docs, Needs-Second

#2730 wap: add some workaround to ensure that our package builds on 16.3
  build/scripts/Test-WindowsTerminalPackage.ps1
  src/cascadia/CascadiaPackage/CascadiaPackage.wapproj
Labels: Area-Build, Product-Meta

#2515 Add Cascading User + Default Settings
  doc/user-docs/UsingJsonSettings.md
  src/cascadia/CascadiaPackage/CascadiaPackage.wapproj
  src/cascadia/LocalTests_TerminalApp/ColorSchemeTests.cpp
  src/cascadia/LocalTests_TerminalApp/JsonTestClass.h
  src/cascadia/LocalTests_TerminalApp/KeyBindingsTests.cpp
  src/cascadia/LocalTests_TerminalApp/ProfileTests.cpp
  src/cascadia/LocalTests_TerminalApp/SettingsTests.cpp
  src/cascadia/LocalTests_TerminalApp/TabTests.cpp
  src/cascadia/LocalTests_TerminalApp/TerminalApp.LocalTests.vcxproj
  src/cascadia/TerminalApp/App.cpp
  src/cascadia/TerminalApp/App.h
  src/cascadia/TerminalApp/AppActionHandlers.cpp
  src/cascadia/TerminalApp/AppKeyBindings.cpp
  src/cascadia/TerminalApp/AppKeyBindings.h
  src/cascadia/TerminalApp/AppKeyBindings.idl
  src/cascadia/TerminalApp/AppKeyBindingsSerialization.cpp
  src/cascadia/TerminalApp/AppKeyBindingsSerialization.h
  src/cascadia/TerminalApp/CascadiaSettings.cpp
  src/cascadia/TerminalApp/CascadiaSettings.h
  src/cascadia/TerminalApp/CascadiaSettingsSerialization.cpp
  src/cascadia/TerminalApp/ColorScheme.cpp
  src/cascadia/TerminalApp/ColorScheme.h
  src/cascadia/TerminalApp/GlobalAppSettings.cpp
  src/cascadia/TerminalApp/GlobalAppSettings.h
  src/cascadia/TerminalApp/JsonUtils.cpp
  src/cascadia/TerminalApp/JsonUtils.h
  src/cascadia/TerminalApp/Profile.cpp
  src/cascadia/TerminalApp/Profile.h
  src/cascadia/TerminalApp/TerminalPage.cpp
  src/cascadia/TerminalApp/TerminalPage.h
  src/cascadia/TerminalApp/Utils.h
  src/cascadia/TerminalApp/defaults.json
  src/cascadia/TerminalApp/lib/TerminalAppLib.vcxproj
  src/cascadia/TerminalApp/userDefaults.json
  src/cascadia/ut_app/JsonTests.cpp
  tools/GenerateHeaderForJson.ps1
Labels: Area-Settings, Product-Terminal

#2603 Add Dynamic Profile Generators
  src/cascadia/LocalTests_TerminalApp/SettingsTests.cpp
  src/cascadia/TerminalApp/AzureCloudShellGenerator.cpp
  src/cascadia/TerminalApp/AzureCloudShellGenerator.h
  src/cascadia/TerminalApp/CascadiaSettings.cpp
  src/cascadia/TerminalApp/CascadiaSettings.h
  src/cascadia/TerminalApp/CascadiaSettingsSerialization.cpp
  src/cascadia/TerminalApp/DefaultProfileUtils.cpp
  src/cascadia/TerminalApp/DefaultProfileUtils.h
  src/cascadia/TerminalApp/IDynamicProfileGenerator.h
  src/cascadia/TerminalApp/LegacyProfileGeneratorNamespaces.h
  src/cascadia/TerminalApp/PowershellCoreProfileGenerator.cpp
  src/cascadia/TerminalApp/PowershellCoreProfileGenerator.h
  src/cascadia/TerminalApp/Profile.cpp
  src/cascadia/TerminalApp/Profile.h
  src/cascadia/TerminalApp/TerminalPage.cpp
  src/cascadia/TerminalApp/WslDistroGenerator.cpp
  src/cascadia/TerminalApp/WslDistroGenerator.h
  src/cascadia/TerminalApp/lib/TerminalAppLib.vcxproj
  src/cascadia/ut_app/DynamicProfileTests.cpp
  src/cascadia/ut_app/JsonTests.cpp
  src/cascadia/ut_app/TerminalApp.UnitTests.vcxproj
  src/cascadia/ut_app/TestDynamicProfileGenerator.h
  src/inc/LibraryIncludes.h
Labels: Area-Settings, Issue-Task, Product-Terminal

#2765 utils: prevent the corruption of GUID strings
  src/types/ut_types/UtilsTests.cpp
  src/types/utils.cpp
Labels: Needs-Second

#2526 Enable Terminal closing with ALT + F4 and warning of multiple open tabs
  src/cascadia/TerminalApp/App.cpp
  src/cascadia/TerminalApp/AppActionHandlers.cpp
  src/cascadia/TerminalApp/Resources/en-US/Resources.resw
  src/cascadia/TerminalApp/TerminalPage.cpp
  src/cascadia/TerminalApp/TerminalPage.h
Labels: Area-User Interface, Issue-Task, Product-Terminal

#2789 Don't explode name-only profiles
  src/cascadia/LocalTests_TerminalApp/SettingsTests.cpp
  src/cascadia/TerminalApp/CascadiaSettingsSerialization.cpp
  src/cascadia/TerminalApp/Profile.cpp
  src/cascadia/TerminalApp/Profile.h
Labels: Area-Settings, Issue-Bug, Needs-Second, Product-Terminal

#2777 Escape HTML entities
  src/buffer/out/textBuffer.cpp
Labels: Needs-Second

#2801 Add `hidden` to the defaults, the userDefaults, and the autogeneratd stubs
  doc/cascadia/SettingsSchema.md
  src/cascadia/TerminalApp/Profile.cpp
  src/cascadia/TerminalApp/defaults.json
  src/cascadia/TerminalApp/userDefaults.json
Labels: Area-Settings, AutoMerge, Needs-Second, Product-Terminal

#2802 Update SignConfig to use SHA2 variant per governance request.
  src/tools/ColorTool/signing/SignConfig.xml
Labels: Area-CodeHealth, Issue-Task, Product-Colortool

#2800 Add validation for hiding all the profiles
  src/cascadia/LocalTests_TerminalApp/SettingsTests.cpp
  src/cascadia/TerminalApp/App.cpp
  src/cascadia/TerminalApp/CascadiaSettings.cpp
  src/cascadia/TerminalApp/Resources/en-US/Resources.resw
  src/cascadia/TerminalApp/TerminalWarnings.h
Labels: Area-Settings, AutoMerge, Issue-Bug, Needs-Second, Product-Terminal

#2816 Initialize the VT tab stops when a buffer is created in VT mode
  src/host/screenInfo.cpp
  src/host/ut_host/ScreenBufferTests.cpp
  src/host/ut_host/SelectionTests.cpp
Labels: Issue-Bug, Product-Conhost

#1964 Fix display of the "low ASCII" glyphs in PC code pages
  src/host/_stream.cpp
Labels: Issue-Bug, Product-Conhost

#2845 Remember last-used string in the Find dialog in conhost
  src/interactivity/win32/find.cpp
Labels: Needs-Second

#2824 Enable VT processing by default for conpty
  src/host/srvinit.cpp
Labels: Issue-Bug, Product-Conpty

#2872 Improve debugging experience of key events...
  src/types/IInputEventStreams.cpp
  src/types/KeyEvent.cpp
  src/types/inc/IInputEvent.hpp
  tools/ConsoleTypes.natvis
Labels: Area-CodeHealth, Issue-Task, Product-Conhost

#2885 Retarget VtPipeTerm & terminalcore-lib to 18362
  src/cascadia/TerminalCore/lib/terminalcore-lib.vcxproj
  src/tools/vtpipeterm/VtPipeTerm.vcxproj
Labels: Area-Build, Needs-Second

#2932 Fix double width cursor for CJK characters
  src/cascadia/TerminalCore/Terminal.hpp
  src/cascadia/TerminalCore/terminalrenderdata.cpp
Labels: Needs-Second

#2705 Fix snapping to the cursor in "Terminal Scrolling" mode
  src/host/getset.cpp
  src/host/ut_host/ScreenBufferTests.cpp
Labels: Area-Server, Issue-Bug, Product-Conhost

#2799 Docs: Update Info on "Copy" Operation
  doc/user-docs/UsingJsonSettings.md
  doc/user-docs/index.md
Labels: Issue-Docs

#2704 Add profiles.json schema to doc folder
  doc/cascadia/SettingsSchema.md
  doc/cascadia/profiles.schema.json
Labels: Issue-Docs

#2938 add note on dynamic profile GUIDs
  doc/user-docs/UsingJsonSettings.md
Labels: Issue-Docs

#2936 Give powershell its own scheme
  src/cascadia/TerminalApp/defaults.json
Labels: Area-Settings, Product-Terminal

#2990 Passthrough BEL in conpty
  src/terminal/parser/OutputStateMachineEngine.cpp
Labels: Area-VT, Needs-Second, Product-Conpty

#2995 Update outdated FAQ
  README.md
Labels: Issue-Docs

#2927 teach wil about c++/winrt exceptions by including cppwinrt.h
  src/cascadia/TerminalApp/lib/pch.h
  src/cascadia/TerminalConnection/pch.h
  src/cascadia/TerminalControl/pch.h
  src/cascadia/TerminalSettings/pch.h
  src/cascadia/WindowsTerminal/pch.h
Labels: Needs-Second
