Repository microsoft/terminal, pull requests merged in 2019-07, with the labels that each got.

#1767 Update the title of the bug report template
  .github/ISSUE_TEMPLATE/Bug_Report.md
Labels: AutoMerge

#1577 The start of some User docs
  doc/user-docs/UsingJsonSettings.md
  doc/user-docs/index.md
Labels: Issue-Docs, Needs-Author-Feedback

#1207 Enable resizing the panes with the keyboard.
  src/cascadia/TerminalApp/App.cpp
  src/cascadia/TerminalApp/App.h
  src/cascadia/TerminalApp/AppKeyBindings.cpp
  src/cascadia/TerminalApp/AppKeyBindings.h
  src/cascadia/TerminalApp/AppKeyBindings.idl
  src/cascadia/TerminalApp/AppKeyBindingsSerialization.cpp
  src/cascadia/TerminalApp/Pane.cpp
  src/cascadia/TerminalApp/Pane.h
  src/cascadia/TerminalApp/Tab.cpp
  src/cascadia/TerminalApp/Tab.h
  src/cascadia/TerminalControl/TermControl.cpp
  src/cascadia/TerminalControl/TermControl.h
  src/cascadia/TerminalControl/TermControl.idl
Labels: Area-User Interface, Product-Terminal

#1901 Add Vintage color scheme to defaults; fixes #1781
  src/cascadia/TerminalApp/CascadiaSettings.cpp
Labels: AutoMerge

#1807 Fix margin boundary tests in the RI, DL, and IL escape sequences.
  src/host/getset.cpp
  src/host/screenInfo.cpp
  src/host/screenInfo.hpp
  src/host/ut_host/ScreenBufferTests.cpp
Labels: Area-VT, Product-Conhost

#1107 Implement background image over acrylic or solid color
  src/cascadia/TerminalControl/TermControl.cpp
  src/cascadia/TerminalControl/TermControl.h
Labels: Needs-Attention

#1273 Multi-Click Selection: Double-Click Settings
  src/cascadia/TerminalApp/Profile.cpp
  src/cascadia/TerminalApp/Profile.h
  src/cascadia/TerminalCore/Terminal.cpp
  src/cascadia/TerminalCore/Terminal.hpp
  src/cascadia/TerminalSettings/ICoreSettings.idl
  src/cascadia/TerminalSettings/TerminalSettings.cpp
  src/cascadia/TerminalSettings/terminalsettings.h
  src/inc/DefaultSettings.h
Labels: Area-User Interface

#1648 Obstruct the user when they try to run WT under WOW
  src/cascadia/WindowsTerminal/WindowsTerminal.rc
  src/cascadia/WindowsTerminal/main.cpp
  src/cascadia/WindowsTerminal/pch.h
  src/cascadia/WindowsTerminal/resource.h
Labels: AutoMerge

#1921 Fix wrong maximized window offset on non primary monitors
  src/cascadia/WindowsTerminal/NonClientIslandWindow.cpp
Labels: AutoMerge

#1887 Added links to user docs inside About popup
  src/cascadia/CascadiaPackage/Resources/en-US/Resources.resw
  src/cascadia/TerminalApp/App.cpp
  src/cascadia/TerminalApp/pch.h
Labels: AutoMerge

#1274 allow DX rendering engine to run on windows 7
  src/renderer/dx/CustomTextLayout.cpp
  src/renderer/dx/CustomTextLayout.h
  src/renderer/dx/CustomTextRenderer.cpp
  src/renderer/dx/DxRenderer.cpp
  src/renderer/dx/DxRenderer.hpp
Labels: Area-Rendering

#1197 Double and Triple Click Selection
  doc/cascadia/SettingsSchema.md
  src/cascadia/TerminalApp/GlobalAppSettings.cpp
  src/cascadia/TerminalApp/GlobalAppSettings.h
  src/cascadia/TerminalControl/TermControl.cpp
  src/cascadia/TerminalControl/TermControl.h
  src/cascadia/TerminalCore/Terminal.cpp
  src/cascadia/TerminalCore/Terminal.hpp
  src/cascadia/TerminalCore/TerminalSelection.cpp
  src/cascadia/TerminalSettings/ICoreSettings.idl
  src/cascadia/TerminalSettings/TerminalSettings.cpp
  src/cascadia/TerminalSettings/terminalsettings.h
  src/cascadia/UnitTests_TerminalCore/ScreenSizeLimitsTest.cpp
  src/inc/DefaultSettings.h
Labels: Area-User Interface

#1898 Don't NCPAINT our window, PAINT our window
  src/cascadia/WindowsTerminal/BaseWindow.h
  src/cascadia/WindowsTerminal/NonClientIslandWindow.cpp
  src/cascadia/WindowsTerminal/NonClientIslandWindow.h
Labels: Area-User Interface, Product-Terminal

#1935 Force the use of v2 (non-legacy) conhost when in ConPTY mode
  src/host/exemain.cpp
Labels: Product-Conpty

#1974 Mark ESC as handled so that it doesn't come back in CharacterHandler
  src/cascadia/TerminalCore/Terminal.cpp
  src/inc/unicode.hpp
Labels: Area-TerminalControl, Product-Terminal

#2018 Roll up dependencies through TerminalApp so the package is right
  build/pipelines/templates/build-console-steps.yml
  build/scripts/Test-WindowsTerminalPackage.ps1
  src/cascadia/CascadiaPackage/CascadiaPackage.wapproj
  src/cascadia/WindowsTerminal/WindowsTerminal.vcxproj
Labels: Area-Build

#1948 Enable dragging with the entire titlebar
  src/cascadia/TerminalApp/App.cpp
  src/cascadia/TerminalApp/App.h
  src/cascadia/TerminalApp/App.idl
  src/cascadia/TerminalApp/MinMaxCloseControl.cpp
  src/cascadia/TerminalApp/MinMaxCloseControl.h
  src/cascadia/TerminalApp/MinMaxCloseControl.idl
  src/cascadia/TerminalApp/MinMaxCloseControl.xaml
  src/cascadia/TerminalApp/TabRowControl.cpp
  src/cascadia/TerminalApp/TabRowControl.h
  src/cascadia/TerminalApp/TabRowControl.idl
  src/cascadia/TerminalApp/TabRowControl.xaml
  src/cascadia/TerminalApp/TerminalApp.vcxproj
  src/cascadia/TerminalApp/TerminalPage.cpp
  src/cascadia/TerminalApp/TerminalPage.h
  src/cascadia/TerminalApp/TerminalPage.idl
  src/cascadia/TerminalApp/TerminalPage.xaml
  src/cascadia/TerminalApp/TitlebarControl.cpp
  src/cascadia/TerminalApp/TitlebarControl.h
  src/cascadia/TerminalApp/TitlebarControl.idl
  src/cascadia/TerminalApp/TitlebarControl.xaml
  src/cascadia/TerminalApp/lib/TerminalAppLib.vcxproj
  src/cascadia/WindowsTerminal/AppHost.cpp
  src/cascadia/WindowsTerminal/AppHost.h
  src/cascadia/WindowsTerminal/IslandWindow.cpp
  src/cascadia/WindowsTerminal/IslandWindow.h
  src/cascadia/WindowsTerminal/NonClientIslandWindow.cpp
  src/cascadia/WindowsTerminal/NonClientIslandWindow.h
Labels: Area-User Interface, Product-Terminal

#2012 Add a keybinding for ClosePane
  src/cascadia/TerminalApp/App.cpp
  src/cascadia/TerminalApp/App.h
  src/cascadia/TerminalApp/AppKeyBindings.cpp
  src/cascadia/TerminalApp/AppKeyBindings.h
  src/cascadia/TerminalApp/AppKeyBindings.idl
  src/cascadia/TerminalApp/AppKeyBindingsSerialization.cpp
  src/cascadia/TerminalApp/CascadiaSettings.cpp
  src/cascadia/TerminalApp/Pane.cpp
  src/cascadia/TerminalApp/Pane.h
  src/cascadia/TerminalApp/Tab.cpp
  src/cascadia/TerminalApp/Tab.h
Labels: Area-User Interface, Product-Terminal

#2043 Automatically generate an SxS manifest for WindowsTerminal
  build/rules/GenerateSxsManifestsFromWinmds.targets
  src/cascadia/WindowsTerminal/WindowsTerminal.manifest
  src/cascadia/WindowsTerminal/WindowsTerminal.vcxproj
Labels: Area-Build, Product-Terminal

#1942 Doc of stuff I've explained.
  doc/Niksa.md
Labels: Issue-Docs

#2081 Fix a couple of the DEC Special Graphics characters
  src/terminal/adapter/terminalOutput.cpp
Labels: AutoMerge

#2107 Make sure to apply the theme on load of the application
  src/cascadia/TerminalApp/App.cpp
Labels: Area-User Interface, Product-Terminal

#1237 Initializes conhost's Campbell color scheme in conhost order instead of ANSI/VT order
  src/host/settings.cpp
  src/types/inc/utils.hpp
  src/types/ut_types/UtilsTests.cpp
  src/types/utils.cpp
Labels: AutoMerge, Product-Conhost

#2117 If a profile did not have a GUID, generate one
  src/cascadia/TerminalApp/Profile.cpp
  src/cascadia/ut_app/JsonTests.cpp
Labels: Area-Settings, Issue-Bug

#2118 Prevent a crash on resizing too small caused by the Titlebar
  src/cascadia/TerminalApp/TitlebarControl.cpp
Labels: Area-User Interface, Issue-Bug, Product-Terminal

#2115 Change "Summary"->"Description" in the Feature Request Template
  .github/ISSUE_TEMPLATE/Feature_Request.md
Labels: Issue-Docs

#2122 Fix the About Dialog II: This Time it's Optional
  src/cascadia/TerminalApp/App.cpp
Labels: Area-User Interface, Issue-Bug, Product-Terminal
