Repository microsoft/terminal, pull requests merged in 2019-06, with the labels that each got.

#1140 Add explicit "validation steps" to PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Area-Build, AutoMerge, Issue-Task, Product-Meta

#1005 Switch to jsoncpp as our json library
  NOTICE.md
  dep/jsoncpp/README.md
  dep/jsoncpp/json/json-forwards.h
  dep/jsoncpp/json/json.h
  dep/jsoncpp/jsoncpp.cpp
  src/cascadia/TerminalApp/App.h
  src/cascadia/TerminalApp/AppKeyBindings.cpp
  src/cascadia/TerminalApp/AppKeyBindings.h
  src/cascadia/TerminalApp/AppKeyBindings.idl
  src/cascadia/TerminalApp/AppKeyBindingsSerialization.cpp
  src/cascadia/TerminalApp/AppKeyBindingsSerialization.h
  src/cascadia/TerminalApp/CascadiaSettings.h
  src/cascadia/TerminalApp/CascadiaSettingsSerialization.cpp
  src/cascadia/TerminalApp/ColorScheme.cpp
  src/cascadia/TerminalApp/ColorScheme.h
  src/cascadia/TerminalApp/GlobalAppSettings.cpp
  src/cascadia/TerminalApp/GlobalAppSettings.h
  src/cascadia/TerminalApp/Profile.cpp
  src/cascadia/TerminalApp/Profile.h
  src/cascadia/TerminalApp/TerminalApp.vcxproj
  src/cascadia/TerminalApp/Utils.cpp
  src/cascadia/TerminalApp/Utils.h
  src/cascadia/TerminalApp/pch.h
  src/types/inc/utils.hpp
  src/types/utils.cpp
Labels: Area-Settings, Issue-Task, Product-Terminal

#1144 Fix build warnings and namespace issues introduced by GitHub merge
  src/interactivity/base/VtApiRedirection.cpp
  src/interactivity/onecore/BgfxEngine.cpp
  src/interactivity/onecore/ConIoSrvComm.cpp
  src/interactivity/onecore/ConsoleInputThread.cpp
Labels: Area-Build, Issue-Bug, Product-Meta

#967 Docs: Contributor's guide and spec-template
  .gitignore
  doc/contributing.md
  doc/images/new-issue-template.png
  doc/specs/spec-template.md
Labels: Issue-Docs, Product-Meta

#1113 Fix OpenConsole.psm1 to use vswhere
  .gitignore
  tools/OpenConsole.psm1
Labels: AutoMerge

#825 Add support for multiple panes in the same window
  doc/cascadia/Panes.md
  src/cascadia/TerminalApp/App.cpp
  src/cascadia/TerminalApp/App.h
  src/cascadia/TerminalApp/AppKeyBindings.cpp
  src/cascadia/TerminalApp/AppKeyBindings.h
  src/cascadia/TerminalApp/AppKeyBindings.idl
  src/cascadia/TerminalApp/Pane.cpp
  src/cascadia/TerminalApp/Pane.h
  src/cascadia/TerminalApp/Tab.cpp
  src/cascadia/TerminalApp/Tab.h
  src/cascadia/TerminalApp/TerminalApp.vcxproj
  src/cascadia/TerminalControl/TermControl.cpp
  src/cascadia/TerminalControl/TermControl.h
  src/cascadia/TerminalControl/TermControl.idl
Labels: Area-User Interface, Issue-Task

#1191 Support any number of leading zeros in VT parameter values
  src/terminal/parser/stateMachine.cpp
  src/terminal/parser/ut_parser/OutputEngineTest.cpp
Labels: Area-VT, Product-Conhost

#1199 Properly manage teardown state in TermControl
  src/cascadia/TerminalApp/App.cpp
  src/cascadia/TerminalControl/TermControl.cpp
  src/cascadia/TerminalControl/TermControl.h
Labels: Severity-Crash

#1214 Re-enable serialization for OpenSettings
  src/cascadia/TerminalApp/AppKeyBindingsSerialization.cpp
Labels: AutoMerge

#1196 Add an about dialog with the version number
  src/cascadia/CascadiaPackage/Resources/en-US/Resources.resw
  src/cascadia/TerminalApp/App.cpp
  src/cascadia/TerminalApp/App.h
  src/cascadia/TerminalApp/pch.h
Labels: Area-User Interface, Product-Terminal

#1267 The InputStateMachine should dispatch Intermediate characters
  OpenConsole.sln
  src/terminal/parser/IStateMachineEngine.hpp
  src/terminal/parser/InputStateMachineEngine.cpp
  src/terminal/parser/InputStateMachineEngine.hpp
  src/terminal/parser/OutputStateMachineEngine.cpp
  src/terminal/parser/OutputStateMachineEngine.hpp
  src/terminal/parser/stateMachine.cpp
  src/terminal/parser/ut_parser/InputEngineTest.cpp
Labels: Area-Input, Area-VT, Product-Conpty

#1259 Don't always send an uppercase letter for Alt+key
  src/cascadia/TerminalCore/Terminal.cpp
  src/cascadia/UnitTests_TerminalCore/InputTest.cpp
  src/cascadia/UnitTests_TerminalCore/UnitTests.vcxproj
Labels: Area-Input, Product-Terminal

#1296 Move build prerequisites into 'Developer Guidance' (right before buil…
  README.md
Labels: AutoMerge

#1283 Code highlighting and capitalization fix for doc/EXCEPTIONS.md
  doc/EXCEPTIONS.md
Labels: AutoMerge

#1248 Captured pointer for SwapChainPanel and ScrollBar separately
  src/cascadia/TerminalControl/TermControl.cpp
  src/cascadia/TerminalControl/TermControl.h
Labels: Area-TerminalControl, Product-Terminal

#883 adding profiles.json documentation
  doc/cascadia/SettingsSchema.md
Labels: Issue-Docs

#1254 Bugfix: crash on copying resized selection
  src/cascadia/TerminalCore/Terminal.cpp
Labels: Area-User Interface

#1293 Switch away from Windows.Storage.ApplicationData
  src/cascadia/TerminalApp/App.cpp
  src/cascadia/TerminalApp/CascadiaSettings.h
  src/cascadia/TerminalApp/CascadiaSettingsSerialization.cpp
  src/cascadia/TerminalApp/pch.h
Labels: Area-Settings

#1306 Update the package base version to 0.2
  src/cascadia/CascadiaPackage/CascadiaPackage.wapproj
Labels: Area-Build, Product-Terminal

#1326 CreateFile with the right flags
  src/cascadia/TerminalApp/CascadiaSettingsSerialization.cpp
Labels: AutoMerge

#1340 Fix the total teardown order for ConhostConnection
  src/cascadia/TerminalConnection/ConhostConnection.cpp
Labels: AutoMerge

#1263 fallback to software rendering
  src/renderer/dx/DxRenderer.cpp
  src/renderer/dx/DxRenderer.hpp
Labels: Area-Rendering

#929 Apply a GDI region to the top level Island window to allow dragging with a single Xaml Island
  OpenConsole.sln
  src/cascadia/Microsoft.UI.Xaml.Markup/Microsoft.UI.Xaml.Markup.def
  src/cascadia/Microsoft.UI.Xaml.Markup/Microsoft.UI.Xaml.Markup.vcxproj
  src/cascadia/Microsoft.UI.Xaml.Markup/ReadMe.md
  src/cascadia/Microsoft.UI.Xaml.Markup/XamlApplication.cpp
  src/cascadia/Microsoft.UI.Xaml.Markup/XamlApplication.h
  src/cascadia/Microsoft.UI.Xaml.Markup/XamlApplication.idl
  src/cascadia/Microsoft.UI.Xaml.Markup/packages.config
  src/cascadia/Microsoft.UI.Xaml.Markup/pch.cpp
  src/cascadia/Microsoft.UI.Xaml.Markup/pch.h
  src/cascadia/TerminalApp/App.base.h
  src/cascadia/TerminalApp/App.cpp
  src/cascadia/TerminalApp/App.h
  src/cascadia/TerminalApp/App.idl
  src/cascadia/TerminalApp/App.xaml
  src/cascadia/TerminalApp/MinMaxCloseControl.cpp
  src/cascadia/TerminalApp/MinMaxCloseControl.h
  src/cascadia/TerminalApp/MinMaxCloseControl.idl
  src/cascadia/TerminalApp/MinMaxCloseControl.xaml
  src/cascadia/TerminalApp/TerminalApp.vcxproj
  src/cascadia/TerminalApp/packages.config
  src/cascadia/TerminalApp/pch.h
  src/cascadia/WindowsTerminal/AppHost.cpp
  src/cascadia/WindowsTerminal/BaseWindow.h
  src/cascadia/WindowsTerminal/IslandWindow.cpp
  src/cascadia/WindowsTerminal/IslandWindow.h
  src/cascadia/WindowsTerminal/NonClientIslandWindow.cpp
  src/cascadia/WindowsTerminal/NonClientIslandWindow.h
  src/cascadia/WindowsTerminal/WindowsTerminal.manifest
  src/cascadia/WindowsTerminal/WindowsTerminal.vcxproj
  src/cascadia/WindowsTerminal/main.cpp
  src/cascadia/WindowsTerminal/packages.config
  src/cascadia/WindowsTerminal/pch.h
Labels: Area-User Interface, Issue-Task, Product-Terminal

#1052 Add feature to ColorTool to write color scheme as JSON for Windows Terminal (issue #986)
  src/tools/ColorTool/ColorTool/ColorScheme.cs
  src/tools/ColorTool/ColorTool/ConsoleTargets/TerminalSchemeConsoleTarget.cs
  src/tools/ColorTool/ColorTool/Program.cs
  src/tools/ColorTool/ColorTool/Resources.resx
  src/tools/ColorTool/ColorTool/SchemeParsers/IniSchemeParser.cs
  src/tools/ColorTool/ColorTool/SchemeParsers/JsonParser.cs
  src/tools/ColorTool/ColorTool/SchemeParsers/SchemeParserBase.cs
  src/tools/ColorTool/ColorTool/SchemeParsers/XmlSchemeParser.cs
Labels: Product-Colortool

#1678 Update bot doc for In-PR label rule
  doc/bot.md
Labels: Area-Build, Issue-Task, Product-Meta

#1279 Revoke old event handlers correctly on pane close
  src/cascadia/TerminalApp/Pane.cpp
Labels: Area-User Interface
