Repository microsoft/terminal, pull requests merged in 2019-10, with the labels that each got.

#2831 make filling chars (and, thus, erase line/char) unset wrap
  src/buffer/out/Row.cpp
  src/buffer/out/Row.hpp
  src/buffer/out/textBuffer.cpp
  src/buffer/out/textBuffer.hpp
  src/host/_output.cpp
  src/host/ft_host/API_FillOutputTests.cpp
  src/host/screenInfo.cpp
  src/host/screenInfo.hpp
  src/host/ut_host/TextBufferTests.cpp
Labels: Needs-Second

#2924 Patch fix for #1360 until WriteStream (#780) can be implemented.
  src/cascadia/TerminalCore/Terminal.cpp
  src/cascadia/UnitTests_TerminalCore/TerminalApiTests.cpp
  src/cascadia/UnitTests_TerminalCore/UnitTests.vcxproj
Labels: AutoMerge

#2972 docs: Fix Typo in README.md
  README.md
Labels: Issue-Docs, Needs-Second

#2987 When reverse indexing, preserve RGB/256 attributes
  src/host/getset.cpp
  src/host/ut_host/ScreenBufferTests.cpp
Labels: Area-VT, Needs-Second, Product-Conhost

#2996 CUU and CUD should not move "across" margins.
  src/host/getset.cpp
  src/host/ut_host/ScreenBufferTests.cpp
Labels: Area-VT, Issue-Bug, Needs-Second, Product-Conhost

#3026 Remove a stray inclusion of an old Windows.ImplementationLibrary package
  src/cascadia/WindowsTerminal/WindowsTerminal.vcxproj
Labels: Area-Build, Needs-Second, Product-Terminal

#3024 Simplify non-client hit testing in NCIslandWindow to fix doubleclick
  src/cascadia/WindowsTerminal/NonClientIslandWindow.cpp
  src/cascadia/WindowsTerminal/NonClientIslandWindow.h
Labels: Area-User Interface, Needs-Second, Product-Terminal

#3025 Propagate window style changes to the titlebar and minmax
  src/cascadia/TerminalApp/MinMaxCloseControl.cpp
  src/cascadia/TerminalApp/MinMaxCloseControl.h
  src/cascadia/TerminalApp/MinMaxCloseControl.idl
  src/cascadia/TerminalApp/TitlebarControl.cpp
  src/cascadia/TerminalApp/TitlebarControl.h
  src/cascadia/TerminalApp/TitlebarControl.idl
  src/cascadia/WindowsTerminal/NonClientIslandWindow.cpp
Labels: Area-User Interface, Needs-Second, Product-Terminal

#2651 Prevent the v1 propsheet from zeroing colors, causing black text on black background.
  src/propsheet/PropSheetHandler.cpp
  src/propsheet/console.cpp
  src/propsheet/console.h
  src/propsheet/globals.cpp
  src/propsheet/registry.cpp
  src/propslib/ShortcutSerialization.cpp
  src/propslib/ShortcutSerialization.hpp
  tools/bx.ps1
  tools/opencon.cmd
Labels: Issue-Bug, Needs-Second, Product-Conhost

#2829 Render the cursor state to VT
  src/host/ut_host/VtRendererTests.cpp
  src/renderer/vt/XtermEngine.cpp
  src/renderer/vt/XtermEngine.hpp
  src/renderer/vt/vtrenderer.hpp
Labels: Issue-Bug, Needs-Second, Product-Conpty

#3015 Don't put NUL in the buffer in VT mode
  src/host/ut_host/ScreenBufferTests.cpp
  src/terminal/parser/OutputStateMachineEngine.cpp
Labels: Area-VT, Product-Conhost

#2998 Edits doc section: Starting Windows Terminal
  doc/user-docs/index.md
Labels: Issue-Docs

#3005 [contributing.md] add how to report security bugs
  doc/contributing.md
Labels: Issue-Docs

#2823 Return to ground when we flush the last char
  src/terminal/parser/stateMachine.cpp
  src/terminal/parser/ut_parser/InputEngineTest.cpp
  src/terminal/parser/ut_parser/Parser.UnitTests-common.vcxproj
  src/terminal/parser/ut_parser/Parser.UnitTests.vcxproj
  tools/bcz.cmd
Labels: Issue-Bug, Needs-Second, Product-Conhost

#3031 Layer the globals globals on top of the root globals
  src/cascadia/LocalTests_TerminalApp/SettingsTests.cpp
  src/cascadia/TerminalApp/CascadiaSettingsSerialization.cpp
Labels: Area-Settings, Product-Terminal

#3087 Updates path to profiles.json
  doc/user-docs/UsingJsonSettings.md
Labels: Needs-Second

#3106 health: get rid of our hand-rolled sprintf->wstring helpers, prefer WIL
  src/cascadia/TerminalConnection/AzureConnection.cpp
  src/cascadia/TerminalConnection/AzureConnection.h
  src/cascadia/WindowsTerminal/main.cpp
  src/types/utils.cpp
Labels: Area-CodeHealth

#3138 Turn source linking back on for WinDBG style so we at least have one …
  build/pipelines/templates/build-console-steps.yml
  build/scripts/Index-Pdbs.ps1
Labels: Area-Build, Issue-Task, Product-Conhost, Product-Terminal

#2004 add wpf control
  OpenConsole.sln
  src/buffer/out/textBuffer.hpp
  src/cascadia/PublicTerminalCore/HwndTerminal.cpp
  src/cascadia/PublicTerminalCore/HwndTerminal.hpp
  src/cascadia/PublicTerminalCore/PublicTerminalCore.vcxproj
  src/cascadia/PublicTerminalCore/PublicTerminalCore.vcxproj.filters
  src/cascadia/PublicTerminalCore/pch.cpp
  src/cascadia/PublicTerminalCore/pch.h
  src/cascadia/TerminalControl/TermControl.cpp
  src/cascadia/TerminalCore/ITerminalApi.hpp
  src/cascadia/TerminalCore/ITerminalInput.hpp
  src/cascadia/TerminalCore/Terminal.cpp
  src/cascadia/TerminalCore/Terminal.hpp
  src/cascadia/WpfTerminalControl/ITerminalConnection.cs
  src/cascadia/WpfTerminalControl/NativeMethods.cs
  src/cascadia/WpfTerminalControl/TerminalContainer.cs
  src/cascadia/WpfTerminalControl/TerminalControl.xaml
  src/cascadia/WpfTerminalControl/TerminalControl.xaml.cs
  src/cascadia/WpfTerminalControl/TerminalOutputEventArgs.cs
  src/cascadia/WpfTerminalControl/TerminalTheme.cs
  src/cascadia/WpfTerminalControl/WpfTerminalControl.csproj
  src/cascadia/WpfTerminalControl/stylecop.json
  src/renderer/dx/DxRenderer.cpp
  src/renderer/inc/IRenderData.hpp
  src/renderer/inc/IRenderThread.hpp
  src/renderer/inc/IRenderer.hpp
  src/terminal/input/terminalInput.cpp
  src/terminal/input/terminalInput.hpp
  src/terminal/parser/IStateMachineEngine.hpp
Labels: Needs-Second

#3107 Allow FontInfo{,Base,Desired} to store a font name > 32 wch
  src/buffer/out/textBuffer.cpp
  src/buffer/out/textBuffer.hpp
  src/host/getset.cpp
  src/host/output.cpp
  src/host/renderFontDefaults.cpp
  src/host/renderFontDefaults.hpp
  src/host/selection.cpp
  src/host/selection.hpp
  src/host/settings.cpp
  src/host/settings.hpp
  src/host/srvinit.cpp
  src/host/telemetry.cpp
  src/interactivity/onecore/SystemConfigurationProvider.cpp
  src/interactivity/onecore/SystemConfigurationProvider.hpp
  src/interactivity/win32/menu.cpp
  src/renderer/base/FontInfoBase.cpp
  src/renderer/base/FontInfoDesired.cpp
  src/renderer/base/fontinfo.cpp
  src/renderer/dx/DxRenderer.cpp
  src/renderer/gdi/state.cpp
  src/renderer/inc/FontInfo.hpp
  src/renderer/inc/FontInfoBase.hpp
  src/renderer/inc/FontInfoDesired.hpp
  src/renderer/inc/IFontDefaultList.hpp
Labels: Needs-Author-Feedback

#3035 Improve the Readme
  README.md
Labels: Issue-Docs

#3033 Add a warning when a profile has an unknown color scheme
  src/cascadia/LocalTests_TerminalApp/ColorSchemeTests.cpp
  src/cascadia/LocalTests_TerminalApp/SettingsTests.cpp
  src/cascadia/TerminalApp/App.cpp
  src/cascadia/TerminalApp/CascadiaSettings.cpp
  src/cascadia/TerminalApp/CascadiaSettings.h
  src/cascadia/TerminalApp/CascadiaSettingsSerialization.cpp
  src/cascadia/TerminalApp/GlobalAppSettings.cpp
  src/cascadia/TerminalApp/GlobalAppSettings.h
  src/cascadia/TerminalApp/Profile.cpp
  src/cascadia/TerminalApp/Profile.h
  src/cascadia/TerminalApp/Resources/en-US/Resources.resw
  src/cascadia/TerminalApp/TerminalWarnings.h
  src/cascadia/ut_app/JsonTests.cpp
Labels: Area-Settings, Product-Terminal

#3027 Upgrade to Microsoft.UI.Xaml 2.2
  build/rules/GenerateSxsManifestsFromWinmds.targets
  src/cascadia/CascadiaPackage/CascadiaPackage.wapproj
  src/cascadia/LocalTests_TerminalApp/TerminalApp.LocalTests.vcxproj
  src/cascadia/TerminalApp/App.h
  src/cascadia/TerminalApp/App.xaml
  src/cascadia/TerminalApp/MinMaxCloseControl.xaml
  src/cascadia/TerminalApp/Tab.cpp
  src/cascadia/TerminalApp/TabRowControl.cpp
  src/cascadia/TerminalApp/TabRowControl.h
  src/cascadia/TerminalApp/TabRowControl.idl
  src/cascadia/TerminalApp/TabRowControl.xaml
  src/cascadia/TerminalApp/TerminalPage.cpp
  src/cascadia/TerminalApp/TerminalPage.h
  src/cascadia/TerminalApp/TitlebarControl.cpp
  src/cascadia/TerminalApp/TitlebarControl.h
  src/cascadia/TerminalApp/TitlebarControl.idl
  src/cascadia/TerminalApp/TitlebarControl.xaml
  src/cascadia/TerminalApp/Utils.cpp
  src/cascadia/TerminalApp/Utils.h
  src/cascadia/TerminalApp/lib/TerminalAppLib.vcxproj
  src/cascadia/TerminalApp/packages.config
  src/cascadia/TerminalControl/TermControl.cpp
  src/cascadia/TerminalControl/TermControl.h
  src/cascadia/WindowsTerminal/NonClientIslandWindow.cpp
  src/cascadia/WindowsTerminal/WindowsTerminal.vcxproj
  src/cascadia/WindowsTerminal/packages.config
  src/cascadia/ut_app/TerminalApp.UnitTests.vcxproj
Labels: Needs-Second

#3198 Replace ExpandEnvironmentStrings double calling with wil helper
  src/host/ft_host/API_FontTests.cpp
  src/host/ft_host/CanaryTests.cpp
  src/host/ft_host/Common.cpp
  src/host/ft_host/Common.hpp
  src/server/Entrypoints.cpp
Labels: Needs-Second

#2928 TermControl: force all ambiguous glyphs to be narrow
  src/cascadia/TerminalControl/TermControl.cpp
Labels: Area-TerminalControl, Issue-Bug, Product-Terminal

#2817 Enable setting an initial position and maximization launch for Terminal
  src/cascadia/TerminalApp/App.cpp
  src/cascadia/TerminalApp/App.h
  src/cascadia/TerminalApp/App.idl
  src/cascadia/TerminalApp/GlobalAppSettings.cpp
  src/cascadia/TerminalApp/GlobalAppSettings.h
  src/cascadia/WindowsTerminal/AppHost.cpp
  src/cascadia/WindowsTerminal/AppHost.h
  src/cascadia/WindowsTerminal/BaseWindow.h
  src/cascadia/WindowsTerminal/IslandWindow.cpp
  src/cascadia/WindowsTerminal/IslandWindow.h
  src/cascadia/WindowsTerminal/NonClientIslandWindow.h
  src/cascadia/WindowsTerminal/pch.h
Labels: Needs-Author-Feedback

#2959 Reduce text layout CPU usage when DWrite analysis is not needed
  src/renderer/dx/CustomTextLayout.cpp
Labels: Area-Performance, Area-Rendering

#3214 Make sure we resize the region even when the drag bar didn't change
  src/cascadia/WindowsTerminal/NonClientIslandWindow.cpp
Labels: Needs-Second

#3215 html: make sure we allocate enough space for the \0, always close
  src/interactivity/win32/Clipboard.cpp
Labels: Needs-Second

#3213 Switch all of the UIA providers to WRL::RuntimeClass
  src/cascadia/TerminalControl/UiaTextRange.cpp
  src/cascadia/TerminalControl/UiaTextRange.hpp
  src/cascadia/WindowsTerminal/WindowUiaProvider.cpp
  src/cascadia/WindowsTerminal/WindowUiaProvider.hpp
  src/cascadia/WindowsTerminal/main.cpp
  src/interactivity/win32/uiaTextRange.cpp
  src/interactivity/win32/uiaTextRange.hpp
  src/interactivity/win32/ut_interactivity_win32/UiaTextRangeTests.cpp
  src/interactivity/win32/windowUiaProvider.cpp
  src/interactivity/win32/windowUiaProvider.hpp
  src/types/ScreenInfoUiaProviderBase.cpp
  src/types/ScreenInfoUiaProviderBase.h
  src/types/UiaTextRangeBase.cpp
  src/types/UiaTextRangeBase.hpp
  src/types/WindowUiaProviderBase.cpp
  src/types/WindowUiaProviderBase.hpp
Labels: Needs-Second

#2965 Fix potential cursor redrawing crash
  src/cascadia/TerminalCore/Terminal.cpp
Labels: Needs-Second, Severity-Blocking

#2937 Reduce InsertAttrRuns CPU usage
  src/buffer/out/AttrRow.cpp
Labels: Area-Output, Area-Performance, Product-Conhost

#3284 Update README.md
  README.md
Labels: Issue-Docs

#2930 Introduce UiaRenderer project
  OpenConsole.sln
  src/renderer/uia/UiaRenderer.cpp
  src/renderer/uia/UiaRenderer.hpp
  src/renderer/uia/lib/uia.vcxproj
  src/renderer/uia/precomp.cpp
  src/renderer/uia/precomp.h
Labels: Needs-Second

#3368 Add support for the HPA escape sequence
  src/terminal/parser/OutputStateMachineEngine.cpp
  src/terminal/parser/OutputStateMachineEngine.hpp
  src/terminal/parser/ut_parser/OutputEngineTest.cpp
Labels: Needs-Second, Product-Conhost

#3371 Get rid of the SCREEN_INFORMATION::LineChar array
  src/host/popup.cpp
  src/host/screenInfo.cpp
  src/host/screenInfo.hpp
Labels: Needs-Second

#2975 Added <kbd> notations for keyboard keys.
  doc/user-docs/index.md
Labels: Issue-Docs, Needs-Second
