Repository microsoft/terminal, pull requests merged in 2019-05, with the labels that each got.

#599 make closeOnExit: true the default
  src/cascadia/TerminalApp/Profile.cpp
  src/cascadia/TerminalSettings/TerminalSettings.cpp
Labels: Issue-Bug

#628 close one tab by press ctrl-w and hide the bar
  src/cascadia/TerminalApp/App.cpp
Labels: Area-User Interface, Issue-Bug

#739 Fixed duplicate line in TermControl (#732)
  src/cascadia/TerminalControl/TermControl.cpp
Labels: Area-TerminalControl, Issue-Bug

#726 doc: append Debugging section with instructions to enable debugging
  README.md
Labels: Issue-Docs

#730 Improve the formatting of keyboard keys
  README.md
Labels: Issue-Docs

#686 Blink the cursor
  src/cascadia/TerminalControl/TermControl.cpp
  src/cascadia/TerminalControl/TermControl.h
  src/cascadia/TerminalCore/Terminal.cpp
  src/cascadia/TerminalCore/Terminal.hpp
Labels: Area-TerminalControl, Issue-Feature

#737 fix tab control and tabs is not synced after focused tab is removed
  src/cascadia/TerminalApp/App.cpp
Labels: Issue-Bug

#765 Reflect new AppNameDev in readme
  README.md
Labels: Issue-Docs

#777 Update README.md
  README.md
Labels: Issue-Docs

#786 Fix WIL doc summary
  doc/WIL.md
Labels: Issue-Docs

#785 Fixed a bug where terminal won't build when local user folder has spaces
  src/cppwinrt.build.post.props
Labels: Area-Build

#784 Add link to related console-docs GH repository
  README.md
Labels: Issue-Docs

#793 inbox: reflect incoming changes from Windows
  src/project.inc
  src/project.unittest.inc
  src/renderer/vt/sources.inc
Labels: Area-Build

#746 Changes to be able to quit the application via exit inside a CLI prompt.
  src/cascadia/TerminalApp/App.cpp
  src/cascadia/TerminalApp/App.h
  src/cascadia/TerminalApp/App.idl
  src/cascadia/WindowsTerminal/AppHost.cpp
  src/cascadia/WindowsTerminal/AppHost.h
  src/cascadia/WindowsTerminal/IslandWindow.cpp
  src/cascadia/WindowsTerminal/IslandWindow.h
Labels: Issue-Bug

#747 Added Keybindings for go up and go down page
  src/cascadia/TerminalApp/App.cpp
  src/cascadia/TerminalApp/App.h
  src/cascadia/TerminalApp/AppKeyBindings.cpp
  src/cascadia/TerminalApp/AppKeyBindings.h
  src/cascadia/TerminalApp/AppKeyBindings.idl
  src/cascadia/TerminalApp/CascadiaSettings.cpp
  src/cascadia/TerminalControl/TermControl.cpp
  src/cascadia/TerminalControl/TermControl.h
  src/cascadia/TerminalControl/TermControl.idl
Labels: Area-Settings, Issue-Feature

#742 Amend Color array to typed values
  src/cascadia/TerminalApp/ColorScheme.cpp
Labels: Area-Settings, Issue-Feature

#762 Added a pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Issue-Docs

#834 Added documentation policy to README.md
  README.md
Labels: Issue-Docs

#704 Fixed typo's and improved consistency.
  doc/AddASetting.md
  doc/ConsoleCtrlEvent.md
  doc/ConsoleHostSettings.md
  doc/Debugging.md
  doc/ORGANIZATION.md
  doc/UniversalTest.md
  doc/WindowsTestPasses.md
  doc/building.md
Labels: Issue-Docs

#811 ci: Restore Taef.TestAdapter before build to run tests in CI
  build/.nuget/packages.config
  build/config/NuGet.config
  build/pipelines/templates/build-console-steps.yml
Labels: Area-Build

#838 doc: add some new issue templates
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/Bug_Report.md
  .github/ISSUE_TEMPLATE/Documentation_Issue.md
  .github/ISSUE_TEMPLATE/Feature_Request.md
  .github/ISSUE_TEMPLATE/Guidance_Issue.md
Labels: Issue-Docs

#847 fixed on build error xcopy on localized machines
  src/cppwinrt.build.post.props
Labels: AutoMerge

#831 Delete the keybinding for NewTabProfile9 and SwitchToTab9
  src/cascadia/TerminalApp/AppKeyBindings.cpp
  src/cascadia/TerminalApp/AppKeyBindings.idl
  src/cascadia/TerminalApp/CascadiaSettings.cpp
Labels: AutoMerge

#871 Fix signatures of some callback functions
  src/cascadia/TerminalConnection/ConhostConnection.cpp
  src/cascadia/TerminalConnection/ConhostConnection.h
  src/cascadia/TerminalConnection/ConptyConnection.cpp
  src/cascadia/TerminalConnection/ConptyConnection.h
  src/host/CursorBlinker.cpp
  src/host/PtySignalInputThread.cpp
  src/host/PtySignalInputThread.hpp
  src/host/VtInputThread.cpp
  src/host/VtInputThread.hpp
  src/host/srvinit.cpp
  src/interactivity/onecore/ConsoleInputThread.cpp
  src/interactivity/win32/ConsoleInputThread.cpp
  src/interactivity/win32/find.cpp
  src/interactivity/win32/windowio.cpp
  src/interactivity/win32/windowio.hpp
  src/propsheet/ColorControl.cpp
  src/propsheet/ColorControl.h
  src/propsheet/ColorsPage.cpp
  src/propsheet/ColorsPage.h
  src/propsheet/console.cpp
  src/propsheet/console.h
  src/propsheet/fontdlg.cpp
  src/propsheet/misc.cpp
  src/propsheet/preview.cpp
  src/tools/echokey/main.cpp
  src/tools/fontlist/main.cpp
  src/tools/vtpipeterm/VtConsole.cpp
  src/tools/vtpipeterm/VtConsole.hpp
  src/tools/vtpipeterm/main.cpp
Labels: Area-Build, AutoMerge, Issue-Bug, Product-Conhost

#843 Fix #453: Setting historySize=32767 causes WindowsTerminal to hang
  src/cascadia/TerminalControl/TermControl.cpp
  src/cascadia/TerminalCore/Terminal.cpp
  src/cascadia/UnitTests_TerminalCore/ScreenSizeLimitsTest.cpp
  src/cascadia/UnitTests_TerminalCore/UnitTests.vcxproj
  src/inc/LibraryIncludes.h
  tools/runut.cmd
Labels: AutoMerge

#285 Add GUIConsole sample
  samples/ConPTY/GUIConsole/GUIConsole.ConPTY/GUIConsole.ConPTY.csproj
  samples/ConPTY/GUIConsole/GUIConsole.ConPTY/Native/ConsoleApi.cs
  samples/ConPTY/GUIConsole/GUIConsole.ConPTY/Native/ProcessApi.cs
  samples/ConPTY/GUIConsole/GUIConsole.ConPTY/Native/PseudoConsoleApi.cs
  samples/ConPTY/GUIConsole/GUIConsole.ConPTY/Processes/Process.cs
  samples/ConPTY/GUIConsole/GUIConsole.ConPTY/Processes/ProcessFactory.cs
  samples/ConPTY/GUIConsole/GUIConsole.ConPTY/PseudoConsole.cs
  samples/ConPTY/GUIConsole/GUIConsole.ConPTY/PseudoConsolePipe.cs
  samples/ConPTY/GUIConsole/GUIConsole.ConPTY/Terminal.cs
  samples/ConPTY/GUIConsole/GUIConsole.WPF/App.config
  samples/ConPTY/GUIConsole/GUIConsole.WPF/App.xaml
  samples/ConPTY/GUIConsole/GUIConsole.WPF/App.xaml.cs
  samples/ConPTY/GUIConsole/GUIConsole.WPF/GUIConsole.WPF.csproj
  samples/ConPTY/GUIConsole/GUIConsole.WPF/MainWindow.xaml
  samples/ConPTY/GUIConsole/GUIConsole.WPF/MainWindow.xaml.cs
  samples/ConPTY/GUIConsole/GUIConsole.WPF/Properties/AssemblyInfo.cs
  samples/ConPTY/GUIConsole/GUIConsole.WPF/Properties/Resources.Designer.cs
  samples/ConPTY/GUIConsole/GUIConsole.WPF/Properties/Resources.resx
  samples/ConPTY/GUIConsole/GUIConsole.WPF/Properties/Settings.Designer.cs
  samples/ConPTY/GUIConsole/GUIConsole.WPF/Properties/Settings.settings
  samples/ConPTY/GUIConsole/GUIConsole.sln
  samples/ConPTY/GUIConsole/README.md
Labels: AutoMerge, Issue-Samples, Needs-Attention, Product-Conpty

#884 Create Bot.md
  doc/bot.md
Labels: AutoMerge

#829 Simplify DPI logic
  src/cascadia/WindowsTerminal/BaseWindow.h
  src/cascadia/WindowsTerminal/IslandWindow.cpp
  src/cascadia/WindowsTerminal/IslandWindow.h
  src/cascadia/WindowsTerminal/NonClientIslandWindow.cpp
Labels: AutoMerge

#710 Added requestedTheme option into terminal settings
  src/cascadia/TerminalApp/GlobalAppSettings.cpp
  src/cascadia/TerminalApp/GlobalAppSettings.h
Labels: AutoMerge

#907 Add behavior of .vsconfig to README
  README.md
Labels: AutoMerge, Issue-Docs

#911 Fix `it's` versus `its` typo.
  src/buffer/out/TextAttribute.cpp
  src/buffer/out/UnicodeStorage.cpp
  src/cascadia/TerminalApp/CascadiaSettingsSerialization.cpp
  src/cascadia/TerminalApp/GlobalAppSettings.cpp
  src/cascadia/TerminalApp/Profile.cpp
  src/cascadia/TerminalApp/Tab.cpp
  src/cascadia/TerminalConnection/ConhostConnection.cpp
  src/cascadia/TerminalControl/TermControl.cpp
  src/cascadia/WindowsTerminal/IslandWindow.cpp
  src/cppwinrt.build.post.props
  src/host/ConsoleArguments.cpp
  src/host/VtIo.cpp
  src/host/screenInfo.cpp
  src/host/settings.cpp
  src/host/srvinit.cpp
  src/interactivity/win32/windowio.cpp
  src/renderer/base/renderer.cpp
  src/renderer/dx/DxRenderer.cpp
  src/renderer/inc/RenderEngineBase.hpp
  src/renderer/vt/XtermEngine.cpp
  src/terminal/adapter/MouseInput.cpp
  src/terminal/adapter/adaptDispatch.cpp
  src/terminal/adapter/ut_adapter/adapterTest.cpp
  src/terminal/parser/InputStateMachineEngine.cpp
  src/terminal/parser/OutputStateMachineEngine.cpp
  src/tools/vtpipeterm/VtConsole.cpp
Labels: AutoMerge

#748 Support remapping keybindings
  src/cascadia/TerminalApp/App.cpp
  src/cascadia/TerminalApp/AppKeyBindings.cpp
  src/cascadia/TerminalApp/AppKeyBindings.h
  src/cascadia/TerminalApp/AppKeyBindings.idl
  src/cascadia/TerminalApp/CascadiaSettingsSerialization.cpp
  src/cascadia/TerminalApp/GlobalAppSettings.cpp
  src/cascadia/TerminalApp/GlobalAppSettings.h
  src/cascadia/TerminalApp/KeyChordSerialization.cpp
  src/cascadia/TerminalApp/KeyChordSerialization.h
  src/cascadia/TerminalApp/TerminalApp.vcxproj
Labels: Area-Settings, Issue-Feature

#741 make copying of files windows localization agnostic
  tools/echokey.cmd
  tools/opencas.cmd
  tools/opencon.cmd
  tools/openterm.cmd
  tools/openvt.cmd
Labels: Area-Build, AutoMerge

#719 Remove ATL dependencies (#676)
  src/inc/LibraryIncludes.h
  src/terminal/parser/ft_fuzzer/VTCommandFuzzer.cpp
  src/terminal/parser/ft_fuzzer/VTCommandFuzzer.vcxproj
  src/terminal/parser/ft_fuzzer/VTCommandFuzzer.vcxproj.filters
  src/terminal/parser/ft_fuzzer/fuzzing_directed.h
  src/terminal/parser/ft_fuzzer/fuzzing_logic.h
  src/terminal/parser/ft_fuzzer/memallocator.h
  src/terminal/parser/ft_fuzzer/stdafx.h
  src/terminal/parser/ft_fuzzer/string_helper.h
  src/tsf/ConsoleTSF.cpp
  src/tsf/ConsoleTSF.h
  src/tsf/StructureArray.h
  src/tsf/TfCatUtil.cpp
  src/tsf/TfCatUtil.h
  src/tsf/TfConvArea.cpp
  src/tsf/TfConvArea.h
  src/tsf/TfCtxtComp.h
  src/tsf/TfDispAttr.cpp
  src/tsf/TfDispAttr.h
  src/tsf/TfEditses.cpp
  src/tsf/TfEditses.h
  src/tsf/TfTxtevCb.cpp
  src/tsf/precomp.h
  src/tsf/tsf.vcxproj
  src/tsf/tsf.vcxproj.filters
Labels: AutoMerge

#913 Switch to v5 UUIDs as profile GUIDs for the default profiles
  OpenConsole.sln
  src/cascadia/TerminalApp/CascadiaSettings.cpp
  src/cascadia/TerminalApp/CascadiaSettings.h
  src/cascadia/TerminalApp/Profile.cpp
  src/cascadia/TerminalApp/Profile.h
  src/common.build.exe.or.dll.props
  src/testlist/Microsoft.Console.Tests.testlist
  src/types/dirs
  src/types/inc/utils.hpp
  src/types/precomp.h
  src/types/ut_types/DefaultResource.rc
  src/types/ut_types/Types.Unit.Tests.vcxproj
  src/types/ut_types/UuidTests.cpp
  src/types/ut_types/product.pbxproj
  src/types/ut_types/sources
  src/types/utils.cpp
  tools/OpenConsole.psm1
  tools/runut.cmd
  tools/tests.xml
Labels: Area-Settings, Issue-Task, Product-Terminal

#899 Update README.md - Build the Code section
  README.md
Labels: AutoMerge, Issue-Docs

#931 Re-enable ARM64 in CI
  build/pipelines/ci.yml
Labels: Area-Build

#767 Closing the tab shifts focus to the right
  src/cascadia/TerminalApp/App.cpp
Labels: Area-User Interface

#836 Utf8ToWideCharParser: Fix memory leak in case of error
  src/host/utf8ToWideCharParser.cpp
Labels: Issue-Bug, Product-Conhost

#941 Added support for DECSCUSR sequences
  src/cascadia/TerminalControl/TermControl.cpp
  src/cascadia/TerminalCore/ITerminalApi.hpp
  src/cascadia/TerminalCore/Terminal.cpp
  src/cascadia/TerminalCore/Terminal.hpp
  src/cascadia/TerminalCore/TerminalApi.cpp
  src/cascadia/TerminalCore/TerminalDispatch.cpp
  src/cascadia/TerminalCore/TerminalDispatch.hpp
Labels: Area-VT, Issue-Bug, Product-Terminal

#954 Remove ATL from .vsconfig!
  .vsconfig
Labels: Area-Build, AutoMerge, Product-Meta

#903 Add an error dialog when we fail to parse settings
  src/cascadia/CascadiaPackage/Resources/en-US/Resources.resw
  src/cascadia/TerminalApp/App.cpp
  src/cascadia/TerminalApp/App.h
  src/cascadia/TerminalApp/App.xaml
  src/cascadia/TerminalApp/CascadiaSettings.cpp
  src/cascadia/TerminalApp/CascadiaSettings.h
  src/cascadia/TerminalApp/CascadiaSettingsSerialization.cpp
  src/cascadia/WindowsTerminal/IslandWindow.cpp
Labels: Area-User Interface, Issue-Task, Product-Terminal

#918 Update the default settings
  src/cascadia/TerminalApp/CascadiaSettings.cpp
  src/cascadia/TerminalApp/CascadiaSettings.h
  src/cascadia/TerminalApp/GlobalAppSettings.cpp
  src/inc/DefaultSettings.h
Labels: Area-Settings, Issue-Bug, Product-Terminal

#585 add .editorconfig file
  .editorconfig
Labels: AutoMerge

#1008 Update manifest to correct 1903 version, unref param fix
  src/cascadia/WindowsTerminal/IslandWindow.cpp
  src/cascadia/WindowsTerminal/WindowsTerminal.manifest
Labels: Area-CodeHealth, Issue-Task, Product-Terminal

#1009 fix build break from using `await` instead of `co_await`
  src/cascadia/TerminalApp/App.cpp
Labels: AutoMerge

#948 add audit mode to ci
  .gitignore
  build/pipelines/ci.yml
  build/pipelines/release.yml
  build/pipelines/templates/build-console-audit-job.yml
  build/pipelines/templates/build-console-ci.yml
  build/pipelines/templates/build-console-int.yml
  build/pipelines/templates/release-sign-and-bundle.yml
  src/StaticAnalysis.ruleset
  src/buffer/out/precomp.h
  src/cascadia/TerminalApp/App.h
  src/cascadia/TerminalApp/CascadiaSettingsSerialization.cpp
  src/cascadia/TerminalConnection/pch.h
  src/common.build.post.props
  src/common.build.pre.props
  src/inc/LibraryIncludes.h
  src/propsheet/precomp.h
Labels: Area-Build, Product-Meta

#1034 Fix Typo In Terminal.cpp Comment
  src/cascadia/TerminalCore/Terminal.cpp
Labels: AutoMerge

#1015 Fix #936: misuse of uninitialized objects causes AppVerifier breaks on Windows Terminal startup
  src/cascadia/TerminalControl/TermControl.cpp
  src/renderer/base/thread.cpp
Labels: AutoMerge

#1044 Guard try_query calls with a null check on the pointer we're QI-ing...
  src/tsf/ConsoleTSF.cpp
  src/tsf/ConsoleTSF.h
Labels: Area-Input, Issue-Bug, Product-Conhost, Severity-Crash

#1063 Use a ComPtr to avoid leaking font.
  src/renderer/dx/CustomTextLayout.cpp
Labels: Area-Rendering, AutoMerge

#953 Apply [[nodiscard]] to functions returning error codes
  src/cascadia/WindowsTerminal/BaseWindow.h
  src/cascadia/WindowsTerminal/IslandWindow.cpp
  src/cascadia/WindowsTerminal/IslandWindow.h
  src/cascadia/WindowsTerminal/NonClientIslandWindow.cpp
  src/cascadia/WindowsTerminal/NonClientIslandWindow.h
  src/host/ConsoleArguments.hpp
  src/host/VtIo.cpp
  src/host/VtIo.hpp
  src/host/cmdline.h
  src/host/popup.cpp
  src/host/popup.h
  src/inc/test/CommonState.hpp
  src/interactivity/inc/IConsoleControl.hpp
  src/interactivity/win32/window.cpp
  src/interactivity/win32/window.hpp
  src/interactivity/win32/windowproc.cpp
  src/propsheet/ColorControl.cpp
  src/propsheet/ColorControl.h
  src/propsheet/ColorsPage.cpp
  src/propsheet/ColorsPage.h
  src/propsheet/console.cpp
  src/propsheet/console.h
  src/propsheet/dbcs.cpp
  src/propsheet/font.h
  src/propsheet/fontdlg.cpp
  src/propsheet/misc.cpp
  src/propsheet/preview.cpp
  src/propsheet/util.cpp
  src/server/IoDispatchers.cpp
  src/terminal/parser/ft_fuzzer/fuzzing_directed.h
Labels: Area-CodeHealth, AutoMerge

#888 Highlight the default profile in new-tab flyout
  src/cascadia/TerminalApp/App.cpp
  src/cascadia/TerminalApp/pch.h
Labels: Area-User Interface, Issue-Task, Product-Terminal
