Repository microsoft/terminal, pull requests merged in 2020-01, with the labels that each got.

#4083 Replace bitwise flipping with WI_ flag helpers
  src/terminal/adapter/adaptDispatchGraphics.cpp
Labels: AutoMerge, Needs-Second

#4022 Fix a crash when dragging a debug conhost across a DPI boundary
  src/interactivity/win32/windowproc.cpp
Labels: AutoMerge, Needs-Second, Product-Conhost, Severity-Crash

#4005 Apply audit mode to TerminalInput/Adapter/Parser libraries
  OpenConsole.sln
  src/cascadia/TerminalCore/TerminalDispatch.cpp
  src/cascadia/TerminalCore/TerminalDispatch.hpp
  src/cascadia/TerminalCore/TerminalDispatchGraphics.cpp
  src/inc/ITerminalOutputConnection.hpp
  src/inc/LibraryIncludes.h
  src/inc/til.h
  src/terminal/adapter/DispatchCommon.cpp
  src/terminal/adapter/IInteractDispatch.hpp
  src/terminal/adapter/ITermDispatch.hpp
  src/terminal/adapter/InteractDispatch.cpp
  src/terminal/adapter/InteractDispatch.hpp
  src/terminal/adapter/MouseInput.cpp
  src/terminal/adapter/MouseInput.hpp
  src/terminal/adapter/adaptDispatch.cpp
  src/terminal/adapter/adaptDispatch.hpp
  src/terminal/adapter/adaptDispatchGraphics.cpp
  src/terminal/adapter/lib/adapter.vcxproj
  src/terminal/adapter/lib/adapter.vcxproj.filters
  src/terminal/adapter/termDispatch.hpp
  src/terminal/adapter/terminalOutput.cpp
  src/terminal/adapter/terminalOutput.hpp
  src/terminal/input/terminalInput.cpp
  src/terminal/input/terminalInput.hpp
  src/terminal/parser/InputStateMachineEngine.cpp
  src/terminal/parser/InputStateMachineEngine.hpp
  src/terminal/parser/OutputStateMachineEngine.cpp
  src/terminal/parser/OutputStateMachineEngine.hpp
  src/terminal/parser/stateMachine.cpp
  src/terminal/parser/stateMachine.hpp
  src/terminal/parser/telemetry.cpp
  src/terminal/parser/telemetry.hpp
  src/terminal/parser/tracing.cpp
  src/terminal/parser/tracing.hpp
  src/terminal/parser/ut_parser/OutputEngineTest.cpp
  src/types/inc/utils.hpp
Labels: Area-CodeHealth, AutoMerge, Issue-Task, Product-Conhost

#4016 Apply audit mode to TerminalConnection/Core/Settings and WinConPTY libraries
  OpenConsole.sln
  src/buffer/out/textBuffer.cpp
  src/buffer/out/textBuffer.hpp
  src/cascadia/TerminalConnection/AzureClientID.h
  src/cascadia/TerminalConnection/AzureConnection.cpp
  src/cascadia/TerminalConnection/AzureConnection.h
  src/cascadia/TerminalConnection/ConnectionStateHolder.h
  src/cascadia/TerminalConnection/ConptyConnection.cpp
  src/cascadia/TerminalConnection/ConptyConnection.h
  src/cascadia/TerminalConnection/EchoConnection.cpp
  src/cascadia/TerminalConnection/EchoConnection.h
  src/cascadia/TerminalConnection/TelnetConnection.cpp
  src/cascadia/TerminalConnection/init.cpp
  src/cascadia/TerminalCore/ITerminalApi.hpp
  src/cascadia/TerminalCore/Terminal.cpp
  src/cascadia/TerminalCore/Terminal.hpp
  src/cascadia/TerminalCore/TerminalApi.cpp
  src/cascadia/TerminalCore/TerminalDispatch.cpp
  src/cascadia/TerminalCore/TerminalDispatch.hpp
  src/cascadia/TerminalCore/TerminalDispatchGraphics.cpp
  src/cascadia/TerminalCore/TerminalSelection.cpp
  src/cascadia/TerminalCore/lib/terminalcore-lib.vcxproj
  src/cascadia/TerminalCore/terminalrenderdata.cpp
  src/cascadia/TerminalSettings/KeyChord.cpp
  src/cascadia/TerminalSettings/KeyChord.h
  src/cascadia/TerminalSettings/TerminalSettings.cpp
  src/cascadia/TerminalSettings/terminalsettings.h
  src/cascadia/WinRTUtils/inc/LibraryResources.h
  src/cascadia/inc/cppwinrt_utils.h
  src/common.build.pre.props
  src/server/DeviceHandle.cpp
  src/server/WinNTControl.cpp
  src/server/WinNTControl.h
  src/terminal/adapter/adaptDispatchGraphics.cpp
  src/terminal/parser/OutputStateMachineEngine.cpp
  src/terminal/parser/stateMachine.cpp
  src/winconpty/winconpty.cpp
Labels: Area-CodeHealth, Issue-Task, Product-Conpty, Product-Terminal

#3575 Terminal uses system default for number of rows scrolled at a time. Can be overridden in settings file.
  doc/cascadia/SettingsSchema.md
  doc/cascadia/profiles.schema.json
  src/cascadia/LocalTests_TerminalApp/SettingsTests.cpp
  src/cascadia/TerminalApp/GlobalAppSettings.cpp
  src/cascadia/TerminalApp/GlobalAppSettings.h
  src/cascadia/TerminalControl/TermControl.cpp
  src/cascadia/TerminalControl/TermControl.h
  src/cascadia/TerminalSettings/ICoreSettings.idl
  src/cascadia/TerminalSettings/TerminalSettings.cpp
  src/cascadia/TerminalSettings/terminalsettings.h
  src/cascadia/UnitTests_TerminalCore/MockTermSettings.h
  src/inc/DefaultSettings.h
Labels: Area-Settings, Needs-Second, Product-Terminal

#4113 Fix flipped sense in TerminalDispatch::CursorPosition
  src/cascadia/TerminalCore/TerminalDispatch.cpp
Labels: Needs-Second

#2654 add a spec for initial position and launch mode
  doc/specs/#1043 - Set the initial position of the Terminal/spec.md
Labels: Issue-Docs, Needs-Second, Product-Terminal

#4128 Correct improper usage of THROW_IF_NULL_ALLOC
  src/host/PtySignalInputThread.cpp
  src/host/screenInfo.cpp
  src/interactivity/win32/Clipboard.cpp
  src/renderer/base/renderer.cpp
  src/renderer/dx/DxRenderer.cpp
  src/terminal/adapter/InteractDispatch.cpp
  src/terminal/adapter/adaptDispatch.cpp
  src/terminal/parser/InputStateMachineEngine.cpp
  src/terminal/parser/OutputStateMachineEngine.cpp
  src/tools/vtpipeterm/VtConsole.cpp
Labels: Area-CodeHealth, Needs-Second, Product-Conhost

#4143 Fix a test that regressed during #3575
  src/cascadia/LocalTests_TerminalApp/SettingsTests.cpp
Labels: Area-CodeHealth, AutoMerge, Product-Terminal

#4140 Fix IME/CoreTextEditContext not being reset properly
  src/cascadia/TerminalControl/TSFInputControl.cpp
Labels: Area-Input, Area-TerminalControl, AutoMerge, Product-Terminal

#4125 Correct passthrough sequences after refactor
  src/terminal/parser/stateMachine.cpp
  src/terminal/parser/ut_parser/StateMachineTest.cpp
Labels: Area-VT, AutoMerge, Product-Conhost

#3181 Snap to character grid when resizing window
  src/cascadia/TerminalApp/AppLogic.cpp
  src/cascadia/TerminalApp/AppLogic.h
  src/cascadia/TerminalApp/AppLogic.idl
  src/cascadia/TerminalApp/Pane.LayoutSizeNode.cpp
  src/cascadia/TerminalApp/Pane.cpp
  src/cascadia/TerminalApp/Pane.h
  src/cascadia/TerminalApp/Tab.cpp
  src/cascadia/TerminalApp/Tab.h
  src/cascadia/TerminalApp/TerminalPage.cpp
  src/cascadia/TerminalApp/TerminalPage.h
  src/cascadia/TerminalApp/lib/TerminalAppLib.vcxproj
  src/cascadia/TerminalApp/lib/TerminalAppLib.vcxproj.filters
  src/cascadia/TerminalControl/TermControl.cpp
  src/cascadia/TerminalControl/TermControl.h
  src/cascadia/TerminalControl/TermControl.idl
  src/cascadia/WindowsTerminal/AppHost.cpp
  src/cascadia/WindowsTerminal/IslandWindow.cpp
  src/cascadia/WindowsTerminal/IslandWindow.h
  src/cascadia/WindowsTerminal/NonClientIslandWindow.cpp
  src/cascadia/WindowsTerminal/NonClientIslandWindow.h
Labels: Area-User Interface, Needs-Second, Product-Terminal

#4123 Introduce til::some
  OpenConsole.sln
  src/dirs
  src/inc/til.h
  src/inc/til/some.h
  src/til/dirs
  src/til/precomp.cpp
  src/til/precomp.h
  src/til/ut_til/DefaultResource.rc
  src/til/ut_til/SomeTests.cpp
  src/til/ut_til/product.pbxproj
  src/til/ut_til/sources
  src/til/ut_til/til.unit.tests.vcxproj
  tools/OpenConsole.psm1
  tools/runut.cmd
  tools/tests.xml
Labels: Area-CodeHealth, Product-Meta

#4154 Add a setting to disable pane snapping
  doc/cascadia/SettingsSchema.md
  doc/cascadia/profiles.schema.json
  src/cascadia/TerminalApp/GlobalAppSettings.cpp
  src/cascadia/TerminalApp/GlobalAppSettings.h
  src/cascadia/TerminalApp/TerminalPage.cpp
  src/cascadia/TerminalApp/defaults.json
Labels: Area-Settings, Area-User Interface, AutoMerge, Product-Terminal

#4158 wsl: actually close the pipe handle for wsl.exe, but only once
  src/cascadia/TerminalApp/WslDistroGenerator.cpp
Labels: Needs-Second, Product-Terminal

#4157 Add WT_SESSION to WSLENV so it propagates into WSL
  src/cascadia/TerminalConnection/ConptyConnection.cpp
Labels: Area-TerminalConnection, AutoMerge, Needs-Second, Product-Terminal

#4156 Don't generate WSL distributions for docker-desktop*
  src/cascadia/TerminalApp/WslDistroGenerator.cpp
Labels: Area-Settings, AutoMerge, Product-Terminal

#3876 Add tab width modes: equal and titleLength
  doc/cascadia/SettingsSchema.md
  doc/cascadia/profiles.schema.json
  src/cascadia/TerminalApp/GlobalAppSettings.cpp
  src/cascadia/TerminalApp/GlobalAppSettings.h
  src/cascadia/TerminalApp/TabRowControl.xaml
  src/cascadia/TerminalApp/TerminalPage.cpp
  src/cascadia/TerminalApp/TerminalPage.h
  src/cascadia/TerminalApp/defaults.json
Labels: Area-Settings, Area-User Interface, Product-Terminal

#4163 doc: Add debugging notes on DebugBreak
  doc/Debugging.md
Labels: Issue-Docs, Needs-Second, Product-Meta

#4051 Converts Dispatcher().RunAsync to WinRT Coroutines
  doc/STYLE.md
  src/cascadia/TerminalApp/AppLogic.cpp
  src/cascadia/TerminalApp/AppLogic.h
  src/cascadia/TerminalApp/Pane.cpp
  src/cascadia/TerminalApp/Pane.h
  src/cascadia/TerminalApp/Tab.cpp
  src/cascadia/TerminalApp/Tab.h
  src/cascadia/TerminalApp/TerminalPage.cpp
  src/cascadia/TerminalApp/TerminalPage.h
  src/cascadia/TerminalControl/TermControl.cpp
  src/cascadia/TerminalControl/TermControl.h
Labels: Area-CodeHealth, AutoMerge, Needs-Second, Product-Terminal

#4173 Remove global namespaced min/max and replace it with STL min/max
  src/host/ft_host/API_BufferTests.cpp
  src/host/ft_host/API_DimensionsTests.cpp
  src/host/ft_host/API_OutputTests.cpp
  src/host/ft_host/API_TitleTests.cpp
  src/host/ft_host/CJK_DbcsTests.cpp
  src/host/ft_host/precomp.h
  src/propsheet/console.cpp
  src/propsheet/fontdlg.cpp
  src/propsheet/precomp.h
  src/propsheet/preview.cpp
Labels: Area-CodeHealth, AutoMerge, Needs-Author-Feedback

#4105 Fix unittesting our `.xaml` classes
  OpenConsole.sln
  src/cascadia/LocalTests_TerminalApp/ColorSchemeTests.cpp
  src/cascadia/LocalTests_TerminalApp/KeyBindingsTests.cpp
  src/cascadia/LocalTests_TerminalApp/ProfileTests.cpp
  src/cascadia/LocalTests_TerminalApp/SettingsTests.cpp
  src/cascadia/LocalTests_TerminalApp/TabTests.cpp
  src/cascadia/LocalTests_TerminalApp/TerminalApp.LocalTests.vcxproj
  src/cascadia/LocalTests_TerminalApp/TestHostApp/Package.appxmanifest
  src/cascadia/LocalTests_TerminalApp/TestHostApp/TestHostApp.vcxproj
  src/cascadia/LocalTests_TerminalApp/TestHostApp/UnitTestApp.xaml
  src/cascadia/LocalTests_TerminalApp/TestHostApp/UnitTestApp.xaml.cpp
  src/cascadia/LocalTests_TerminalApp/TestHostApp/UnitTestApp.xaml.h
  src/cascadia/LocalTests_TerminalApp/TestHostApp/pch.cpp
  src/cascadia/LocalTests_TerminalApp/TestHostApp/pch.h
  src/cascadia/LocalTests_TerminalApp/pch.h
  src/cascadia/TerminalApp/CascadiaSettings.h
  src/cascadia/TerminalApp/TerminalPage.h
  src/common.build.tests.props
  src/host/ft_uia/Host.Tests.UIA.csproj
  src/host/ft_uia/packages.config
  src/terminal/parser/ut_parser/packages.config
  tools/OpenConsole.psm1
  tools/razzle.cmd
  tools/runut.cmd
  tools/tests.xml
Labels: Area-CodeHealth, AutoMerge, Product-Terminal

#4172 when spawning a pty, be sure to provide & escape conhost's path
  src/winconpty/winconpty.cpp
Labels: Product-Conpty

#3935 Add Ctrl+Backspace support
  src/terminal/parser/InputStateMachineEngine.cpp
  src/terminal/parser/ut_parser/InputEngineTest.cpp
Labels: Area-Input, Area-TerminalControl, AutoMerge, Needs-Second, Product-Terminal

#4202 Guard the substring calls in StateMachine parser to avoid bounds issues
  src/terminal/parser/stateMachine.cpp
Labels: AutoMerge

#4209 Correct the behaviour of the IS_GLYPH_CHAR macro
  src/host/_stream.cpp
Labels: AutoMerge, Needs-Second

#4190 Fix redundant CR in formatted text copy
  src/buffer/out/textBuffer.cpp
Labels: AutoMerge

#4197 Move reflowing the buffer to `TextBuffer`
  src/buffer/out/textBuffer.cpp
  src/buffer/out/textBuffer.hpp
  src/host/screenInfo.cpp
Labels: Area-Output, AutoMerge, Product-Conhost

#4150 Fixed a deadlock when printing surrogate pairs
  src/cascadia/TerminalCore/Terminal.cpp
  src/cascadia/UnitTests_TerminalCore/TerminalApiTest.cpp
Labels: Area-Output, Area-TerminalControl, AutoMerge, Product-Terminal

#3271 Add support for all the line feed control sequences
  src/cascadia/TerminalCore/TerminalDispatch.cpp
  src/cascadia/TerminalCore/TerminalDispatch.hpp
  src/host/getset.cpp
  src/host/getset.h
  src/host/outputStream.cpp
  src/host/outputStream.hpp
  src/host/ut_host/ScreenBufferTests.cpp
  src/terminal/adapter/DispatchTypes.hpp
  src/terminal/adapter/ITermDispatch.hpp
  src/terminal/adapter/adaptDispatch.cpp
  src/terminal/adapter/adaptDispatch.hpp
  src/terminal/adapter/conGetSet.hpp
  src/terminal/adapter/termDispatch.hpp
  src/terminal/adapter/ut_adapter/adapterTest.cpp
  src/terminal/parser/OutputStateMachineEngine.cpp
  src/terminal/parser/OutputStateMachineEngine.hpp
  src/terminal/parser/telemetry.cpp
  src/terminal/parser/telemetry.hpp
  src/terminal/parser/ut_parser/OutputEngineTest.cpp
Labels: Area-VT, AutoMerge, Needs-Second, Product-Conhost

#3495 Add spec for adding commandline arguments to `wt.exe`
  doc/specs/#607 - Commandline Arguments for the Windows Terminal.md
Labels: Issue-Docs, Product-Terminal

#4144 Introduce chromium safe math
  NOTICE.md
  dep/chromium/LICENSE
  dep/chromium/MAINTAINER_README.md
  dep/chromium/base/numerics/BUILD.gn
  dep/chromium/base/numerics/DEPS
  dep/chromium/base/numerics/OWNERS
  dep/chromium/base/numerics/README.md
  dep/chromium/base/numerics/checked_math.h
  dep/chromium/base/numerics/checked_math_impl.h
  dep/chromium/base/numerics/clamped_math.h
  dep/chromium/base/numerics/clamped_math_impl.h
  dep/chromium/base/numerics/math_constants.h
  dep/chromium/base/numerics/ranges.h
  dep/chromium/base/numerics/safe_conversions.h
  dep/chromium/base/numerics/safe_conversions_arm_impl.h
  dep/chromium/base/numerics/safe_conversions_impl.h
  dep/chromium/base/numerics/safe_math.h
  dep/chromium/base/numerics/safe_math_arm_impl.h
  dep/chromium/base/numerics/safe_math_clang_gcc_impl.h
  dep/chromium/base/numerics/safe_math_shared_impl.h
  dep/chromium/cgmanifest.json
  src/cascadia/WindowsTerminalUniversal/WindowsTerminalUniversal.vcxproj
  src/cascadia/WindowsTerminalUniversal/pch.h
  src/common.build.pre.props
  src/inc/LibraryIncludes.h
  src/propslib/precomp.h
  src/server/precomp.h
  src/terminal/parser/ft_fuzzer/stdafx.h
  src/terminal/parser/ft_fuzzwrapper/precomp.h
  src/tsf/precomp.h
Labels: Area-CodeHealth, AutoMerge, Issue-Task, Product-Conhost, Product-Conpty, Product-Meta, Product-Terminal

#3628 Improve the VT cursor movement implementation
  src/host/getset.cpp
  src/host/getset.h
  src/host/outputStream.cpp
  src/host/outputStream.hpp
  src/host/ut_host/ScreenBufferTests.cpp
  src/terminal/adapter/adaptDispatch.cpp
  src/terminal/adapter/adaptDispatch.hpp
  src/terminal/adapter/conGetSet.hpp
  src/terminal/adapter/ut_adapter/adapterTest.cpp
Labels: Area-VT, AutoMerge, Product-Conhost

#4213 Create tests that roundtrip output through a conpty to a Terminal
  src/cascadia/TerminalCore/Terminal.hpp
  src/cascadia/UnitTests_TerminalCore/ConptyRoundtripTests.cpp
  src/cascadia/UnitTests_TerminalCore/UnitTests.vcxproj
  src/cascadia/UnitTests_TerminalCore/precomp.h
  src/host/screenInfo.hpp
  src/host/ut_host/ConptyOutputTests.cpp
  src/host/ut_host/Host.UnitTests.vcxproj
  src/host/ut_host/TextBufferTests.cpp
  src/host/ut_host/sources
  src/inc/test/CommonState.hpp
  src/renderer/base/renderer.cpp
  src/renderer/base/renderer.hpp
  src/renderer/vt/Xterm256Engine.hpp
  src/renderer/vt/XtermEngine.hpp
  src/renderer/vt/state.cpp
  src/renderer/vt/vtrenderer.hpp
Labels: Area-CodeHealth, AutoMerge, Product-Conpty, Product-Terminal

#4174 Use til::some<T,N> to replace the SomeViewports class
  src/inc/til.h
  src/inc/til/at.h
  src/inc/til/some.h
  src/types/inc/viewport.hpp
  src/types/viewport.cpp
Labels: Area-CodeHealth, AutoMerge

#4081 Fix column count issues with certain ligature.
  src/renderer/dx/CustomTextLayout.cpp
Labels: Area-Rendering, AutoMerge, Needs-Second, Product-Terminal

#4297 Add support for the HPR and VPR escape sequences
  src/host/ut_host/ScreenBufferTests.cpp
  src/terminal/adapter/ITermDispatch.hpp
  src/terminal/adapter/adaptDispatch.cpp
  src/terminal/adapter/adaptDispatch.hpp
  src/terminal/adapter/termDispatch.hpp
  src/terminal/parser/OutputStateMachineEngine.cpp
  src/terminal/parser/OutputStateMachineEngine.hpp
  src/terminal/parser/telemetry.cpp
  src/terminal/parser/telemetry.hpp
  src/terminal/parser/ut_parser/OutputEngineTest.cpp
Labels: Area-VT, AutoMerge, Issue-Task, Needs-Second, Product-Conhost

#4319 Fix the `UnitTests_TerminalCore`'s dependency on `RendererGdi`
  OpenConsole.sln
  src/cascadia/UnitTests_TerminalCore/UnitTests.vcxproj
Labels: Area-Build, AutoMerge

#3817 Add support for the DECSCNM screen mode
  src/host/getset.cpp
  src/host/getset.h
  src/host/outputStream.cpp
  src/host/outputStream.hpp
  src/host/settings.cpp
  src/host/settings.hpp
  src/host/ut_host/ScreenBufferTests.cpp
  src/terminal/adapter/DispatchTypes.hpp
  src/terminal/adapter/ITermDispatch.hpp
  src/terminal/adapter/adaptDispatch.cpp
  src/terminal/adapter/adaptDispatch.hpp
  src/terminal/adapter/conGetSet.hpp
  src/terminal/adapter/termDispatch.hpp
  src/terminal/adapter/ut_adapter/adapterTest.cpp
  src/terminal/parser/ut_parser/OutputEngineTest.cpp
Labels: Area-VT, AutoMerge, Product-Conhost

#4337 Shut down all controls under a tab before we remove it from the list
  src/cascadia/TerminalApp/Pane.cpp
  src/cascadia/TerminalApp/Pane.h
  src/cascadia/TerminalApp/Tab.cpp
  src/cascadia/TerminalApp/Tab.h
  src/cascadia/TerminalApp/TerminalPage.cpp
  src/cascadia/TerminalControl/TSFInputControl.cpp
  src/cascadia/TerminalControl/TSFInputControl.h
  src/cascadia/TerminalControl/TSFInputControl.idl
  src/cascadia/TerminalControl/TermControl.cpp
Labels: AutoMerge, Severity-Blocking

#4342 Allow string values (like "system") in the `rowsToScroll` schema
  doc/cascadia/profiles.schema.json
Labels: Area-Schema, Issue-Docs, Needs-Second

#4023 Add support for commandline args to `wt.exe`
  dep/CLI11/CLI11.hpp
  dep/CLI11/README.md
  doc/user-docs/UsingCommandlineArguments.md
  src/cascadia/LocalTests_TerminalApp/CommandlineTest.cpp
  src/cascadia/LocalTests_TerminalApp/TerminalApp.LocalTests.vcxproj
  src/cascadia/LocalTests_TerminalApp/pch.h
  src/cascadia/TerminalApp/AppCommandlineArgs.cpp
  src/cascadia/TerminalApp/AppCommandlineArgs.h
  src/cascadia/TerminalApp/AppLogic.cpp
  src/cascadia/TerminalApp/AppLogic.h
  src/cascadia/TerminalApp/AppLogic.idl
  src/cascadia/TerminalApp/Commandline.cpp
  src/cascadia/TerminalApp/Commandline.h
  src/cascadia/TerminalApp/Tab.cpp
  src/cascadia/TerminalApp/TerminalPage.cpp
  src/cascadia/TerminalApp/TerminalPage.h
  src/cascadia/TerminalApp/TerminalPage.idl
  src/cascadia/TerminalApp/lib/TerminalAppLib.vcxproj
  src/cascadia/TerminalApp/lib/pch.h
  src/cascadia/TerminalControl/TermControl.cpp
  src/cascadia/TerminalControl/TermControl.h
  src/cascadia/TerminalControl/TermControl.idl
  src/cascadia/WindowsTerminal/AppHost.cpp
  src/cascadia/WindowsTerminal/AppHost.h
  src/cascadia/WindowsTerminal/WindowsTerminal.rc
  src/cascadia/WindowsTerminal/main.cpp
  src/cascadia/WindowsTerminal/pch.h
  src/cascadia/WindowsTerminal/resource.h
  src/inc/LibraryIncludes.h
  src/types/inc/User32Utils.hpp
Labels: Area-User Interface, AutoMerge, Product-Terminal

#4358 Remove unneeded c_str() conversions
  src/cascadia/PublicTerminalCore/HwndTerminal.cpp
  src/cascadia/TerminalApp/Profile.cpp
  src/cascadia/TerminalControl/TSFInputControl.cpp
  src/cascadia/TerminalControl/TermControl.cpp
  src/cascadia/TerminalCore/terminalrenderdata.cpp
  src/cascadia/UnitTests_TerminalCore/MockTermSettings.h
  src/cascadia/WindowsTerminal/AppHost.cpp
Labels: Area-CodeHealth, Needs-Second

#4382 Add just the test infrastructure bits from #4354
  src/cascadia/TerminalCore/Terminal.hpp
  src/cascadia/UnitTests_TerminalCore/ConptyRoundtripTests.cpp
  src/cascadia/UnitTests_TerminalCore/TerminalBufferTests.cpp
  src/cascadia/UnitTests_TerminalCore/TestUtils.h
  src/cascadia/UnitTests_TerminalCore/UnitTests.vcxproj
  src/host/ConsoleArguments.cpp
  src/host/ConsoleArguments.hpp
  src/host/VtIo.cpp
  src/host/VtIo.hpp
  src/host/globals.cpp
  src/host/globals.h
  src/host/screenInfo.hpp
  src/host/ut_host/ConptyOutputTests.cpp
  src/inc/test/CommonState.hpp
  src/renderer/vt/vtrenderer.hpp
Labels: Area-CodeHealth, AutoMerge, Product-Terminal

#4289 Remove unneeded VT-specific control character handling
  src/cascadia/TerminalCore/ITerminalApi.hpp
  src/cascadia/TerminalCore/Terminal.cpp
  src/cascadia/TerminalCore/Terminal.hpp
  src/cascadia/TerminalCore/TerminalApi.cpp
  src/cascadia/TerminalCore/TerminalDispatch.cpp
  src/host/_stream.cpp
  src/host/cmdline.h
  src/host/outputStream.cpp
  src/host/screenInfo.cpp
  src/host/screenInfo.hpp
Labels: AutoMerge

#4400 Add privacy policy to about dialog
  src/cascadia/TerminalApp/Resources/en-US/Resources.resw
  src/cascadia/TerminalApp/TerminalPage.cpp
Labels: AutoMerge

#4093 Implement til::u8u16 and til::u16u8 conversion functions
  OpenConsole.sln
  src/cascadia/TerminalConnection/ConptyConnection.cpp
  src/cascadia/TerminalConnection/ConptyConnection.h
  src/inc/til.h
  src/inc/til/u8u16convert.h
  src/til/ut_til/til.unit.tests.vcxproj
  src/til/ut_til/u8u16convertTests.cpp
  src/tools/U8U16Test/PropertySheet.props
  src/tools/U8U16Test/U8U16Test.cpp
  src/tools/U8U16Test/U8U16Test.hpp
  src/tools/U8U16Test/U8U16Test.vcxproj
  src/tools/U8U16Test/U8U16Test.vcxproj.filters
  src/tools/U8U16Test/_test.cmd
  src/tools/U8U16Test/en.txt
  src/tools/U8U16Test/fr.txt
  src/tools/U8U16Test/main.cpp
  src/tools/U8U16Test/packages.config
  src/tools/U8U16Test/ru.txt
  src/tools/U8U16Test/zh.txt
  src/types/UTF8OutPipeReader.cpp
  src/types/lib/types.vcxproj
  src/types/lib/types.vcxproj.filters
  src/types/ut_types/Types.Unit.Tests.vcxproj
  src/types/ut_types/UTF8OutPipeReaderTests.cpp
Labels: Area-Output, Product-Meta

#4323 Add support for dragging and dropping paths onto the Terminal
  src/cascadia/TerminalControl/Resources/en-US/Resources.resw
  src/cascadia/TerminalControl/TermControl.cpp
  src/cascadia/TerminalControl/TermControl.h
  src/cascadia/TerminalControl/pch.h
Labels: Area-User Interface, AutoMerge, Product-Terminal

#4372 A pair of fixes related to cursor movement in conpty
  src/host/getset.cpp
  src/host/output.cpp
  src/host/ut_host/ScreenBufferTests.cpp
Labels: AutoMerge, Needs-Second

#4406 Fix the search box in High Contrast by using the right theme resources
  src/cascadia/TerminalControl/SearchBoxControl.xaml
Labels: AutoMerge

#4101 No more are you sure boxes
  doc/cascadia/SettingsSchema.md
  doc/cascadia/profiles.schema.json
  src/cascadia/TerminalApp/GlobalAppSettings.cpp
  src/cascadia/TerminalApp/GlobalAppSettings.h
  src/cascadia/TerminalApp/TerminalPage.cpp
  src/cascadia/TerminalApp/defaults.json
Labels: Area-Settings, AutoMerge, Product-Terminal

#4402 Kill NEEDS_LOC and move cmdline descriptions into resources
  src/cascadia/TerminalApp/AppCommandlineArgs.cpp
  src/cascadia/TerminalApp/Resources/en-US/Resources.resw
  src/cascadia/TerminalApp/lib/pch.h
  src/cascadia/WinRTUtils/inc/LibraryResources.h
Labels: AutoMerge

#4404 selection: Shift-Click to set endpoint, clear & discard keypress on ESC
  src/cascadia/TerminalControl/TermControl.cpp
Labels: Area-TerminalControl, AutoMerge, Product-Terminal

#4273 Collect all known PowerShell Core installations for dynamic profiles
  src/cascadia/CascadiaPackage/ProfileIcons/pwsh-preview.scale-100.png
  src/cascadia/CascadiaPackage/ProfileIcons/pwsh-preview.scale-125.png
  src/cascadia/CascadiaPackage/ProfileIcons/pwsh-preview.scale-150.png
  src/cascadia/CascadiaPackage/ProfileIcons/pwsh-preview.scale-200.png
  src/cascadia/CascadiaPackage/ProfileIcons/pwsh.scale-100.png
  src/cascadia/CascadiaPackage/ProfileIcons/pwsh.scale-125.png
  src/cascadia/CascadiaPackage/ProfileIcons/pwsh.scale-150.png
  src/cascadia/CascadiaPackage/ProfileIcons/pwsh.scale-200.png
  src/cascadia/TerminalApp/PowershellCoreProfileGenerator.cpp
  src/cascadia/TerminalApp/PowershellCoreProfileGenerator.h
  src/cascadia/TerminalApp/Profile.h
Labels: AutoMerge

#4018 Refactor UiaTextRange For Improved Navigation and Reliability
  src/buffer/out/textBuffer.cpp
  src/buffer/out/textBuffer.hpp
  src/cascadia/TerminalControl/TermControlUiaProvider.cpp
  src/cascadia/TerminalControl/TermControlUiaProvider.hpp
  src/cascadia/TerminalControl/UiaTextRange.cpp
  src/cascadia/TerminalControl/UiaTextRange.hpp
  src/cascadia/TerminalControl/XamlUiaTextRange.cpp
  src/cascadia/TerminalCore/terminalrenderdata.cpp
  src/host/ut_host/TextBufferTests.cpp
  src/inc/LibraryIncludes.h
  src/interactivity/win32/screenInfoUiaProvider.cpp
  src/interactivity/win32/screenInfoUiaProvider.hpp
  src/interactivity/win32/uiaTextRange.cpp
  src/interactivity/win32/uiaTextRange.hpp
  src/interactivity/win32/ut_interactivity_win32/UiaTextRangeTests.cpp
  src/types/ScreenInfoUiaProviderBase.cpp
  src/types/ScreenInfoUiaProviderBase.h
  src/types/UiaTextRangeBase.cpp
  src/types/UiaTextRangeBase.hpp
  src/types/inc/viewport.hpp
  src/types/viewport.cpp
Labels: Area-Accessibility, Area-CodeHealth, AutoMerge, Product-Conhost, Product-Terminal

#4373 Introduce UiaTextRangeBase::FindText() for Accessibility
  src/cascadia/TerminalControl/UiaTextRange.cpp
  src/cascadia/TerminalControl/UiaTextRange.hpp
  src/cascadia/TerminalControl/XamlUiaTextRange.cpp
  src/inc/HostAndPropsheetIncludes.h
  src/interactivity/win32/screenInfoUiaProvider.hpp
  src/interactivity/win32/uiaTextRange.cpp
  src/interactivity/win32/uiaTextRange.hpp
  src/types/ScreenInfoUiaProviderBase.h
  src/types/UiaTextRangeBase.cpp
  src/types/UiaTextRangeBase.hpp
  src/types/WindowUiaProviderBase.hpp
Labels: Area-Accessibility, AutoMerge
