Repository microsoft/terminal, pull requests merged in 2020-02, with the labels that each got.

#4449 Adjust GetBoundingRect() for Inclusive end
  src/types/UiaTextRangeBase.cpp
Labels: Area-Accessibility, AutoMerge, Product-Conhost, Product-Terminal

#4450 Update TAEF to 10.51 and remove the private dep on Taef.TestAdapter
  build/.nuget/packages.config
  build/config/NuGet.config
  build/pipelines/templates/build-console-audit-job.yml
  build/pipelines/templates/build-console-steps.yml
  src/cascadia/LocalTests_TerminalApp/TestHostApp/TestHostApp.vcxproj
  src/common.build.tests.props
  src/host/ft_uia/Host.Tests.UIA.csproj
  src/host/ft_uia/packages.config
  src/terminal/parser/ut_parser/packages.config
  tools/OpenConsole.psm1
  tools/razzle.cmd
Labels: AutoMerge

#3963 [VT Mouse Mode] Translate SGR Mouse VT Sequences to MOUSE_EVENT_RECORD
  src/terminal/parser/InputStateMachineEngine.cpp
  src/terminal/parser/InputStateMachineEngine.hpp
  src/terminal/parser/ut_parser/InputEngineTest.cpp
Labels: Area-Input, AutoMerge, Product-Conpty

#3943 Add support for VT100 Auto Wrap Mode (DECAWM)
  src/host/_stream.cpp
  src/host/getset.cpp
  src/host/getset.h
  src/host/outputStream.cpp
  src/host/outputStream.hpp
  src/host/ut_host/ScreenBufferTests.cpp
  src/terminal/adapter/DispatchTypes.hpp
  src/terminal/adapter/ITermDispatch.hpp
  src/terminal/adapter/adaptDispatch.cpp
  src/terminal/adapter/adaptDispatch.hpp
  src/terminal/adapter/conGetSet.hpp
  src/terminal/adapter/termDispatch.hpp
  src/terminal/adapter/ut_adapter/adapterTest.cpp
  src/terminal/parser/ut_parser/OutputEngineTest.cpp
Labels: Area-VT, AutoMerge, Product-Conhost

#4422 Unify UTF-8 handling using til::u8u16 & revise WriteConsoleAImpl
  src/host/VtInputThread.cpp
  src/host/VtInputThread.hpp
  src/host/_stream.cpp
  src/host/_stream.h
Labels: Area-Output

#4451 Update index.md - Tips and Tricks
  doc/user-docs/index.md
Labels: AutoMerge, Needs-Second

#4350 Convert Tab to a WinRT type
  src/cascadia/LocalTests_TerminalApp/CommandlineTest.cpp
  src/cascadia/LocalTests_TerminalApp/TabTests.cpp
  src/cascadia/TerminalApp/ActionArgs.h
  src/cascadia/TerminalApp/ActionArgs.idl
  src/cascadia/TerminalApp/Tab.cpp
  src/cascadia/TerminalApp/Tab.h
  src/cascadia/TerminalApp/Tab.idl
  src/cascadia/TerminalApp/TerminalApp.vcxproj
  src/cascadia/TerminalApp/TerminalPage.cpp
  src/cascadia/TerminalApp/TerminalPage.h
  src/cascadia/TerminalApp/lib/TerminalAppLib.vcxproj
  src/cascadia/TerminalApp/lib/TerminalAppLib.vcxproj.filters
  src/cascadia/inc/cppwinrt_utils.h
Labels: Area-CodeHealth, AutoMerge, Product-Terminal

#4392 Add VS Code keys and improve keybinding documentation
  doc/cascadia/SettingsSchema.md
  src/cascadia/TerminalApp/KeyChordSerialization.cpp
Labels: Area-Settings, Issue-Bug, Issue-Docs, Needs-Second, Product-Terminal

#4468 schema: add default colors for foreground and background
  doc/cascadia/profiles.schema.json
Labels: AutoMerge

#4467 Added shift+ins to defaults.json
  src/cascadia/TerminalApp/defaults-universal.json
  src/cascadia/TerminalApp/defaults.json
Labels: Needs-Second

#4518 doc: correct spelling error in UsingJsonSettings.md
  doc/user-docs/UsingJsonSettings.md
Labels: Needs-Author-Feedback

#4490 Move tests to invoke `te.exe` directly instead of using VSTest runner
  OpenConsole.sln
  build/pipelines/templates/build-console-steps.yml
  build/scripts/Run-Tests.ps1
  src/host/ft_host/API_InputTests.cpp
  src/host/ut_host/ConptyOutputTests.cpp
  src/host/ut_host/VtIoTests.cpp
  src/renderer/base/renderer.cpp
Labels: AutoMerge

#4505 Initialize Windows Terminal in STA
  src/cascadia/WindowsTerminal/main.cpp
Labels: AutoMerge

#4433 Passthrough `CSI 3 J` in Conpty
  src/cascadia/UnitTests_TerminalCore/ConptyRoundtripTests.cpp
  src/terminal/adapter/adaptDispatch.cpp
Labels: AutoMerge

#4522 Force the use of named forwarders in PublicTermCore for Win7
  src/cascadia/PublicTerminalCore/PublicTerminalCore.vcxproj
Labels: AutoMerge, Needs-Second

#4309 Fix FillConsoleOutputCharacterA crash
  src/host/_output.cpp
  src/host/ft_host/API_FillOutputTests.cpp
  src/host/ft_host/Common.cpp
  src/host/ft_host/Common.hpp
  src/host/ft_host/InitTests.cpp
  src/inc/til.h
  src/types/convert.cpp
Labels: Area-Server, Product-Conhost

#3344 Fix scrollbar doesn't update viewport after window resize
  src/cascadia/TerminalApp/Tab.cpp
  src/cascadia/TerminalControl/TermControl.cpp
  src/cascadia/TerminalControl/TermControl.h
  src/cascadia/TerminalControl/TermControl.idl
Labels: Area-TerminalControl, AutoMerge, Product-Terminal

#4523 Limit Concept of TextBuffer's Size in UIA
  src/types/UiaTextRangeBase.cpp
  src/types/UiaTextRangeBase.hpp
Labels: AutoMerge

#4412 doc: add useAcrylic unfocused limitation to docs
  doc/cascadia/SettingsSchema.md
  doc/user-docs/index.md
Labels: Area-Settings, Issue-Docs

#4403 Move cursor in conpty correctly after a backspace when we've delayed an EOL wrap
  src/cascadia/UnitTests_TerminalCore/ConptyRoundtripTests.cpp
  src/renderer/vt/XtermEngine.cpp
  src/renderer/vt/paint.cpp
  src/renderer/vt/vtrenderer.hpp
Labels: Area-Rendering, AutoMerge, Product-Conpty

#4497 Fix UiaTextRange Misaligned Bounding Rects
  src/cascadia/TerminalControl/UiaTextRange.cpp
Labels: Area-Accessibility, AutoMerge, Product-Terminal

#4526 Make ScreenInfoUiaProvider::GetVisibleRanges() Return Only One Range
  src/types/ScreenInfoUiaProviderBase.cpp
Labels: Area-Accessibility, AutoMerge, Product-Conhost, Product-Terminal

#4525 uia: add support for scrolling the viewport
  src/cascadia/TerminalControl/TermControlUiaProvider.cpp
  src/cascadia/TerminalControl/TermControlUiaProvider.hpp
  src/cascadia/TerminalControl/UiaTextRange.cpp
  src/interactivity/win32/screenInfoUiaProvider.hpp
  src/types/ScreenInfoUiaProviderBase.h
Labels: Area-Accessibility, Needs-Second, Product-Terminal

#4538 Fix the crash when closing Terminal containing multiple tabs.
  src/cascadia/TerminalApp/TerminalPage.cpp
Labels: Area-User Interface, AutoMerge, Issue-Bug, Product-Terminal, Severity-Crash

#4541 Don't say "drop files" for things that aren't files
  src/cascadia/TerminalControl/TermControl.cpp
Labels: AutoMerge

#4534 Gather data on profile customization and tab settings to help us improve defaults
  src/cascadia/TerminalApp/AppKeyBindingsSerialization.cpp
  src/cascadia/TerminalApp/CascadiaSettingsSerialization.cpp
  src/cascadia/TerminalApp/TerminalPage.cpp
  src/cascadia/TerminalApp/lib/TerminalAppLib.vcxproj
  src/cascadia/TerminalConnection/ConptyConnection.cpp
  src/cascadia/TerminalConnection/ConptyConnection.h
  src/cascadia/TerminalControl/TermControl.cpp
Labels: Area-Settings, AutoMerge, Gathering-Data, Issue-Task, Product-Terminal

#4555 When patching profiles in, copy the user's indentation
  src/cascadia/TerminalApp/CascadiaSettingsSerialization.cpp
Labels: AutoMerge

#4556 Update stock user defaults to the list+defaults style
  src/cascadia/TerminalApp/userDefaults.json
Labels: AutoMerge

#4506 Fix click-drag selection on an unfocused Terminal
  src/cascadia/TerminalControl/TermControl.cpp
  src/cascadia/TerminalControl/TermControl.h
Labels: Area-TerminalControl, AutoMerge, Product-Terminal

#4559 Fix crash when closing a ton of tabs at once
  src/cascadia/TerminalControl/TermControl.cpp
Labels: AutoMerge, Issue-Bug, Product-Terminal, Severity-Crash

#4594 Avoid processing VT Render Trace strings when no one is listening
  src/renderer/vt/tracing.cpp
Labels: Area-Performance, AutoMerge, Issue-Task, Product-Conpty

#3511 Throttle SetEvent call in render thread
  src/renderer/base/thread.cpp
  src/renderer/base/thread.hpp
Labels: Area-Performance, Area-Rendering

#4592 readme: reintroduce the Store install link
  README.md
Labels: AutoMerge

#4617 fix: escape double quotes on cmder and Anaconda profiles
  doc/user-docs/ThirdPartyToolProfiles.md
Labels: AutoMerge

#4639 Batch up to 64 files per clang-format to speed it up
  build/pipelines/templates/check-formatting.yml
  tools/OpenConsole.psm1
Labels: Area-Build, AutoMerge, Product-Meta

#4596 Fix duplicate copyOnSelect when clicking on an unfocused terminal
  src/cascadia/TerminalControl/TermControl.cpp
  src/cascadia/TerminalControl/TermControl.h
Labels: AutoMerge

#4466 Make ScreenInfoUiaProvider::GetSelection() Return One Selection
  src/cascadia/TerminalControl/TermControl.cpp
  src/cascadia/TerminalControl/TermControlUiaProvider.cpp
  src/cascadia/TerminalControl/TermControlUiaProvider.hpp
  src/cascadia/TerminalControl/UiaTextRange.cpp
  src/cascadia/TerminalControl/UiaTextRange.hpp
  src/cascadia/TerminalCore/Terminal.hpp
  src/cascadia/TerminalCore/TerminalSelection.cpp
  src/cascadia/TerminalCore/terminalrenderdata.cpp
  src/host/renderData.cpp
  src/host/renderData.hpp
  src/interactivity/win32/screenInfoUiaProvider.cpp
  src/interactivity/win32/screenInfoUiaProvider.hpp
  src/interactivity/win32/uiaTextRange.cpp
  src/interactivity/win32/uiaTextRange.hpp
  src/types/IUiaData.h
  src/types/ScreenInfoUiaProviderBase.cpp
  src/types/ScreenInfoUiaProviderBase.h
  src/types/UiaTextRangeBase.cpp
Labels: Area-Accessibility, AutoMerge, Product-Conhost, Product-Terminal

#4664 Add DxEngine drawing ETW tracing for debugging and diagnostics purposes
  src/renderer/dx/DxRenderer.cpp
  src/renderer/dx/DxRenderer.hpp
Labels: Area-Rendering, AutoMerge, Issue-Task, Product-Terminal

#4495 UIA: Fix GetVisibleRanges() and add Tracing
  src/host/renderData.cpp
  src/host/tracing.cpp
  src/host/tracing.hpp
  src/types/ScreenInfoUiaProviderBase.cpp
  src/types/ScreenInfoUiaProviderBase.h
  src/types/UiaTextRangeBase.cpp
  src/types/UiaTextRangeBase.hpp
  src/types/UiaTracing.cpp
  src/types/UiaTracing.h
  src/types/lib/types.vcxproj
  src/types/lib/types.vcxproj.filters
Labels: Area-Accessibility, AutoMerge, Issue-Task, Product-Conhost, Product-Terminal

#4642 Unify resource filenames across the repository
  src/cascadia/CascadiaPackage/CascadiaPackage.wapproj
  src/cascadia/CascadiaPackage/Resources/Resources.language-en.resw
  src/cascadia/CascadiaPackage/Resources/Resources.resw
  src/cascadia/TerminalApp/Resources/Resources.language-en.resw
  src/cascadia/TerminalApp/lib/TerminalAppLib.vcxproj
  src/cascadia/TerminalConnection/Resources/Resources.language-en.resw
  src/cascadia/TerminalConnection/TerminalConnection.vcxproj
  src/cascadia/TerminalControl/Resources/Resources.language-en.resw
  src/cascadia/TerminalControl/TerminalControl.vcxproj
Labels: AutoMerge

#4652 Shim the Azure connection through a conhost to stop VT bleeding
  OpenConsole.sln
  src/cascadia/CascadiaPackage/CascadiaPackage.wapproj
  src/cascadia/TerminalApp/TerminalPage.cpp
  src/cascadia/TerminalAzBridge/ConsoleInputReader.cpp
  src/cascadia/TerminalAzBridge/ConsoleInputReader.h
  src/cascadia/TerminalAzBridge/TerminalAzBridge.vcxproj
  src/cascadia/TerminalAzBridge/main.cpp
  src/cascadia/TerminalAzBridge/packages.config
  src/cascadia/TerminalAzBridge/pch.cpp
  src/cascadia/TerminalAzBridge/pch.h
Labels: Area-AzureShell

#4668 Restrict DX run height adjustment to only relevant glyph AND Correct PTY rendering on trailing half of fullwidth glyphs
  OpenConsole.sln
  src/renderer/base/renderer.cpp
  src/renderer/dx/CustomTextLayout.cpp
  src/renderer/dx/CustomTextLayout.h
  src/renderer/dx/DxRenderer.cpp
  src/renderer/dx/dirs
  src/renderer/dx/ut_dx/CustomTextLayoutTests.cpp
  src/renderer/dx/ut_dx/DefaultResource.rc
  src/renderer/dx/ut_dx/Dx.Unit.Tests.vcxproj
  src/renderer/dx/ut_dx/product.pbxproj
  src/renderer/dx/ut_dx/sources
  src/renderer/vt/tracing.cpp
Labels: Area-Rendering, AutoMerge, Issue-Bug, Product-Terminal

#4671 Clip text to within the row we expect
  OpenConsole.sln
  src/renderer/dx/CustomTextRenderer.cpp
Labels: Area-Rendering, AutoMerge, Issue-Bug, Product-Terminal

#4685 Ensure til::u8u16 still works if the string consists of just a lead byte
  src/inc/til/u8u16convert.h
  src/til/ut_til/u8u16convertTests.cpp
Labels: AutoMerge, Needs-Second

#4548 Move Terminal UIA provider into Types & hook it up to the WPF control
  src/cascadia/PublicTerminalCore/HwndTerminal.cpp
  src/cascadia/PublicTerminalCore/HwndTerminal.hpp
  src/cascadia/PublicTerminalCore/pch.h
  src/cascadia/TerminalControl/TermControlAutomationPeer.cpp
  src/cascadia/TerminalControl/TermControlAutomationPeer.h
  src/cascadia/TerminalControl/TerminalControl.vcxproj
  src/cascadia/TerminalControl/XamlUiaTextRange.cpp
  src/cascadia/TerminalControl/XamlUiaTextRange.h
  src/cascadia/WpfTerminalControl/NativeMethods.cs
  src/cascadia/WpfTerminalControl/TerminalContainer.cs
  src/cascadia/WpfTerminalControl/TerminalControl.xaml.cs
  src/interactivity/win32/uiaTextRange.cpp
  src/interactivity/win32/uiaTextRange.hpp
  src/types/IControlAccessibilityInfo.h
  src/types/ScreenInfoUiaProviderBase.h
  src/types/TermControlUiaProvider.cpp
  src/types/TermControlUiaProvider.hpp
  src/types/TermControlUiaTextRange.cpp
  src/types/TermControlUiaTextRange.hpp
  src/types/UiaTextRangeBase.hpp
  src/types/lib/types.vcxproj
  src/types/lib/types.vcxproj.filters
  src/types/sources.inc
Labels: AutoMerge

#4711 Add support for cleartype text antialiasing
  doc/cascadia/SettingsSchema.md
  doc/cascadia/profiles.schema.json
  src/cascadia/TerminalApp/Profile.cpp
  src/cascadia/TerminalApp/Profile.h
  src/cascadia/TerminalApp/defaults.json
  src/cascadia/TerminalControl/TermControl.cpp
  src/cascadia/TerminalSettings/IControlSettings.idl
  src/cascadia/TerminalSettings/TerminalSettings.cpp
  src/cascadia/TerminalSettings/terminalsettings.h
  src/renderer/dx/DxRenderer.cpp
  src/renderer/dx/DxRenderer.hpp
Labels: Area-Rendering, Area-Settings, AutoMerge, Needs-Second, Product-Terminal

#4722 Fix the build on VS 2019 Update 5
  src/cascadia/CascadiaPackage/CascadiaPackage.wapproj
  src/terminal/adapter/adaptDefaults.hpp
  src/terminal/adapter/conGetSet.hpp
Labels: AutoMerge

#4721 TermControl: don't use narrow when narrow_cast will do
  src/cascadia/TerminalControl/TermControl.cpp
  src/cascadia/TerminalControl/TermControlAutomationPeer.cpp
Labels: Needs-Second

#4688 Display Emojis, Kaomojis, and symbols while in IME mode
  src/cascadia/TerminalControl/TSFInputControl.cpp
  src/cascadia/TerminalControl/TSFInputControl.h
  src/cascadia/WinRTUtils/inc/Utils.h
Labels: Area-Input, AutoMerge, Issue-Bug, Priority-1, Product-Terminal

#4723 Allow IME input in Search Box
  src/cascadia/TerminalControl/TermControl.cpp
Labels: Area-TerminalControl, AutoMerge, Issue-Bug, Priority-1, Product-Terminal

#4731 Avoid splitting surrogate pairs when breaking runs for scaling
  src/renderer/dx/CustomTextLayout.cpp
Labels: Area-Rendering, AutoMerge, Product-Terminal

#4415 Make Conpty emit wrapped lines as actually wrapped lines
  src/cascadia/TerminalCore/Terminal.cpp
  src/cascadia/UnitTests_TerminalCore/ConptyRoundtripTests.cpp
  src/cascadia/UnitTests_TerminalCore/TerminalBufferTests.cpp
  src/cascadia/UnitTests_TerminalCore/TestUtils.h
  src/host/ut_host/VtRendererTests.cpp
  src/interactivity/onecore/BgfxEngine.cpp
  src/interactivity/onecore/BgfxEngine.hpp
  src/renderer/base/renderer.cpp
  src/renderer/base/renderer.hpp
  src/renderer/dx/DxRenderer.cpp
  src/renderer/dx/DxRenderer.hpp
  src/renderer/gdi/gdirenderer.hpp
  src/renderer/gdi/paint.cpp
  src/renderer/inc/IRenderEngine.hpp
  src/renderer/uia/UiaRenderer.cpp
  src/renderer/uia/UiaRenderer.hpp
  src/renderer/vt/XtermEngine.cpp
  src/renderer/vt/XtermEngine.hpp
  src/renderer/vt/paint.cpp
  src/renderer/vt/tracing.cpp
  src/renderer/vt/tracing.hpp
  src/renderer/vt/vtrenderer.hpp
  src/renderer/wddmcon/WddmConRenderer.cpp
  src/renderer/wddmcon/WddmConRenderer.hpp
Labels: Area-Rendering, AutoMerge, Product-Conpty, Product-Terminal

#4698 Fix RenderThread's notify mechanism
  src/renderer/base/thread.cpp
  src/renderer/base/thread.hpp
Labels: Area-Rendering, AutoMerge, Product-Meta

#4714 Accept String value for Keybindings's Keys
  doc/cascadia/profiles.schema.json
  doc/user-docs/UsingJsonSettings.md
  src/cascadia/LocalTests_TerminalApp/KeyBindingsTests.cpp
  src/cascadia/TerminalApp/AppKeyBindingsSerialization.cpp
  src/cascadia/TerminalApp/defaults.json
Labels: Area-Settings, AutoMerge, Product-Terminal

#4560 Move rect expansion to textbuffer; refactor selection code
  src/buffer/out/textBuffer.cpp
  src/buffer/out/textBuffer.hpp
  src/cascadia/PublicTerminalCore/HwndTerminal.cpp
  src/cascadia/TerminalControl/TermControl.cpp
  src/cascadia/TerminalCore/Terminal.cpp
  src/cascadia/TerminalCore/Terminal.hpp
  src/cascadia/TerminalCore/TerminalSelection.cpp
  src/cascadia/TerminalCore/terminalrenderdata.cpp
  src/cascadia/UnitTests_TerminalCore/SelectionTest.cpp
  src/host/renderData.cpp
  src/host/renderData.hpp
  src/host/selection.cpp
  src/host/selection.hpp
  src/host/ut_host/SelectionTests.cpp
  src/host/ut_host/TextBufferTests.cpp
  src/interactivity/win32/screenInfoUiaProvider.cpp
  src/types/IUiaData.h
  src/types/TermControlUiaProvider.cpp
Labels: Area-Interaction, Issue-Task, Product-Conhost, Product-Terminal

#4743 Convert TSFInputControl to a .xaml file
  src/cascadia/TerminalControl/TSFInputControl.cpp
  src/cascadia/TerminalControl/TSFInputControl.h
  src/cascadia/TerminalControl/TSFInputControl.xaml
  src/cascadia/TerminalControl/TerminalControl.vcxproj
Labels: AutoMerge

#4720 fix mouse events in the wpf control
  src/cascadia/PublicTerminalCore/HwndTerminal.cpp
  src/cascadia/PublicTerminalCore/HwndTerminal.hpp
  src/cascadia/WpfTerminalControl/TerminalContainer.cs
Labels: Area-WPFControl

#4658 doc: add a tip about opening terminal in current directory
  doc/user-docs/index.md
Labels: Issue-Docs, Needs-Second, Product-Terminal
