Repository microsoft/terminal, pull requests merged in 2020-09, with the labels that each got.

#7504 Prevent crash when attempting to select an out-of-bounds UIA text range
  src/types/UiaTextRangeBase.cpp
Labels: AutoMerge, Needs-Second

#7515 Add profiles to the Jumplist
  .github/actions/spell-check/dictionary/microsoft.txt
  src/cascadia/TerminalApp/AppLogic.cpp
  src/cascadia/TerminalApp/AppLogic.h
  src/cascadia/TerminalApp/Jumplist.cpp
  src/cascadia/TerminalApp/Jumplist.h
  src/cascadia/TerminalApp/TerminalAppLib.vcxproj
Labels: Area-User Interface, AutoMerge, Issue-Feature, Product-Terminal

#7447 Update to a newer MUX prerelease; remove workaround for compact sizing
  src/cascadia/CascadiaPackage/CascadiaPackage.wapproj
  src/cascadia/LocalTests_TerminalApp/TerminalApp.LocalTests.vcxproj
  src/cascadia/LocalTests_TerminalApp/TestHostApp/TestHostApp.vcxproj
  src/cascadia/TerminalApp/TerminalAppLib.vcxproj
  src/cascadia/TerminalApp/TerminalPage.cpp
  src/cascadia/TerminalApp/dll/TerminalApp.vcxproj
  src/cascadia/TerminalApp/packages.config
  src/cascadia/WindowsTerminal/WindowsTerminal.vcxproj
  src/cascadia/WindowsTerminal/packages.config
  src/cascadia/WindowsTerminalUniversal/WindowsTerminalUniversal.vcxproj
  src/cascadia/ut_app/TerminalApp.UnitTests.vcxproj
Labels: Area-CodeHealth, AutoMerge, Issue-Task, Product-Terminal

#7379 Add support for DECSCUSR "0" to restore cursor to user default
  src/cascadia/TerminalCore/Terminal.cpp
  src/cascadia/TerminalCore/Terminal.hpp
  src/cascadia/TerminalCore/TerminalApi.cpp
  src/host/outputStream.cpp
  src/host/outputStream.hpp
  src/terminal/adapter/DispatchTypes.hpp
  src/terminal/adapter/adaptDispatch.cpp
  src/terminal/adapter/conGetSet.hpp
  src/terminal/adapter/ut_adapter/adapterTest.cpp
  src/terminal/parser/OutputStateMachineEngine.hpp
Labels: Area-VT, AutoMerge, Issue-Task, Product-Conhost, Product-Terminal

#7530 Keep degenerate UIA text ranges degenerate after movement
  src/interactivity/win32/ut_interactivity_win32/UiaTextRangeTests.cpp
  src/types/UiaTextRangeBase.cpp
Labels: Area-Accessibility, AutoMerge, Issue-Bug, Priority-1, Product-Conhost, Product-Terminal

#7567 jumplist: prefer the app execution alias in %LOCALAPPDATA%
  src/cascadia/TerminalApp/Jumplist.cpp
Labels: AutoMerge

#7573 Remove AcrylicOpacity from AzureCloudShellGenerator
  src/cascadia/TerminalApp/AzureCloudShellGenerator.cpp
Labels: Area-Settings, AutoMerge, Issue-Bug, Priority-3, Product-Terminal

#7457 Make CascadiaSettings a WinRT object
  src/cascadia/LocalTests_TerminalApp/ColorSchemeTests.cpp
  src/cascadia/LocalTests_TerminalApp/ProfileTests.cpp
  src/cascadia/LocalTests_TerminalApp/SettingsTests.cpp
  src/cascadia/LocalTests_TerminalApp/TabTests.cpp
  src/cascadia/TerminalApp/AppActionHandlers.cpp
  src/cascadia/TerminalApp/AppLogic.cpp
  src/cascadia/TerminalApp/AppLogic.h
  src/cascadia/TerminalApp/CascadiaSettings.cpp
  src/cascadia/TerminalApp/CascadiaSettings.h
  src/cascadia/TerminalApp/CascadiaSettings.idl
  src/cascadia/TerminalApp/CascadiaSettingsSerialization.cpp
  src/cascadia/TerminalApp/Command.cpp
  src/cascadia/TerminalApp/Command.h
  src/cascadia/TerminalApp/Jumplist.cpp
  src/cascadia/TerminalApp/Jumplist.h
  src/cascadia/TerminalApp/Pane.cpp
  src/cascadia/TerminalApp/TerminalAppLib.vcxproj
  src/cascadia/TerminalApp/TerminalPage.cpp
  src/cascadia/TerminalApp/TerminalPage.h
  src/cascadia/ut_app/DynamicProfileTests.cpp
Labels: Area-Settings, AutoMerge, Issue-Task, Product-Terminal

#6720 Add initial settings UI spec
  doc/specs/#1564 - Settings UI/appearance.png
  doc/specs/#1564 - Settings UI/design.md
  doc/specs/#1564 - Settings UI/keyboard-modal-add.png
  doc/specs/#1564 - Settings UI/keyboard-modal-args.png
  doc/specs/#1564 - Settings UI/keyboard-modal.png
  doc/specs/#1564 - Settings UI/keyboard.png
  doc/specs/#1564 - Settings UI/navigation-2.png
  doc/specs/#1564 - Settings UI/navigation.png
  doc/specs/#1564 - Settings UI/spec.md
Labels: Area-Settings, Area-User Interface, Issue-Docs, Product-Terminal

#7575 Destruct ConptyConnection on a background thread
  src/cascadia/TerminalConnection/ConptyConnection.cpp
  src/cascadia/TerminalConnection/ConptyConnection.h
Labels: Area-TerminalConnection, AutoMerge, Issue-Bug, Needs-Second, Priority-1, Product-Terminal, Severity-Crash

#7583 Switch all DSR responses to appending instead of prepending
  .github/actions/spell-check/dictionary/microsoft.txt
  src/host/directio.cpp
  src/host/directio.h
  src/host/outputStream.cpp
  src/host/outputStream.hpp
  src/terminal/adapter/adaptDispatch.cpp
  src/terminal/adapter/conGetSet.hpp
  src/terminal/adapter/ut_adapter/adapterTest.cpp
Labels: Area-Input, AutoMerge, Issue-Bug, Needs-Second, Product-Terminal

#7523 Open up content dialogs for invalid URIs and unsupported schemes
  src/cascadia/TerminalApp/Resources/en-US/Resources.resw
  src/cascadia/TerminalApp/TerminalPage.cpp
  src/cascadia/TerminalApp/TerminalPage.h
  src/cascadia/TerminalApp/TerminalPage.xaml
Labels: Needs-Second

#7608 Fix OSC8 termination over the PTY after SGR 0
  src/renderer/vt/paint.cpp
Labels: Area-VT, Issue-Bug, Priority-1, Product-Conpty, Severity-Blocking

#7619 Make til::color's COLORREF conversion more optimal
  .github/actions/spell-check/expect/expect.txt
  src/inc/til/color.h
Labels: AutoMerge

#7537 Introduce KeyMapping and Move TerminalSettings construction
  src/cascadia/LocalTests_TerminalApp/ColorSchemeTests.cpp
  src/cascadia/LocalTests_TerminalApp/KeyBindingsTests.cpp
  src/cascadia/LocalTests_TerminalApp/ProfileTests.cpp
  src/cascadia/LocalTests_TerminalApp/SettingsTests.cpp
  src/cascadia/LocalTests_TerminalApp/TestUtils.h
  src/cascadia/TerminalApp/AppActionHandlers.cpp
  src/cascadia/TerminalApp/AppKeyBindings.cpp
  src/cascadia/TerminalApp/AppKeyBindings.h
  src/cascadia/TerminalApp/AppKeyBindings.idl
  src/cascadia/TerminalApp/AppLogic.cpp
  src/cascadia/TerminalApp/CascadiaSettings.cpp
  src/cascadia/TerminalApp/CascadiaSettings.h
  src/cascadia/TerminalApp/CascadiaSettings.idl
  src/cascadia/TerminalApp/CascadiaSettingsSerialization.cpp
  src/cascadia/TerminalApp/ColorScheme.cpp
  src/cascadia/TerminalApp/ColorScheme.h
  src/cascadia/TerminalApp/ColorScheme.idl
  src/cascadia/TerminalApp/Command.cpp
  src/cascadia/TerminalApp/GlobalAppSettings.cpp
  src/cascadia/TerminalApp/GlobalAppSettings.h
  src/cascadia/TerminalApp/GlobalAppSettings.idl
  src/cascadia/TerminalApp/Jumplist.cpp
  src/cascadia/TerminalApp/KeyMapping.cpp
  src/cascadia/TerminalApp/KeyMapping.h
  src/cascadia/TerminalApp/KeyMapping.idl
  src/cascadia/TerminalApp/KeyMappingSerialization.cpp
  src/cascadia/TerminalApp/Profile.cpp
  src/cascadia/TerminalApp/Profile.h
  src/cascadia/TerminalApp/Profile.idl
  src/cascadia/TerminalApp/ShortcutActionDispatch.idl
  src/cascadia/TerminalApp/TerminalAppLib.vcxproj
  src/cascadia/TerminalApp/TerminalAppLib.vcxproj.filters
  src/cascadia/TerminalApp/TerminalPage.cpp
  src/cascadia/TerminalApp/TerminalPage.h
  src/cascadia/TerminalApp/TerminalSettings.cpp
  src/cascadia/TerminalApp/TerminalSettings.h
  src/cascadia/TerminalCore/ICoreSettings.idl
  src/cascadia/UnitTests_TerminalCore/MockTermSettings.h
Labels: AutoMerge

#7655 Fix failing HyperlinkIdConsistency unit test
  src/cascadia/UnitTests_TerminalCore/ConptyRoundtripTests.cpp
Labels: AutoMerge

#7609 Update ColorScheme with Json Serializer and color table API
  .github/actions/spell-check/dictionary/apis.txt
  src/cascadia/LocalTests_TerminalApp/ColorSchemeTests.cpp
  src/cascadia/TerminalApp/ColorScheme.cpp
  src/cascadia/TerminalApp/ColorScheme.h
  src/cascadia/TerminalApp/ColorScheme.idl
  src/cascadia/TerminalApp/JsonUtils.h
  src/cascadia/TerminalApp/TerminalSettingsSerializationHelpers.h
  src/cascadia/inc/cppwinrt_utils.h
  src/cascadia/ut_app/JsonTests.cpp
  src/cascadia/ut_app/JsonUtilsTests.cpp
Labels: Area-Settings, Product-Terminal

#7648 Update Cascadia Code to 2009.14
  res/Cascadia.ttf
  res/CascadiaMono.ttf
  res/README.md
Labels: AutoMerge, Needs-Second

#7659 Give Tab ownership of its SwitchToTab command
  src/cascadia/TerminalApp/CommandPalette.cpp
  src/cascadia/TerminalApp/CommandPalette.h
  src/cascadia/TerminalApp/Tab.cpp
  src/cascadia/TerminalApp/Tab.h
  src/cascadia/TerminalApp/Tab.idl
  src/cascadia/TerminalApp/TerminalPage.cpp
  src/cascadia/TerminalApp/TerminalPage.h
Labels: Needs-Second

#7673 Make sure we don't hide the cursor until the IME starts
  .github/actions/spell-check/expect/expect.txt
  src/host/conimeinfo.cpp
  src/host/convarea.cpp
Labels: AutoMerge

#7630 [1.3 STABLE ONLY] Unbind `togglePaneZoom`
  doc/cascadia/profiles.schema.json
  src/cascadia/TerminalApp/ActionAndArgs.cpp
  src/cascadia/TerminalApp/defaults.json
Labels: Needs-Second

#7490 Add support for the "blink" graphic rendition attribute
  .github/actions/spell-check/expect/expect.txt
  src/buffer/out/TextAttribute.cpp
  src/buffer/out/TextAttribute.hpp
  src/cascadia/TerminalControl/TermControl.cpp
  src/cascadia/TerminalControl/TermControl.h
  src/cascadia/TerminalCore/Terminal.cpp
  src/cascadia/TerminalCore/Terminal.hpp
  src/cascadia/TerminalCore/TerminalDispatchGraphics.cpp
  src/cascadia/TerminalCore/terminalrenderdata.cpp
  src/host/CursorBlinker.cpp
  src/host/consoleInformation.cpp
  src/host/server.h
  src/host/settings.cpp
  src/host/settings.hpp
  src/renderer/base/BlinkingState.cpp
  src/renderer/base/lib/base.vcxproj
  src/renderer/base/lib/base.vcxproj.filters
  src/renderer/inc/BlinkingState.hpp
  src/terminal/adapter/DispatchTypes.hpp
  src/terminal/adapter/adaptDispatchGraphics.cpp
Labels: Area-VT, AutoMerge, Issue-Task, Product-Conhost, Product-Terminal

#7675 Convert TerminalSettingsEditor into a DLL
  OpenConsole.sln
  src/cascadia/TerminalApp/TerminalAppLib.vcxproj
  src/cascadia/TerminalApp/dll/TerminalApp.vcxproj
  src/cascadia/TerminalApp/pch.h
  src/cascadia/TerminalSettingsEditor/App.cpp
  src/cascadia/TerminalSettingsEditor/App.h
  src/cascadia/TerminalSettingsEditor/App.idl
  src/cascadia/TerminalSettingsEditor/App.xaml
  src/cascadia/TerminalSettingsEditor/Assets/Square150x150Logo.png
  src/cascadia/TerminalSettingsEditor/Assets/Square44x44Logo.png
  src/cascadia/TerminalSettingsEditor/Assets/StoreLogo.png
  src/cascadia/TerminalSettingsEditor/ColorSchemes.idl
  src/cascadia/TerminalSettingsEditor/CommonResources.xaml
  src/cascadia/TerminalSettingsEditor/GlobalAppearance.idl
  src/cascadia/TerminalSettingsEditor/Home.xaml
  src/cascadia/TerminalSettingsEditor/Interaction.idl
  src/cascadia/TerminalSettingsEditor/Launch.idl
  src/cascadia/TerminalSettingsEditor/MainPage.cpp
  src/cascadia/TerminalSettingsEditor/MainPage.xaml
  src/cascadia/TerminalSettingsEditor/Microsoft.Terminal.Settings.Editor.def
  src/cascadia/TerminalSettingsEditor/Microsoft.Terminal.Settings.Editor.filters
  src/cascadia/TerminalSettingsEditor/Microsoft.Terminal.Settings.Editor.vcxproj
  src/cascadia/TerminalSettingsEditor/ObjectModel/AppSettings.cpp
  src/cascadia/TerminalSettingsEditor/ObjectModel/AppSettings.h
  src/cascadia/TerminalSettingsEditor/ObjectModel/ColorScheme.cpp
  src/cascadia/TerminalSettingsEditor/ObjectModel/ColorScheme.h
  src/cascadia/TerminalSettingsEditor/ObjectModel/ColorScheme.idl
  src/cascadia/TerminalSettingsEditor/ObjectModel/ColorSchemeModel.cpp
  src/cascadia/TerminalSettingsEditor/ObjectModel/ColorSchemeModel.h
  src/cascadia/TerminalSettingsEditor/ObjectModel/ColorSchemeModel.idl
  src/cascadia/TerminalSettingsEditor/ObjectModel/GlobalSettings.cpp
  src/cascadia/TerminalSettingsEditor/ObjectModel/GlobalSettings.h
  src/cascadia/TerminalSettingsEditor/ObjectModel/GlobalSettings.idl
  src/cascadia/TerminalSettingsEditor/ObjectModel/GlobalSettingsModel.cpp
  src/cascadia/TerminalSettingsEditor/ObjectModel/GlobalSettingsModel.h
  src/cascadia/TerminalSettingsEditor/ObjectModel/GlobalSettingsModel.idl
  src/cascadia/TerminalSettingsEditor/ObjectModel/Profile.cpp
  src/cascadia/TerminalSettingsEditor/ObjectModel/Profile.h
  src/cascadia/TerminalSettingsEditor/ObjectModel/Profile.idl
  src/cascadia/TerminalSettingsEditor/ObjectModel/ProfileModel.cpp
  src/cascadia/TerminalSettingsEditor/ObjectModel/ProfileModel.h
  src/cascadia/TerminalSettingsEditor/ObjectModel/ProfileModel.idl
  src/cascadia/TerminalSettingsEditor/Package.appxmanifest
  src/cascadia/TerminalSettingsEditor/Profiles.idl
  src/cascadia/TerminalSettingsEditor/PropertySheet.props
  src/cascadia/TerminalSettingsEditor/Rendering.idl
  src/cascadia/WindowsTerminal/WindowsTerminal.vcxproj
Labels: AutoMerge

#7677 Fix A11y EndExclusive Error for Move & Expand
  src/buffer/out/textBuffer.cpp
  src/host/ut_host/TextBufferTests.cpp
  src/interactivity/win32/ut_interactivity_win32/UiaTextRangeTests.cpp
Labels: Area-Accessibility, AutoMerge, Issue-Bug, Priority-1, Product-Conhost, Severity-Crash

#7768 When win32 is resizing the viewport, make sure Right > Left
  src/host/screenInfo.cpp
Labels: Area-Output, Issue-Bug, Needs-Second, Priority-0, Product-Conhost, Severity-Crash

#7738 Fix the "visual representation" optimization for hyperlinks
  src/buffer/out/TextAttribute.hpp
Labels: Area-Rendering, AutoMerge, Issue-Bug, Priority-2, Product-Conpty

#7640 Introduce til::presorted_static_map
  .github/actions/spell-check/expect/expect.txt
  src/inc/til/static_map.h
  src/til/ut_til/StaticMapTests.cpp
Labels: AutoMerge

#7770 Fix and test TextBuffer::MoveToPreviousWord()
  src/buffer/out/textBuffer.cpp
  src/host/ut_host/TextBufferTests.cpp
  src/interactivity/win32/ut_interactivity_win32/UiaTextRangeTests.cpp
Labels: Area-Accessibility, AutoMerge, Issue-Bug, Needs-Second, Priority-1, Product-Conhost, Product-Terminal

#7783 Fix parallel builds by specifying the application type for WAP
  build/pipelines/templates/build-console-steps.yml
  src/cascadia/TerminalAzBridge/TerminalAzBridge.vcxproj
  src/cascadia/WindowsTerminal/WindowsTerminal.vcxproj
Labels: AutoMerge

#7789 Add optimization to get a11y next word
  src/buffer/out/textBuffer.cpp
  src/buffer/out/textBuffer.hpp
Labels: Area-Accessibility, AutoMerge, Issue-Task, Product-Conhost
