Repository microsoft/terminal, pull requests merged in 2021-06, with the labels that each got.

#10264 Enable winrt::make<> detection
  src/cascadia/Remoting/WindowManager.h
  src/cascadia/ut_app/TerminalApp.UnitTests.vcxproj
  src/cppwinrt.build.pre.props
Labels: Area-CodeHealth, AutoMerge, Priority-3

#10268 Make the xaml formatting script work outside the root directory
  tools/OpenConsole.psm1
Labels: Area-Build, AutoMerge, Issue-Bug, Product-Meta

#10307 Cleanup from bell flash PR
  src/cascadia/TerminalControl/TermControl.cpp
  src/cascadia/TerminalControl/TermControl.h
Labels: AutoMerge

#10173 Polish code for actions page
  src/cascadia/TerminalSettingsEditor/Actions.cpp
  src/cascadia/TerminalSettingsEditor/Actions.h
  src/cascadia/TerminalSettingsEditor/Actions.idl
  src/cascadia/TerminalSettingsEditor/Actions.xaml
  src/cascadia/TerminalSettingsEditor/CommonResources.xaml
  src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw
  src/cascadia/TerminalSettingsEditor/ViewModelHelpers.h
  src/cascadia/TerminalSettingsModel/ActionMap.cpp
Labels: Area-Settings UI, AutoMerge, Issue-Task, Needs-Second, Product-Terminal

#10335 Fix some places where we weren't using winrt::make
  src/cascadia/TerminalApp/App.base.h
  src/cascadia/TerminalSettingsEditor/MainPage.h
  src/cascadia/TerminalSettingsModel/ActionMap.cpp
Labels: AutoMerge

#10342 Enable incremental linking for debug builds
  src/common.build.pre.props
Labels: AutoMerge

#10367 Restore helix runs by passing parameters
  build/pipelines/templates/build-console-ci.yml
Labels: Area-Build, AutoMerge, Issue-Bug, Product-Conhost

#10370 Restore embedded manifests to say 18362
  src/cascadia/LocalTests_TerminalApp/TerminalApp.LocalTests.manifest
  src/cascadia/WindowsTerminal/WindowsTerminal.manifest
  src/cascadia/ut_app/TerminalApp.Unit.Tests.manifest
Labels: Area-Build, AutoMerge, Issue-Bug, Product-Meta

#10357 Lock for writing in `ControlCore::SetBackgroundOpacity`
  src/cascadia/TerminalControl/ControlCore.cpp
Labels: AutoMerge

#10369 Add percentage sign to opacity slider values
  src/cascadia/TerminalSettingsEditor/Converters.idl
  src/cascadia/TerminalSettingsEditor/Microsoft.Terminal.Settings.Editor.vcxproj
  src/cascadia/TerminalSettingsEditor/Microsoft.Terminal.Settings.Editor.vcxproj.filters
  src/cascadia/TerminalSettingsEditor/PercentageSignConverter.cpp
  src/cascadia/TerminalSettingsEditor/PercentageSignConverter.h
  src/cascadia/TerminalSettingsEditor/Profiles.xaml
Labels: Area-Settings UI, AutoMerge, Issue-Task, Product-Terminal, zPreview-Service-Consider

#10389 Activate window only (no toggle) when inbound connection arrives
  src/cascadia/WindowsTerminal/AppHost.cpp
Labels: Area-DefApp, AutoMerge, Issue-Bug, Priority-2, Product-Terminal, zPreview-Service-Consider

#10396 Summon, not toggle visibility, window on command line dispatch
  src/cascadia/WindowsTerminal/AppHost.cpp
Labels: Area-Remoting, AutoMerge, Issue-Bug, Needs-Second, Priority-2, Product-Terminal

#10297 Replace feedback button with command palette button in dropdown
  src/cascadia/TerminalApp/Resources/en-US/Resources.resw
  src/cascadia/TerminalApp/TerminalPage.cpp
  src/cascadia/TerminalApp/TerminalPage.h
Labels: Area-User Interface, AutoMerge, Issue-Task, Needs-Second, Product-Terminal

#10384 profile.schema: add missing actions and commands keys
  doc/cascadia/profiles.schema.json
Labels: Area-Schema, Issue-Docs, Issue-Task, Needs-Second, Product-Terminal

#10373 Bugfix: serialize iterable commands
  src/cascadia/LocalTests_SettingsModel/SerializationTests.cpp
  src/cascadia/TerminalSettingsModel/ActionMap.cpp
  src/cascadia/TerminalSettingsModel/ActionMap.h
  src/cascadia/TerminalSettingsModel/ActionMapSerialization.cpp
  src/cascadia/TerminalSettingsModel/Command.cpp
Labels: Area-Settings, AutoMerge, Issue-Bug, Priority-0, Product-Terminal, Severity-Blocking, zPreview-Service-Consider

#10361 Add support for branch- and branding-based feature flagging
  .github/actions/spelling/allow/apis.txt
  .github/actions/spelling/expect/expect.txt
  build/rules/GenerateFeatureFlags.proj
  doc/feature_flags.md
  src/common.build.post.props
  src/features.xml
  tools/FeatureStagingSchema.xsd
  tools/Generate-FeatureStagingHeader.ps1
Labels: AutoMerge

#10309 Add a language switcher using PrimaryLanguageOverride
  .github/actions/spelling/allow/allow.txt
  .vscode/settings.json
  doc/cascadia/profiles.schema.json
  src/cascadia/TerminalApp/AppLogic.cpp
  src/cascadia/TerminalApp/AppLogic.h
  src/cascadia/TerminalApp/pch.h
  src/cascadia/TerminalSettingsEditor/GlobalAppearance.cpp
  src/cascadia/TerminalSettingsEditor/GlobalAppearance.h
  src/cascadia/TerminalSettingsEditor/GlobalAppearance.idl
  src/cascadia/TerminalSettingsEditor/GlobalAppearance.xaml
  src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw
  src/cascadia/TerminalSettingsEditor/pch.h
  src/cascadia/TerminalSettingsModel/AppearanceConfig.h
  src/cascadia/TerminalSettingsModel/GlobalAppSettings.cpp
  src/cascadia/TerminalSettingsModel/GlobalAppSettings.h
  src/cascadia/TerminalSettingsModel/GlobalAppSettings.idl
  src/inc/LibraryIncludes.h
  src/inc/til.h
  src/inc/til/string.h
  src/renderer/dx/precomp.h
Labels: Area-Settings, AutoMerge, Issue-Feature, Product-Terminal

#10404 Convert four INSIDE_WINDOWS blocks to til features
  .github/actions/spelling/patterns/patterns.txt
  src/features.xml
  src/host/exe/exemain.cpp
  src/host/srvinit.cpp
  src/host/ut_host/ClipboardTests.cpp
  src/host/ut_host/VtIoTests.cpp
  src/interactivity/base/EventSynthesis.cpp
  src/interactivity/win32/window.cpp
  src/renderer/dx/DxRenderer.cpp
  src/renderer/dx/ScreenPixelShader.h
  src/renderer/dx/ScreenVertexShader.h
  src/server/IoDispatchers.cpp
Labels: AutoMerge

#10390 Fix SUI race conditions when reloading settings
  src/cascadia/TerminalApp/AppLogic.cpp
  src/cascadia/TerminalApp/AppLogic.h
  src/cascadia/TerminalApp/TerminalPage.cpp
  src/cascadia/TerminalApp/TerminalPage.h
  src/cascadia/TerminalSettingsEditor/MainPage.cpp
  src/cascadia/TerminalSettingsEditor/MainPage.h
Labels: Area-Settings UI, AutoMerge, Issue-Bug, Priority-1, Product-Terminal, Severity-Crash

#10411 Force the execution policy on the til::feature powershell script
  build/rules/GenerateFeatureFlags.proj
Labels: AutoMerge

#10412 Fix edit button color in light theme
  src/cascadia/TerminalSettingsEditor/Actions.xaml
Labels: Area-Settings UI, AutoMerge, Issue-Bug, Needs-Second, Product-Terminal, zPreview-Service-Consider

#10392 Cancel the preview of nested commands when moving back on the stack.
  src/cascadia/TerminalApp/CommandPalette.cpp
Labels: Area-CmdPal, AutoMerge, Issue-Bug, Needs-Second, Priority-3, Product-Terminal

#10326 Remove CONSOLE_API_MSG::UpdateUserBufferPointers hack
  .github/actions/spelling/allow/apis.txt
  src/server/ApiMessage.cpp
  src/server/ApiMessage.h
  src/server/WaitBlock.cpp
Labels: Area-CodeHealth, Area-Server, AutoMerge, Issue-Task, Needs-Second, Product-Conhost

#10423 Don't dispatch the Toggle Command Palette action to keep the just closed Command Palette closed.
  src/cascadia/TerminalApp/CommandPalette.cpp
Labels: Area-CmdPal, AutoMerge, Issue-Bug, Needs-Second, Priority-3, Product-Terminal

#10415 Persist inbox conhost; delegate control activities to it via a pipe
  .github/actions/spelling/expect/expect.txt
  src/cascadia/CascadiaPackage/Package-Dev.appxmanifest
  src/cascadia/CascadiaPackage/Package-Pre.appxmanifest
  src/cascadia/CascadiaPackage/Package.appxmanifest
  src/host/PtySignalInputThread.cpp
  src/host/exe/CConsoleHandoff.cpp
  src/host/exe/CConsoleHandoff.h
  src/host/globals.h
  src/host/proxy/IConsoleHandoff.idl
  src/host/srvinit.cpp
  src/host/srvinit.h
  src/inc/HostSignals.hpp
  src/inc/LibraryIncludes.h
  src/interactivity/base/HostSignalInputThread.cpp
  src/interactivity/base/HostSignalInputThread.hpp
  src/interactivity/base/RemoteConsoleControl.cpp
  src/interactivity/base/RemoteConsoleControl.hpp
  src/interactivity/base/ServiceLocator.cpp
  src/interactivity/base/lib/InteractivityBase.vcxproj
  src/interactivity/base/lib/InteractivityBase.vcxproj.filters
  src/interactivity/base/sources.inc
  src/interactivity/inc/ServiceLocator.hpp
  src/interactivity/win32/ConsoleControl.hpp
  src/server/IoDispatchers.cpp
Labels: Area-DefApp, AutoMerge, Issue-Bug, Priority-1, Product-Terminal

#10434 Fix crash when unpackaged due to PrimaryLanguageOverride
  src/cascadia/ShellExtension/OpenTerminalHere.cpp
  src/cascadia/TerminalApp/AppLogic.cpp
  src/cascadia/TerminalApp/AppLogic.h
  src/cascadia/TerminalApp/Jumplist.cpp
  src/cascadia/TerminalSettingsEditor/GlobalAppearance.cpp
  src/cascadia/TerminalSettingsEditor/GlobalAppearance.h
  src/cascadia/TerminalSettingsEditor/GlobalAppearance.idl
  src/cascadia/TerminalSettingsEditor/GlobalAppearance.xaml
  src/cascadia/TerminalSettingsEditor/pch.h
  src/cascadia/TerminalSettingsModel/CascadiaSettings.cpp
  src/cascadia/TerminalSettingsModel/CascadiaSettings.h
  src/cascadia/TerminalSettingsModel/CascadiaSettingsSerialization.cpp
  src/cascadia/TerminalSettingsModel/pch.h
  src/cascadia/WinRTUtils/inc/WtExeUtils.h
Labels: Area-TerminalControl, AutoMerge, Issue-Bug, Needs-Second, Priority-1, Product-Terminal, Severity-Crash

#10341 Ensure equality when hashing default args and no args in actions
  src/cascadia/LocalTests_SettingsModel/KeyBindingsTests.cpp
  src/cascadia/TerminalSettingsModel/ActionArgs.h
  src/cascadia/TerminalSettingsModel/ActionMap.cpp
Labels: AutoMerge, Needs-Second, zPreview-Service-Consider

#10446 Localize the shell extension's menu item
  src/cascadia/ShellExtension/OpenTerminalHere.cpp
  src/cascadia/ShellExtension/dllmain.cpp
  src/cascadia/TerminalApp/Resources/en-US/Resources.resw
Labels: Area-Localization, Area-ShellExtension, AutoMerge, Issue-Task, Product-Terminal, Severity-Blocking

#10455 Update Cascadia Code to 2106.17
  consolegit2gitfilters.json
  res/Cascadia.ttf
  res/CascadiaMono.ttf
  res/README.md
  res/fonts/CascadiaCode.ttf
  res/fonts/CascadiaCodeItalic.ttf
  res/fonts/CascadiaMono.ttf
  res/fonts/CascadiaMonoItalic.ttf
  res/fonts/README.md
  src/cascadia/CascadiaPackage/Package-Pre.appxmanifest
  src/cascadia/CascadiaPackage/Package.appxmanifest
  src/cascadia/CascadiaResources.build.items
Labels: AutoMerge, Needs-Second, zPreview-Service-Consider, zStable-Service-Consider

#10465 Fix code-format and test invocation through PowerShell
  tools/OpenConsole.psm1
  tools/tests.xml
Labels: Needs-Second

#10426 Prefer FMT_COMPILE for string formatting in VtRenderer
  .github/actions/spelling/allow/microsoft.txt
  src/host/ut_host/VtRendererTests.cpp
  src/renderer/vt/VtSequences.cpp
  src/renderer/vt/state.cpp
  src/renderer/vt/vtrenderer.hpp
Labels: Area-Performance, Area-VT, AutoMerge

#10486 wpf: fix the TerminalTheme struct to marshal the same on all platforms
  src/cascadia/PublicTerminalCore/HwndTerminal.cpp
  src/cascadia/PublicTerminalCore/HwndTerminal.hpp
  src/cascadia/WpfTerminalTestNetCore/MainWindow.xaml.cs
Labels: Area-WPFControl, AutoMerge, Needs-Second

#10478 Replace PolyTextOutW with ExtTextOutW
  src/renderer/gdi/paint.cpp
Labels: Area-Rendering, AutoMerge, Impact-Compatibility, Impact-Correctness, Issue-Task, Priority-2, Product-Conhost

#10449 Fix startup race of resizing ConPTY
  src/host/ConsoleArguments.cpp
  src/host/ConsoleArguments.hpp
  src/host/PtySignalInputThread.cpp
  src/host/PtySignalInputThread.hpp
Labels: Area-Server, AutoMerge, Issue-Bug, Priority-2, Product-Conpty

#9201 Introduce DxFontInfo
  src/renderer/dx/CustomTextLayout.cpp
  src/renderer/dx/DxFontInfo.cpp
  src/renderer/dx/DxFontInfo.h
  src/renderer/dx/DxFontRenderData.cpp
  src/renderer/dx/DxFontRenderData.h
  src/renderer/dx/lib/dx.vcxproj
  src/renderer/dx/sources.inc
Labels: Area-Rendering, AutoMerge, Needs-Second, Product-Terminal

#10403 Introduce til/latch.h, til/mutex.h and til/throttled_func.h
  .github/actions/spelling/allow/apis.txt
  .github/actions/spelling/allow/microsoft.txt
  src/cascadia/TerminalControl/ControlCore.h
  src/cascadia/TerminalControl/TermControl.h
  src/cascadia/TerminalControl/TerminalControlLib.vcxproj
  src/cascadia/TerminalControl/ThrottledFunc.h
  src/cascadia/TerminalControl/pch.h
  src/cascadia/WinRTUtils/WinRTUtils.vcxproj
  src/cascadia/WinRTUtils/WinRTUtils.vcxproj.filters
  src/cascadia/WinRTUtils/inc/ThrottledFunc.h
  src/inc/til/latch.h
  src/inc/til/mutex.h
  src/inc/til/string.h
  src/inc/til/throttled_func.h
  src/til/ut_til/VisualizeControlCodesTests.cpp
  src/til/ut_til/mutex.cpp
  src/til/ut_til/string.cpp
  src/til/ut_til/throttled_func.cpp
  src/til/ut_til/til.unit.tests.vcxproj
  src/til/ut_til/til.unit.tests.vcxproj.filters
Labels: AutoMerge, Issue-Feature, Product-Terminal

#10489 Add Settings UI enum to json schema
  doc/cascadia/profiles.schema.json
Labels: zPreview-Service-Consider, zStable-Service-Consider

#10494 Replicate winrt::make<> changes in ScratchIslandApp SampleAppLib
  scratch/ScratchIslandApp/SampleApp/App.base.h
Labels: Area-CodeHealth, AutoMerge, Issue-Task

#10499 Update WindowExe.manifest
  scratch/ScratchIslandApp/WindowExe/WindowExe.manifest
Labels: Area-CodeHealth, AutoMerge, Issue-Bug

#10447 Allow closing tabs by index
  doc/cascadia/profiles.schema.json
  src/cascadia/TerminalApp/AppActionHandlers.cpp
  src/cascadia/TerminalApp/TabManagement.cpp
  src/cascadia/TerminalApp/TerminalPage.h
  src/cascadia/TerminalSettingsModel/ActionAndArgs.cpp
  src/cascadia/TerminalSettingsModel/ActionArgs.cpp
  src/cascadia/TerminalSettingsModel/ActionArgs.h
  src/cascadia/TerminalSettingsModel/ActionArgs.idl
  src/cascadia/TerminalSettingsModel/AllShortcutActions.h
  src/cascadia/TerminalSettingsModel/Resources/en-US/Resources.resw
Labels: Area-Settings, AutoMerge, Issue-Task, Needs-Second, Product-Terminal

#10394 Throttle cursor redrawing in outputStream.cpp
  src/host/outputStream.cpp
Labels: AutoMerge

#10471 Defer _run substr operation in StateMachine::ProcessString
  src/terminal/parser/stateMachine.cpp
  src/terminal/parser/stateMachine.hpp
Labels: Area-Performance, AutoMerge

#10513 Introduce a basic ApplicationState class
  .github/actions/spelling/expect/expect.txt
  doc/cascadia/AddASetting.md
  src/cascadia/TerminalApp/AppLogic.cpp
  src/cascadia/TerminalApp/AppLogic.h
  src/cascadia/TerminalSettingsModel/ApplicationState.cpp
  src/cascadia/TerminalSettingsModel/ApplicationState.h
  src/cascadia/TerminalSettingsModel/ApplicationState.idl
  src/cascadia/TerminalSettingsModel/CascadiaSettings.h
  src/cascadia/TerminalSettingsModel/CascadiaSettingsSerialization.cpp
  src/cascadia/TerminalSettingsModel/FileUtils.cpp
  src/cascadia/TerminalSettingsModel/FileUtils.h
  src/cascadia/TerminalSettingsModel/Microsoft.Terminal.Settings.ModelLib.vcxproj
Labels: Area-Settings, AutoMerge, Issue-Feature, Product-Terminal

#10533 Improve parser performance by reducing tracing overhead
  src/terminal/parser/tracing.cpp
  src/terminal/parser/tracing.hpp
Labels: Area-Performance, AutoMerge, Product-Conpty

#10535 Advice users to relaunch after changing the language
  src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw
Labels: Area-Settings UI, Product-Terminal
