Repository microsoft/terminal, pull requests merged in 2021-11, with the labels that each got.

#11670 Fix the cmdpal moving the infobar down
  src/cascadia/TerminalApp/TerminalPage.xaml
Labels: Area-User Interface, Product-Terminal, AutoMerge, Severity-Blocking, Needs-Second, Priority-0

#11658 Default all G-sets to ASCII unless ISO-2022 is requested
  src/terminal/adapter/terminalOutput.cpp
Labels: Product-Conhost, Area-VT, Issue-Bug, Product-Terminal, AutoMerge, Issue-Task, Priority-2

#11416 Use X-macros to simplify new setting creation in SettingsModel
  src/cascadia/TerminalSettingsModel/AppearanceConfig.cpp
  src/cascadia/TerminalSettingsModel/AppearanceConfig.h
  src/cascadia/TerminalSettingsModel/FontConfig.cpp
  src/cascadia/TerminalSettingsModel/FontConfig.h
  src/cascadia/TerminalSettingsModel/GlobalAppSettings.cpp
  src/cascadia/TerminalSettingsModel/GlobalAppSettings.h
  src/cascadia/TerminalSettingsModel/MTSMSettings.h
  src/cascadia/TerminalSettingsModel/Microsoft.Terminal.Settings.ModelLib.vcxproj
  src/cascadia/TerminalSettingsModel/Microsoft.Terminal.Settings.ModelLib.vcxproj.filters
  src/cascadia/TerminalSettingsModel/Profile.cpp
  src/cascadia/TerminalSettingsModel/Profile.h
Labels: AutoMerge, Area-CodeHealth

#11644 Add trimPaste to the schema, too
  doc/cascadia/profiles.schema.json
Labels: Issue-Docs, Area-Settings, Product-Terminal, AutoMerge

#11667 Make sure to format the error message with an UNSIGNED int
  src/cascadia/TerminalConnection/ConptyConnection.cpp
Labels: Issue-Bug, Area-User Interface, Area-TerminalConnection, Product-Terminal, AutoMerge, Needs-Second, Priority-3

#11404 Add settings entry into titlebar context menu
  .github/actions/spelling/allow/apis.txt
  src/cascadia/TerminalApp/AppLogic.cpp
  src/cascadia/TerminalApp/AppLogic.h
  src/cascadia/TerminalApp/AppLogic.idl
  src/cascadia/TerminalApp/TerminalPage.cpp
  src/cascadia/TerminalApp/TerminalPage.h
  src/cascadia/WindowsTerminal/AppHost.cpp
  src/cascadia/WindowsTerminal/AppHost.h
  src/cascadia/WindowsTerminal/IslandWindow.cpp
  src/cascadia/WindowsTerminal/IslandWindow.h
Labels: Area-User Interface, Product-Terminal, AutoMerge, Issue-Task, Needs-Second

#11602 Standardize the color table order
  src/buffer/out/TextAttribute.cpp
  src/buffer/out/TextAttribute.hpp
  src/buffer/out/TextColor.cpp
  src/buffer/out/TextColor.h
  src/buffer/out/ut_textbuffer/TextAttributeTests.cpp
  src/cascadia/LocalTests_SettingsModel/ColorSchemeTests.cpp
  src/cascadia/TerminalCore/Terminal.cpp
  src/cascadia/TerminalCore/TerminalDispatchGraphics.cpp
  src/cascadia/UnitTests_TerminalCore/ConptyRoundtripTests.cpp
  src/host/conattrs.cpp
  src/host/consoleInformation.cpp
  src/host/getset.cpp
  src/host/host-common.vcxitems
  src/host/lib/hostlib.vcxproj.filters
  src/host/registry.cpp
  src/host/renderData.cpp
  src/host/renderData.hpp
  src/host/screenInfo.cpp
  src/host/selectionInput.cpp
  src/host/server.h
  src/host/settings.cpp
  src/host/settings.hpp
  src/host/sources.inc
  src/host/ut_host/ScreenBufferTests.cpp
  src/host/ut_host/TextBufferTests.cpp
  src/host/ut_host/VtRendererTests.cpp
  src/inc/conattrs.hpp
  src/interactivity/win32/Clipboard.cpp
  src/interactivity/win32/menu.cpp
  src/renderer/vt/VtSequences.cpp
  src/renderer/vt/paint.cpp
  src/renderer/vt/vtrenderer.hpp
  src/terminal/adapter/adaptDispatch.cpp
  src/terminal/adapter/adaptDispatchGraphics.cpp
  src/terminal/adapter/ut_adapter/adapterTest.cpp
  src/types/colorTable.cpp
  src/types/inc/colorTable.hpp
  src/types/ut_types/UtilsTests.cpp
Labels: Product-Conhost, Area-Server, Area-VT, Product-Terminal, AutoMerge, Issue-Task

#11305 Unify splitting panes and creating new tabs
  src/cascadia/LocalTests_TerminalApp/TabTests.cpp
  src/cascadia/TerminalApp/AppActionHandlers.cpp
  src/cascadia/TerminalApp/Pane.cpp
  src/cascadia/TerminalApp/Pane.h
  src/cascadia/TerminalApp/TabManagement.cpp
  src/cascadia/TerminalApp/TerminalPage.cpp
  src/cascadia/TerminalApp/TerminalPage.h
  src/cascadia/TerminalApp/TerminalTab.cpp
  src/cascadia/TerminalApp/TerminalTab.h
Labels: Issue-Bug, Product-Terminal, AutoMerge, Area-CodeHealth, Priority-3

#11671 README.md: HTTP => HTTPS
  README.md
Labels: Issue-Docs, AutoMerge

#11653 Fix missing window border when use "win+arrow down" in fullscreen mode in Terminal
  src/cascadia/TerminalApp/AppLogic.cpp
  src/cascadia/TerminalApp/AppLogic.h
  src/cascadia/TerminalApp/AppLogic.idl
  src/cascadia/TerminalApp/TerminalPage.cpp
  src/cascadia/TerminalApp/TerminalPage.h
  src/cascadia/WindowsTerminal/AppHost.cpp
  src/cascadia/WindowsTerminal/IslandWindow.cpp
  src/cascadia/WindowsTerminal/IslandWindow.h
Labels: Product-Conhost, Issue-Bug, Area-User Interface, Product-Terminal, AutoMerge, Needs-Second, Priority-3

#11691 fix build error at 74d21af
  src/cascadia/WindowsTerminal/IslandWindow.cpp
Labels: AutoMerge, Needs-Second

#11674 Don't crash if we fail to BeginBufferedPaint
  src/cascadia/WindowsTerminal/NonClientIslandWindow.cpp
Labels: AutoMerge

#11657 doc: Fix typo in #885 - Terminal Settings Model.md
  doc/specs/#885 - Terminal Settings Model/#885 - Terminal Settings Model.md
Labels: Issue-Docs, Needs-Second

#11727 Fix a conhost binary size regression due to fmt
  src/terminal/adapter/adaptDispatch.cpp
Labels: Product-Conhost, Area-VT, AutoMerge, Needs-Second, Area-Quality, zInbox Bug

#11625 Automatically convert paths dropped on WSL instances
  .github/actions/spelling/allow/allow.txt
  src/cascadia/TerminalControl/IControlSettings.idl
  src/cascadia/TerminalControl/TermControl.cpp
  src/cascadia/TerminalSettingsModel/TerminalSettings.cpp
  src/cascadia/TerminalSettingsModel/TerminalSettings.h
  src/cascadia/UnitTests_Control/MockControlSettings.h
Labels: Issue-Feature, Product-Conhost, Area-Interaction, AutoMerge, Needs-Second

#11623 Introduce AtlasEngine - A new text rendering prototype
  .github/actions/spelling/allow/allow.txt
  .github/actions/spelling/excludes.txt
  OpenConsole.sln
  src/cascadia/PublicTerminalCore/PublicTerminalCore.vcxproj
  src/cascadia/TerminalControl/ControlCore.cpp
  src/cascadia/TerminalControl/ControlCore.h
  src/cascadia/TerminalControl/ControlInteractivity.h
  src/cascadia/TerminalControl/IControlSettings.idl
  src/cascadia/TerminalControl/TermControl.cpp
  src/cascadia/TerminalControl/TermControl.h
  src/cascadia/TerminalControl/TerminalControlLib.vcxproj
  src/cascadia/TerminalCore/lib/terminalcore-lib.vcxproj
  src/cascadia/TerminalSettingsEditor/Profiles.cpp
  src/cascadia/TerminalSettingsEditor/Profiles.h
  src/cascadia/TerminalSettingsEditor/Profiles.idl
  src/cascadia/TerminalSettingsEditor/Profiles.xaml
  src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw
  src/cascadia/TerminalSettingsModel/MTSMSettings.h
  src/cascadia/TerminalSettingsModel/Profile.idl
  src/cascadia/TerminalSettingsModel/TerminalSettings.cpp
  src/cascadia/TerminalSettingsModel/TerminalSettings.h
  src/cascadia/UnitTests_Control/MockControlSettings.h
  src/features.xml
  src/host/exe/Host.EXE.vcxproj
  src/host/ft_fuzzer/Host.FuzzWrapper.vcxproj
  src/host/ft_host/CJK_DbcsTests.cpp
  src/host/globals.h
  src/host/settings.cpp
  src/host/settings.hpp
  src/host/ut_host/Host.UnitTests.vcxproj
  src/interactivity/win32/lib/win32.LIB.vcxproj
  src/interactivity/win32/ut_interactivity_win32/Interactivity.Win32.UnitTests.vcxproj
  src/interactivity/win32/ut_interactivity_win32/UiaTextRangeTests.cpp
  src/interactivity/win32/window.cpp
  src/propslib/RegistrySerialization.cpp
  src/renderer/atlas/AtlasEngine.api.cpp
  src/renderer/atlas/AtlasEngine.cpp
  src/renderer/atlas/AtlasEngine.h
  src/renderer/atlas/AtlasEngine.r.cpp
  src/renderer/atlas/atlas.vcxproj
  src/renderer/atlas/pch.cpp
  src/renderer/atlas/pch.h
  src/renderer/atlas/shader_ps.hlsl
  src/renderer/atlas/shader_vs.hlsl
  src/renderer/base/RenderEngineBase.cpp
  src/renderer/base/thread.cpp
  src/renderer/base/thread.hpp
  src/renderer/dx/CustomTextLayout.cpp
  src/renderer/dx/CustomTextRenderer.cpp
  src/renderer/dx/DxRenderer.cpp
  src/renderer/dx/DxRenderer.hpp
  src/renderer/inc/IRenderEngine.hpp
  src/renderer/uia/UiaRenderer.cpp
  src/renderer/uia/UiaRenderer.hpp
  src/renderer/vt/vtrenderer.hpp
  src/renderer/wddmcon/WddmConRenderer.hpp
Labels: Product-Conhost, Area-Rendering, Product-Terminal, AutoMerge

#11222 Add a file for storing elevated-only state
  .github/actions/spelling/allow/allow.txt
  .github/actions/spelling/allow/apis.txt
  .github/actions/spelling/allow/names.txt
  src/cascadia/TerminalApp/AppLogic.cpp
  src/cascadia/TerminalApp/TerminalPage.cpp
  src/cascadia/TerminalSettingsModel/ApplicationState.cpp
  src/cascadia/TerminalSettingsModel/ApplicationState.h
  src/cascadia/TerminalSettingsModel/ApplicationState.idl
  src/cascadia/TerminalSettingsModel/FileUtils.cpp
  src/cascadia/TerminalSettingsModel/FileUtils.h
  src/cascadia/TerminalSettingsModel/JsonUtils.h
  src/cascadia/TerminalSettingsModel/pch.h
  src/cascadia/WindowsTerminal/AppHost.cpp
  src/types/inc/utils.hpp
  src/types/utils.cpp
Labels: Area-Settings, Product-Terminal, AutoMerge, Issue-Task, Needs-Second

#11528 Separate terminal version and Windows version in issue template
  .github/ISSUE_TEMPLATE/Bug_Report.yml
Labels: Product-Meta

#11692 Fix missing window border when use "win+arrow down" in fullscreen mode in Conhost
  src/interactivity/win32/windowproc.cpp
Labels: Product-Conhost, Issue-Bug, Area-User Interface, Product-Terminal, AutoMerge, Needs-Second, Priority-3

#11764 Use nearby fonts for font fallback
  .github/actions/spelling/allow/allow.txt
  src/cascadia/TerminalSettingsEditor/Profiles.cpp
  src/cascadia/TerminalSettingsEditor/pch.h
  src/renderer/dx/DxFontInfo.cpp
  src/renderer/dx/DxFontInfo.h
  src/renderer/dx/DxFontRenderData.cpp
  src/renderer/dx/DxFontRenderData.h
  src/renderer/dx/lib/dx.vcxproj
  src/renderer/dx/lib/dx.vcxproj.filters
Labels: Area-Fonts, Issue-Bug, Product-Terminal, AutoMerge, Priority-1, Priority-3, zStable-Service-Consider, zPreview-Service-Consider

#11690 Disable the acceptance of C1 control codes by default
  .github/actions/spelling/expect/expect.txt
  src/cascadia/TerminalCore/Terminal.cpp
  src/cascadia/UnitTests_TerminalCore/TerminalApiTest.cpp
  src/host/outputStream.cpp
  src/host/outputStream.hpp
  src/host/ut_host/ScreenBufferTests.cpp
  src/terminal/adapter/ITermDispatch.hpp
  src/terminal/adapter/adaptDispatch.cpp
  src/terminal/adapter/adaptDispatch.hpp
  src/terminal/adapter/conGetSet.hpp
  src/terminal/adapter/termDispatch.hpp
  src/terminal/adapter/ut_adapter/adapterTest.cpp
  src/terminal/parser/OutputStateMachineEngine.cpp
  src/terminal/parser/OutputStateMachineEngine.hpp
  src/terminal/parser/stateMachine.cpp
  src/terminal/parser/stateMachine.hpp
  src/terminal/parser/telemetry.cpp
  src/terminal/parser/telemetry.hpp
  src/terminal/parser/ut_parser/OutputEngineTest.cpp
Labels: Product-Conhost, Area-Output, Issue-Bug, AutoMerge, Needs-Second

#11725 Introduce new TIL string helpers, teach older ones to use wmemcmp
  src/inc/operators.hpp
  src/inc/til/string.h
Labels: AutoMerge, Area-CodeHealth

#11728 Upgrade to Windows SDK 22000
  .vsconfig
  build/scripts/Create-AppxBundle.ps1
  build/scripts/Test-WindowsTerminalPackage.ps1
  doc/cascadia/Unittesting-CppWinRT-Xaml.md
  samples/ConPTY/EchoCon/EchoCon/EchoCon.vcxproj
  scratch/ScratchIslandApp/Package/Package.appxmanifest
  src/cascadia/CascadiaPackage/Package-Dev.appxmanifest
  src/cascadia/CascadiaPackage/Package-Pre.appxmanifest
  src/cascadia/CascadiaPackage/Package.appxmanifest
  src/cascadia/LocalTests_TerminalApp/TerminalApp.LocalTests.AppxManifest.prototype.xml
  src/cascadia/LocalTests_TerminalApp/TestHostApp/Package.appxmanifest
  src/cascadia/WindowsTerminalUniversal/Package-Dev.appxmanifest
  src/cascadia/WindowsTerminalUniversal/Package.appxmanifest
  src/cascadia/ut_app/TerminalApp.Unit.Tests.AppxManifest.xml
  src/common.build.pre.props
  src/tools/MonarchPeasantPackage/MonarchPeasantPackage.wapproj
  src/wap-common.build.pre.props
Labels: Area-Build, AutoMerge, Product-Meta

#11806 Fixes the wapproj fast-up-to-date check
  scratch/ScratchIslandApp/WindowExe/WindowExe.vcxproj
  src/cascadia/CascadiaPackage/CascadiaPackage.wapproj
  src/cascadia/TerminalAzBridge/TerminalAzBridge.vcxproj
  src/cascadia/WindowsTerminal/WindowsTerminal.vcxproj
Labels: Area-Build, AutoMerge, Product-Meta

#11804 Fix for missing CopyComplete files in TerminalConnection.vcxproj
  src/cascadia/TerminalConnection/TerminalConnection.vcxproj
Labels: Area-Build, AutoMerge, Product-Meta

#11803 Prefer Preview VS builds always; use any existing msbuild if it's on the path
  tools/razzle.cmd
Labels: Issue-Bug, Area-Build, AutoMerge, Product-Meta, Issue-Task

#11802 Add some details about working on assigned issues
  .github/actions/spelling/patterns/patterns.txt
  CONTRIBUTING.md
Labels: Issue-Docs, Area-Build, AutoMerge, Product-Meta

#11805 Fix missing .xaml references
  src/cascadia/TerminalApp/TerminalAppLib.vcxproj
  src/cascadia/TerminalSettingsModel/Microsoft.Terminal.Settings.ModelLib.vcxproj
  src/cascadia/TerminalSettingsModel/dll/Microsoft.Terminal.Settings.Model.vcxproj
Labels: Area-Build, AutoMerge, Product-Meta

#11807 Wrap these commands with quotes
  build/rules/GenerateFeatureFlags.proj
  src/host/ft_uia/Host.Tests.UIA.csproj
  src/propsheet/propsheet.vcxproj
Labels: Issue-Bug, Area-Build, AutoMerge, Product-Meta

#11784 Consolidate the color palette APIs
  .github/actions/spelling/allow/apis.txt
  src/buffer/out/TextAttribute.cpp
  src/buffer/out/TextAttribute.hpp
  src/buffer/out/TextColor.cpp
  src/buffer/out/TextColor.h
  src/buffer/out/cursor.cpp
  src/buffer/out/cursor.h
  src/buffer/out/ut_textbuffer/TextAttributeTests.cpp
  src/buffer/out/ut_textbuffer/TextColorTests.cpp
  src/cascadia/PublicTerminalCore/HwndTerminal.cpp
  src/cascadia/TerminalControl/ControlCore.cpp
  src/cascadia/TerminalCore/ITerminalApi.hpp
  src/cascadia/TerminalCore/Terminal.cpp
  src/cascadia/TerminalCore/Terminal.hpp
  src/cascadia/TerminalCore/TerminalApi.cpp
  src/cascadia/TerminalCore/TerminalDispatch.cpp
  src/cascadia/TerminalCore/terminalrenderdata.cpp
  src/cascadia/UnitTests_TerminalCore/ConptyRoundtripTests.cpp
  src/cascadia/UnitTests_TerminalCore/TerminalApiTest.cpp
  src/host/consoleInformation.cpp
  src/host/getset.cpp
  src/host/getset.h
  src/host/outputStream.cpp
  src/host/outputStream.hpp
  src/host/renderData.cpp
  src/host/renderData.hpp
  src/host/screenInfo.cpp
  src/host/screenInfo.hpp
  src/host/selection.cpp
  src/host/selection.hpp
  src/host/selectionState.cpp
  src/host/server.h
  src/host/settings.cpp
  src/host/settings.hpp
  src/host/ut_host/ConptyOutputTests.cpp
  src/host/ut_host/ScreenBufferTests.cpp
  src/inc/conattrs.hpp
  src/interactivity/win32/Clipboard.cpp
  src/interactivity/win32/menu.cpp
  src/propslib/RegistrySerialization.cpp
  src/terminal/adapter/adaptDispatch.cpp
  src/terminal/adapter/conGetSet.hpp
  src/terminal/adapter/ut_adapter/adapterTest.cpp
Labels: Issue-Feature, Product-Conhost, Area-Server, AutoMerge, Area-CodeHealth

#11493 Improve performance and binary size of til::enumset
  src/inc/til/enumset.h
  src/terminal/input/mouseInput.cpp
  src/terminal/input/terminalInput.cpp
  src/terminal/input/terminalInput.hpp
  src/terminal/parser/stateMachine.cpp
  src/terminal/parser/stateMachine.hpp
  src/til/ut_til/EnumSetTests.cpp
Labels: AutoMerge

#11820 Rename IInheritable::InsertParent to improve clarity of intent
  src/cascadia/TerminalSettingsModel/CascadiaSettings.cpp
  src/cascadia/TerminalSettingsModel/CascadiaSettingsSerialization.cpp
  src/cascadia/TerminalSettingsModel/GlobalAppSettings.cpp
  src/cascadia/TerminalSettingsModel/IInheritable.h
  src/cascadia/TerminalSettingsModel/Profile.cpp
  src/cascadia/TerminalSettingsModel/TerminalSettings.cpp
Labels: Area-Settings, Product-Terminal, AutoMerge, Area-CodeHealth

#11680 Add snap-layouts support to the Terminal
  .github/actions/spelling/allow/apis.txt
  src/cascadia/TerminalApp/MinMaxCloseControl.cpp
  src/cascadia/TerminalApp/MinMaxCloseControl.h
  src/cascadia/TerminalApp/MinMaxCloseControl.idl
  src/cascadia/TerminalApp/MinMaxCloseControl.xaml
  src/cascadia/TerminalApp/Resources/en-US/Resources.resw
  src/cascadia/TerminalApp/TitlebarControl.cpp
  src/cascadia/TerminalApp/TitlebarControl.h
  src/cascadia/TerminalApp/TitlebarControl.idl
  src/cascadia/WindowsTerminal/NonClientIslandWindow.cpp
  src/cascadia/WindowsTerminal/NonClientIslandWindow.h
Labels: Issue-Bug, Area-User Interface, Product-Terminal, AutoMerge, Issue-Task, Priority-3
