Repository microsoft/terminal, pull requests merged in 2022-12, with the labels that each got.

#14341 Implement the rest of the FTCS marks
  src/cascadia/TerminalControl/ControlCore.cpp
  src/cascadia/TerminalCore/Terminal.cpp
  src/cascadia/TerminalCore/Terminal.hpp
  src/cascadia/TerminalCore/TerminalApi.cpp
  src/host/outputStream.cpp
  src/host/outputStream.hpp
  src/terminal/adapter/DispatchTypes.hpp
  src/terminal/adapter/ITerminalApi.hpp
  src/terminal/adapter/adaptDispatch.cpp
  src/terminal/adapter/ut_adapter/adapterTest.cpp
Labels: Area-VT, Area-TerminalControl, Product-Terminal, AutoMerge, Needs-Second

#14396 Clean up CodepointWidthDetector
  src/buffer/out/OutputCellIterator.cpp
  src/buffer/out/OutputCellIterator.hpp
  src/cascadia/PublicTerminalCore/HwndTerminal.cpp
  src/cascadia/PublicTerminalCore/HwndTerminal.hpp
  src/cascadia/TerminalControl/ControlCore.cpp
  src/host/ut_host/CodepointWidthDetectorTests.cpp
  src/interactivity/base/EventSynthesis.cpp
  src/types/CodepointWidthDetector.cpp
  src/types/GlyphWidth.cpp
  src/types/convert.cpp
  src/types/inc/CodepointWidthDetector.hpp
  src/types/inc/GlyphWidth.hpp
  src/types/inc/convert.hpp
  tools/Generate-CodepointWidthsFromUCD.ps1
Labels: AutoMerge, Area-CodeHealth

#14463 Fix a potential deadlock for PtySignal::SetParent
  src/host/PtySignalInputThread.cpp
  src/host/PtySignalInputThread.hpp
Labels: Product-Conpty, Issue-Bug, AutoMerge, Priority-1, Area-Remoting

#14421 Refactor ConsoleProcessList
  src/host/ft_fuzzer/fuzzmain.cpp
  src/host/input.cpp
  src/interactivity/win32/windowio.cpp
  src/server/ApiDispatchersInternal.cpp
  src/server/IoDispatchers.cpp
  src/server/ProcessHandle.h
  src/server/ProcessList.cpp
  src/server/ProcessList.h
Labels: AutoMerge, Area-CodeHealth

#14427 Merge IBaseData, IRenderData and IUiaData
  src/buffer/out/search.cpp
  src/buffer/out/search.h
  src/cascadia/PublicTerminalCore/HwndTerminal.cpp
  src/cascadia/PublicTerminalCore/HwndTerminal.hpp
  src/cascadia/TerminalControl/ControlCore.cpp
  src/cascadia/TerminalControl/ControlCore.h
  src/cascadia/TerminalControl/ControlInteractivity.cpp
  src/cascadia/TerminalControl/ControlInteractivity.h
  src/cascadia/TerminalControl/InteractivityAutomationPeer.cpp
  src/cascadia/TerminalCore/Terminal.hpp
  src/host/renderData.cpp
  src/host/renderData.hpp
  src/host/ut_host/VtIoTests.cpp
  src/interactivity/win32/screenInfoUiaProvider.cpp
  src/interactivity/win32/screenInfoUiaProvider.hpp
  src/interactivity/win32/uiaTextRange.cpp
  src/interactivity/win32/uiaTextRange.hpp
  src/interactivity/win32/ut_interactivity_win32/UiaTextRangeTests.cpp
  src/interactivity/win32/windowUiaProvider.cpp
  src/renderer/inc/IRenderData.hpp
  src/types/IBaseData.h
  src/types/IUiaData.h
  src/types/ScreenInfoUiaProviderBase.cpp
  src/types/ScreenInfoUiaProviderBase.h
  src/types/TermControlUiaProvider.cpp
  src/types/TermControlUiaProvider.hpp
  src/types/TermControlUiaTextRange.cpp
  src/types/TermControlUiaTextRange.hpp
  src/types/UiaTextRangeBase.cpp
  src/types/UiaTextRangeBase.hpp
  src/types/lib/types.vcxproj
  src/types/lib/types.vcxproj.filters
Labels: AutoMerge, Area-CodeHealth

#14478 Remove "Requires relaunch" from "use acrylic in tab row" text
  src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw
Labels: Issue-Bug, Product-Terminal, AutoMerge, Priority-3, zStable-Service-Queued-1.12, zPreview-Service-Queued-1.13, Area-Settings UI

#14064 Add support for switching the scheme based on the app's theme
  doc/cascadia/profiles.schema.json
  src/cascadia/LocalTests_SettingsModel/ColorSchemeTests.cpp
  src/cascadia/LocalTests_SettingsModel/DeserializationTests.cpp
  src/cascadia/LocalTests_SettingsModel/SerializationTests.cpp
  src/cascadia/LocalTests_SettingsModel/TerminalSettingsTests.cpp
  src/cascadia/LocalTests_SettingsModel/pch.h
  src/cascadia/TerminalApp/App.cpp
  src/cascadia/TerminalApp/AppLogic.cpp
  src/cascadia/TerminalApp/AppLogic.h
  src/cascadia/TerminalApp/AppLogic.idl
  src/cascadia/TerminalSettingsEditor/Appearances.cpp
  src/cascadia/TerminalSettingsEditor/Appearances.h
  src/cascadia/TerminalSettingsEditor/Appearances.idl
  src/cascadia/TerminalSettingsEditor/Appearances.xaml
  src/cascadia/TerminalSettingsEditor/ColorSchemeViewModel.cpp
  src/cascadia/TerminalSettingsEditor/ColorSchemesPageViewModel.cpp
  src/cascadia/TerminalSettingsModel/AppearanceConfig.cpp
  src/cascadia/TerminalSettingsModel/AppearanceConfig.h
  src/cascadia/TerminalSettingsModel/AzureCloudShellGenerator.cpp
  src/cascadia/TerminalSettingsModel/CascadiaSettings.cpp
  src/cascadia/TerminalSettingsModel/CascadiaSettings.h
  src/cascadia/TerminalSettingsModel/CascadiaSettings.idl
  src/cascadia/TerminalSettingsModel/IAppearanceConfig.idl
  src/cascadia/TerminalSettingsModel/MTSMSettings.h
  src/cascadia/TerminalSettingsModel/PowershellCoreProfileGenerator.cpp
  src/cascadia/TerminalSettingsModel/TerminalSettings.cpp
  src/cascadia/TerminalSettingsModel/TerminalSettings.h
  src/cascadia/TerminalSettingsModel/WslDistroGenerator.cpp
  src/cascadia/TerminalSettingsModel/pch.h
  src/cascadia/WindowsTerminal/AppHost.cpp
  src/cascadia/WindowsTerminal/IslandWindow.cpp
  src/cascadia/WindowsTerminal/IslandWindow.h
  src/cascadia/inc/ControlProperties.h
Labels: Issue-Feature, Issue-Bug, Area-User Interface, Area-Settings, Needs-Author-Feedback, Product-Terminal, AutoMerge, Area-CodeHealth

#14060 When the terminal has exited, ctrl+D to close pane, Enter to restart terminal
  .github/actions/spelling/allow/allow.txt
  src/cascadia/TerminalApp/Pane.cpp
  src/cascadia/TerminalApp/Pane.h
  src/cascadia/TerminalConnection/ConnectionStateHolder.h
  src/cascadia/TerminalConnection/ConptyConnection.cpp
  src/cascadia/TerminalConnection/ConptyConnection.h
  src/cascadia/TerminalConnection/Resources/en-US/Resources.resw
  src/cascadia/TerminalControl/ControlCore.cpp
  src/cascadia/TerminalControl/ControlCore.h
  src/cascadia/TerminalControl/ControlCore.idl
  src/cascadia/TerminalControl/TermControl.h
  src/cascadia/TerminalControl/TermControl.idl
Labels: Area-TerminalControl, Area-Settings, Product-Terminal, AutoMerge, Issue-Task, zBugBash-Consider

#14515 Added null check before rendering a string from the terminal connection
  src/cascadia/WpfTerminalControl/TerminalContainer.cs
Labels: AutoMerge

#14518 Fix setting launch position in the Settings UI not working
  src/cascadia/TerminalSettingsEditor/LaunchViewModel.cpp
Labels: Issue-Bug, Product-Terminal, AutoMerge, Severity-Blocking, Priority-1, Area-Settings UI, zBugBash-Consider

#14467 Harden against resizing down to 0 columns/rows
  src/buffer/out/textBuffer.cpp
  src/cascadia/PublicTerminalCore/HwndTerminal.cpp
Labels: Area-Output, Issue-Bug, Severity-Crash, Product-Terminal, AutoMerge, Needs-Second, Priority-1, zBugBash-Consider

#14481 Enable vintage opacity on Windows 10
  src/cascadia/TerminalControl/ControlCore.cpp
  src/cascadia/TerminalSettingsEditor/ProfileViewModel.cpp
  src/cascadia/TerminalSettingsEditor/ProfileViewModel.h
  src/cascadia/UnitTests_Control/ControlCoreTests.cpp
  src/cascadia/UnitTests_Control/ControlInteractivityTests.cpp
Labels: AutoMerge, Needs-Second, zBugBash-Consider

#14473 reword en-US value for confirmCloseAllTabs
  src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw
Labels: Issue-Bug, Product-Terminal, AutoMerge, Priority-3, Area-Settings UI, zBugBash-Consider

#14402 Add support for DEC macro operations
  .github/actions/spelling/expect/expect.txt
  src/terminal/adapter/DispatchTypes.hpp
  src/terminal/adapter/ITermDispatch.hpp
  src/terminal/adapter/MacroBuffer.cpp
  src/terminal/adapter/MacroBuffer.hpp
  src/terminal/adapter/adaptDispatch.cpp
  src/terminal/adapter/adaptDispatch.hpp
  src/terminal/adapter/lib/adapter.vcxproj
  src/terminal/adapter/lib/adapter.vcxproj.filters
  src/terminal/adapter/sources.inc
  src/terminal/adapter/termDispatch.hpp
  src/terminal/adapter/ut_adapter/adapterTest.cpp
  src/terminal/parser/OutputStateMachineEngine.cpp
  src/terminal/parser/OutputStateMachineEngine.hpp
  src/terminal/parser/stateMachine.cpp
  src/terminal/parser/stateMachine.hpp
  src/terminal/parser/telemetry.cpp
  src/terminal/parser/telemetry.hpp
  src/terminal/parser/ut_parser/OutputEngineTest.cpp
Labels: Area-VT, AutoMerge, Issue-Task, zBugBash-Consider

#14486 Make the Pane inactive border respect the `theme.window.applicationTheme`
  src/cascadia/TerminalApp/App.xaml
  src/cascadia/TerminalApp/Pane.cpp
  src/cascadia/TerminalApp/Pane.h
  src/cascadia/TerminalApp/TerminalPage.cpp
Labels: Issue-Bug, Area-User Interface, Product-Terminal, AutoMerge, Needs-Second, Priority-3, zBugBash-Consider

#14042 Dynamically generate profiles from hosts in OpenSSH config files
  .github/actions/spelling/allow/names.txt
  src/cascadia/TerminalSettingsModel/CascadiaSettingsSerialization.cpp
  src/cascadia/TerminalSettingsModel/Microsoft.Terminal.Settings.ModelLib.vcxproj
  src/cascadia/TerminalSettingsModel/Microsoft.Terminal.Settings.ModelLib.vcxproj.filters
  src/cascadia/TerminalSettingsModel/SshHostGenerator.cpp
  src/cascadia/TerminalSettingsModel/SshHostGenerator.h
  src/features.xml
Labels: Issue-Feature, Area-Extensibility, Area-Settings, Product-Terminal, AutoMerge, zBugBash-Consider

#13763 New Tab Menu Customization
  .github/actions/spelling/allow/names.txt
  .github/actions/spelling/expect/expect.txt
  doc/cascadia/profiles.schema.json
  src/cascadia/TerminalApp/AppLogic.cpp
  src/cascadia/TerminalApp/Resources/en-US/Resources.resw
  src/cascadia/TerminalApp/TerminalPage.cpp
  src/cascadia/TerminalApp/TerminalPage.h
  src/cascadia/TerminalSettingsModel/CascadiaSettings.h
  src/cascadia/TerminalSettingsModel/CascadiaSettingsSerialization.cpp
  src/cascadia/TerminalSettingsModel/FolderEntry.cpp
  src/cascadia/TerminalSettingsModel/FolderEntry.h
  src/cascadia/TerminalSettingsModel/GlobalAppSettings.h
  src/cascadia/TerminalSettingsModel/GlobalAppSettings.idl
  src/cascadia/TerminalSettingsModel/MTSMSettings.h
  src/cascadia/TerminalSettingsModel/MatchProfilesEntry.cpp
  src/cascadia/TerminalSettingsModel/MatchProfilesEntry.h
  src/cascadia/TerminalSettingsModel/Microsoft.Terminal.Settings.ModelLib.vcxproj
  src/cascadia/TerminalSettingsModel/Microsoft.Terminal.Settings.ModelLib.vcxproj.filters
  src/cascadia/TerminalSettingsModel/NewTabMenuEntry.cpp
  src/cascadia/TerminalSettingsModel/NewTabMenuEntry.h
  src/cascadia/TerminalSettingsModel/NewTabMenuEntry.idl
  src/cascadia/TerminalSettingsModel/ProfileCollectionEntry.cpp
  src/cascadia/TerminalSettingsModel/ProfileCollectionEntry.h
  src/cascadia/TerminalSettingsModel/ProfileEntry.cpp
  src/cascadia/TerminalSettingsModel/ProfileEntry.h
  src/cascadia/TerminalSettingsModel/RemainingProfilesEntry.cpp
  src/cascadia/TerminalSettingsModel/RemainingProfilesEntry.h
  src/cascadia/TerminalSettingsModel/SeparatorEntry.cpp
  src/cascadia/TerminalSettingsModel/SeparatorEntry.h
  src/cascadia/TerminalSettingsModel/TerminalSettingsSerializationHelpers.h
  src/cascadia/TerminalSettingsModel/TerminalWarnings.idl
  src/cascadia/TerminalSettingsModel/dll/Microsoft.Terminal.Settings.Model.vcxproj
Labels: Issue-Feature, Area-Settings, Product-Terminal, AutoMerge, zBugBash-Consider

#14534 Don't crash when turning on Voice Access
  src/cascadia/WindowsTerminal/IslandWindow.cpp
Labels: Issue-Bug, Severity-Crash, Product-Terminal, AutoMerge, Severity-Blocking, Needs-Second, Area-Windowing, zBugBash-Consider

#14520 Remove our dependency on Microsoft.Toolkit.Win32.UI.XamlApplication
  dep/nuget/packages.config
  scratch/ScratchIslandApp/SampleApp/App.cpp
  scratch/ScratchIslandApp/SampleApp/App.h
  scratch/ScratchIslandApp/SampleApp/App.idl
  scratch/ScratchIslandApp/SampleApp/App.xaml
  scratch/ScratchIslandApp/SampleApp/SampleAppLib.vcxproj
  scratch/ScratchIslandApp/SampleApp/dll/SampleApp.vcxproj
  scratch/ScratchIslandApp/SampleApp/pch.h
  src/cascadia/LocalTests_TerminalApp/TerminalApp.LocalTests.vcxproj
  src/cascadia/TerminalApp/App.cpp
  src/cascadia/TerminalApp/App.h
  src/cascadia/TerminalApp/App.idl
  src/cascadia/TerminalApp/App.xaml
  src/cascadia/TerminalApp/TerminalAppLib.vcxproj
  src/cascadia/TerminalApp/dll/TerminalApp.vcxproj
  src/cascadia/TerminalApp/pch.h
  src/cascadia/WindowsTerminal/WindowsTerminal.vcxproj
  src/common.nugetversions.props
  src/common.nugetversions.targets
Labels: AutoMerge

#11090 DRAFT Spec for Buffer Exporting and Logging
  .github/actions/spelling/expect/expect.txt
  doc/specs/drafts/#642 - Buffer Exporting and Logging/#642 - Buffer Exporting and Logging.md
  doc/specs/drafts/#642 - Buffer Exporting and Logging/ConEmu-logging-settings.png
  doc/specs/drafts/#642 - Buffer Exporting and Logging/PuTTY-logging-settings.png
  doc/specs/drafts/#642 - Buffer Exporting and Logging/SecureCRT-logging-settings.png
  doc/specs/drafts/#642 - Buffer Exporting and Logging/securecrt-context-menu.png
Labels: Issue-Docs, Product-Terminal, AutoMerge

#14319 Introduce WT A11y Proposal 2023
  .github/actions/spelling/allow/allow.txt
  .github/actions/spelling/allow/names.txt
  .github/actions/spelling/expect/expect.txt
  doc/terminal-a11y-2023.md
Labels: Issue-Docs

#14540 Fix a crash when the theme doesn't have a `window`
  src/cascadia/WindowsTerminal/AppHost.cpp
Labels: AutoMerge, Needs-Second, Area-Theming, zBugBash-Consider

#14522 Ensure X/Y controls are updated when default launch pos selected
  src/cascadia/TerminalSettingsEditor/LaunchViewModel.cpp
Labels: AutoMerge, Needs-Second

#14470 Improve the color schemes page in the SUI
  src/cascadia/TerminalSettingsEditor/ColorSchemeViewModel.cpp
  src/cascadia/TerminalSettingsEditor/ColorSchemeViewModel.h
  src/cascadia/TerminalSettingsEditor/ColorSchemeViewModel.idl
  src/cascadia/TerminalSettingsEditor/ColorSchemes.cpp
  src/cascadia/TerminalSettingsEditor/ColorSchemes.h
  src/cascadia/TerminalSettingsEditor/ColorSchemes.xaml
  src/cascadia/TerminalSettingsEditor/ColorSchemesPageViewModel.cpp
  src/cascadia/TerminalSettingsEditor/ColorSchemesPageViewModel.h
  src/cascadia/TerminalSettingsEditor/ColorSchemesPageViewModel.idl
  src/cascadia/TerminalSettingsEditor/EditColorScheme.cpp
  src/cascadia/TerminalSettingsEditor/EditColorScheme.xaml
  src/cascadia/TerminalSettingsEditor/MainPage.cpp
  src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw
Labels: Product-Terminal, AutoMerge, Issue-Task, Priority-3, Area-Settings UI, zBugBash-Consider

#14550 Fix use of tabs instead of spaces in ColorSchemesPageViewModel.idl
  src/cascadia/TerminalSettingsEditor/ColorSchemesPageViewModel.idl
Labels: AutoMerge

#14564 Match 'add appearance' button text to AutoProp.Name
  src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw
Labels: Issue-Bug, Area-Accessibility, Product-Terminal, AutoMerge, Needs-Second, Priority-2

#14567 Use mica in the SUI if mica is enabled in the theme
  src/cascadia/TerminalSettingsEditor/MainPage.cpp
  src/cascadia/TerminalSettingsEditor/MainPage.h
  src/cascadia/TerminalSettingsEditor/MainPage.xaml
Labels: AutoMerge

#14569 [SUI] Polish Launch Parameters setting controls
  src/cascadia/TerminalSettingsEditor/CommonResources.xaml
  src/cascadia/TerminalSettingsEditor/Launch.xaml
  src/cascadia/TerminalSettingsEditor/LaunchViewModel.cpp
  src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw
Labels: Issue-Bug, Product-Terminal, AutoMerge, Needs-Second, Area-Settings UI

#14544 Add support for start /B and FreeConsole
  .github/actions/spelling/expect/expect.txt
  src/cascadia/TerminalConnection/ConptyConnection.cpp
  src/cascadia/TerminalConnection/ConptyConnection.h
  src/host/PtySignalInputThread.cpp
  src/host/VtIo.cpp
  src/host/VtIo.hpp
  src/host/output.cpp
  src/inc/conpty-static.h
  src/winconpty/dll/winconpty.def
  src/winconpty/ft_pty/ConPtyTests.cpp
  src/winconpty/ft_pty/winconpty.FeatureTests.vcxproj
  src/winconpty/winconpty.cpp
  src/winconpty/winconpty.h
Labels: Product-Conpty, Area-Server, Issue-Bug, Product-Terminal, AutoMerge, Priority-2, Area-DefApp

#14551 Replace UIA CompareInBounds with til::point comparators
  src/types/UiaTextRangeBase.cpp
Labels: Issue-Bug, Area-Accessibility, Product-Terminal, AutoMerge

#14513 GitHub Workflows security hardening
  .github/workflows/addToProject.yml
Labels: AutoMerge
