Repository microsoft/terminal, pull requests merged in 2022-02, with the labels that each got.

#12306 Add PGOBuildMode to PGD merge step
  build/pipelines/templates/pgo-merge-pgd-job.yml
Labels: Issue-Bug, Area-Build, Product-Terminal, Severity-Blocking, Priority-0, zPreview-Service-Consider

#12304 Add `experimental.useAtlasEngine` to schema
  doc/cascadia/profiles.schema.json
Labels: Issue-Docs, Area-Settings, Product-Terminal, AutoMerge

#12307 AtlasEngine: Fix support for combining diacritics
  src/renderer/atlas/AtlasEngine.cpp
  src/renderer/atlas/AtlasEngine.h
Labels: Issue-Bug, AutoMerge, zPreview-Service-Consider, Area-AtlasEngine

#12315 Set the default WSL starting directory to ~
  src/cascadia/TerminalSettingsModel/WslDistroGenerator.cpp
Labels: AutoMerge, Needs-Second, zPreview-Service-Consider

#12320 Make sure Terminal Stable shows up as default on 22544+
  src/internal/stubs.cpp
Labels: Product-Terminal, AutoMerge, Issue-Task, Severity-Blocking, Priority-0, zPreview-Service-Consider, Area-DefApp

#12321 Localize and polish Profile page navigators
  src/cascadia/TerminalSettingsEditor/CommonResources.xaml
  src/cascadia/TerminalSettingsEditor/Profiles_Base.cpp
  src/cascadia/TerminalSettingsEditor/Profiles_Base.xaml
Labels: AutoMerge, zPreview-Service-Consider

#12332 Update readme to account for minversion bump
  README.md
Labels: Issue-Docs

#12324 Update accessible names for 'add profile' page buttons
  src/cascadia/TerminalSettingsEditor/AddProfile.cpp
  src/cascadia/TerminalSettingsEditor/AddProfile.xaml
Labels: Issue-Bug, Area-Accessibility, Needs-Author-Feedback, Product-Terminal, AutoMerge, Priority-3, zPreview-Service-Consider, Area-Settings UI

#12326 Fix more SUI and Rejuvenated UI issues
  src/cascadia/TerminalApp/App.xaml
  src/cascadia/TerminalSettingsEditor/Actions.xaml
  src/cascadia/TerminalSettingsEditor/AddProfile.xaml
  src/cascadia/TerminalSettingsEditor/Appearances.xaml
  src/cascadia/TerminalSettingsEditor/ColorSchemes.xaml
  src/cascadia/TerminalSettingsEditor/CommonResources.xaml
  src/cascadia/TerminalSettingsEditor/MainPage.xaml
  src/cascadia/TerminalSettingsEditor/Profiles_Appearance.xaml
  src/cascadia/TerminalSettingsEditor/Profiles_Base.xaml
Labels: AutoMerge

#12247 Refactor and simplify the ConGetSet API
  src/cascadia/UnitTests_TerminalCore/ConptyRoundtripTests.cpp
  src/host/PtySignalInputThread.cpp
  src/host/cmdline.h
  src/host/directio.cpp
  src/host/directio.h
  src/host/getset.cpp
  src/host/getset.h
  src/host/outputStream.cpp
  src/host/outputStream.hpp
  src/host/ut_host/ConptyOutputTests.cpp
  src/host/ut_host/ScreenBufferTests.cpp
  src/terminal/adapter/DispatchCommon.cpp
  src/terminal/adapter/DispatchCommon.hpp
  src/terminal/adapter/InteractDispatch.cpp
  src/terminal/adapter/adaptDispatch.cpp
  src/terminal/adapter/adaptDispatch.hpp
  src/terminal/adapter/adaptDispatchGraphics.cpp
  src/terminal/adapter/conGetSet.hpp
  src/terminal/adapter/ut_adapter/adapterTest.cpp
  src/terminal/parser/InputStateMachineEngine.cpp
  src/terminal/parser/OutputStateMachineEngine.cpp
  src/terminal/parser/OutputStateMachineEngine.hpp
  src/terminal/parser/stateMachine.cpp
  src/terminal/parser/stateMachine.hpp
Labels: Product-Conhost, Area-VT, Issue-Bug, AutoMerge, Priority-2

#12368 Adding missed MIT license in a few files
  dep/Console/conapi.h
  dep/Console/condrv.h
  dep/Console/conmsgl1.h
  dep/Console/conmsgl2.h
  dep/Console/conmsgl3.h
  dep/Console/ntcon.h
  dep/Console/winconp.h
  dep/NT/ntioapi_x.h
  dep/Win32K/winuserp.h
Labels: Issue-Docs, AutoMerge, Product-Meta, Area-CodeHealth

#12355 Always publish the binlog
  build/pipelines/templates/build-console-steps.yml
Labels: AutoMerge

#12381 Fix toggle switches needing a negative margin
  src/cascadia/TerminalSettingsEditor/CommonResources.xaml
Labels: AutoMerge, zPreview-Service-Queued-1.13

#12375 Hardcode the language list for the package manifest and settings dropdown
  .github/actions/spelling/expect/expect.txt
  src/cascadia/CascadiaPackage/Package-Dev.appxmanifest
  src/cascadia/CascadiaPackage/Package-Pre.appxmanifest
  src/cascadia/CascadiaPackage/Package.appxmanifest
  src/cascadia/TerminalSettingsEditor/GlobalAppearance.cpp
Labels: Issue-Bug, Product-Terminal, AutoMerge, Priority-0, Area-Localization, zStable-Service-Queued-1.12, zPreview-Service-Queued-1.13

#12376 Fix invoking the rightmost breadcrumb bringing you back to Profiles_Base
  src/cascadia/TerminalSettingsEditor/MainPage.cpp
Labels: Issue-Bug, Product-Terminal, AutoMerge, zPreview-Service-Queued-1.13, Area-Settings UI

#12386 Fix the grammar in a comment
  src/host/_stream.cpp
Labels: AutoMerge

#12404 Update Bug_Report.yml
  .github/ISSUE_TEMPLATE/Bug_Report.yml
Labels: Needs-Author-Feedback, AutoMerge, Needs-Second, Needs-Discussion

#12430 Fix a potential crash when setting up the jumplist
  src/cascadia/TerminalApp/Jumplist.cpp
Labels: Severity-Crash, Product-Terminal, AutoMerge, Priority-2

#12439 Fix focus box around color schemes combo box
  src/cascadia/TerminalSettingsEditor/ColorSchemes.xaml
Labels: Issue-Bug, Product-Terminal, Priority-3, Area-Settings UI

#12434 XtermEngine: Explicitly emit cursor state on the first frame
  .github/actions/spelling/expect/expect.txt
  src/host/ut_host/VtRendererTests.cpp
  src/renderer/vt/XtermEngine.cpp
  src/renderer/vt/XtermEngine.hpp
Labels: Area-VT, Issue-Bug, Product-Terminal, Priority-2, zPreview-Service-Queued-1.13

#12438 Properly fall back to Segoe MDL2 for our icons on Win10
  src/cascadia/TerminalSettingsEditor/Appearances.xaml
  src/cascadia/TerminalSettingsEditor/SettingContainerStyle.xaml
Labels: Issue-Bug, Product-Terminal, Needs-Second, Priority-3, Area-Settings UI

#12435 Fix browse buttons getting cut off when the window is too narrow
  src/cascadia/TerminalSettingsEditor/Appearances.xaml
  src/cascadia/TerminalSettingsEditor/CommonResources.xaml
  src/cascadia/TerminalSettingsEditor/Profiles_Base.xaml
Labels: Issue-Bug, Product-Terminal, Priority-3, Area-Settings UI

#12441 Publish the symbols from our MSIX bundle to the public server
  .github/actions/spelling/expect/expect.txt
  build/pipelines/release.yml
Labels: zStable-Service-Queued-1.12, zPreview-Service-Queued-1.13

#12436 Validate cursor position in UIA UTR ctor
  src/types/UiaTextRangeBase.cpp
Labels: Issue-Bug, Area-Accessibility, Severity-Crash, Product-Terminal, Priority-1, zStable-Service-Queued-1.12, zPreview-Service-Queued-1.13

#12432 Allow exceptions from ITerminalApi and TerminalDispatch
  src/cascadia/TerminalCore/ITerminalApi.hpp
  src/cascadia/TerminalCore/Terminal.hpp
  src/cascadia/TerminalCore/TerminalApi.cpp
  src/cascadia/TerminalCore/TerminalDispatch.cpp
  src/cascadia/TerminalCore/TerminalDispatch.hpp
  src/cascadia/TerminalCore/TerminalDispatchGraphics.cpp
  src/cascadia/UnitTests_TerminalCore/TerminalApiTest.cpp
  src/terminal/adapter/termDispatch.hpp
Labels: AutoMerge, zPreview-Service-Queued-1.13

#12442 Fix defterm + elevate by default
  src/cascadia/TerminalApp/TerminalPage.cpp
  src/cascadia/TerminalSettingsModel/ActionArgs.idl
Labels: Issue-Bug, Product-Terminal, Needs-Second, Priority-1, zPreview-Service-Queued-1.13, Area-DefApp

#12437 Don't ever allow `~` as a startingDirectory
  src/types/ut_types/UtilsTests.cpp
  src/types/utils.cpp
Labels: Issue-Bug, Area-TerminalConnection, Product-Terminal, AutoMerge, Needs-Second, Priority-1, zStable-Service-Queued-1.12, zPreview-Service-Queued-1.13

#12389 Eliminate the DispatchCommon class
  src/cascadia/UnitTests_TerminalCore/ConptyRoundtripTests.cpp
  src/host/PtySignalInputThread.cpp
  src/host/outputStream.cpp
  src/host/outputStream.hpp
  src/terminal/adapter/DispatchCommon.cpp
  src/terminal/adapter/DispatchCommon.hpp
  src/terminal/adapter/InteractDispatch.cpp
  src/terminal/adapter/adaptDispatch.cpp
  src/terminal/adapter/adaptDispatch.hpp
  src/terminal/adapter/conGetSet.hpp
  src/terminal/adapter/lib/adapter.vcxproj
  src/terminal/adapter/lib/adapter.vcxproj.filters
  src/terminal/adapter/sources.inc
  src/terminal/adapter/ut_adapter/adapterTest.cpp
Labels: Area-VT, AutoMerge, Product-Meta, Issue-Task

#12390 Eliminate the AdaptDefaults class
  src/cascadia/TerminalCore/ITerminalApi.hpp
  src/cascadia/TerminalCore/Terminal.hpp
  src/cascadia/TerminalCore/TerminalApi.cpp
  src/cascadia/TerminalCore/TerminalDispatch.cpp
  src/cascadia/TerminalCore/TerminalDispatch.hpp
  src/host/outputStream.cpp
  src/host/outputStream.hpp
  src/host/screenInfo.cpp
  src/terminal/adapter/ITermDispatch.hpp
  src/terminal/adapter/adaptDefaults.hpp
  src/terminal/adapter/adaptDispatch.cpp
  src/terminal/adapter/adaptDispatch.hpp
  src/terminal/adapter/conGetSet.hpp
  src/terminal/adapter/lib/adapter.vcxproj
  src/terminal/adapter/lib/adapter.vcxproj.filters
  src/terminal/adapter/termDispatch.hpp
  src/terminal/adapter/ut_adapter/adapterTest.cpp
  src/terminal/parser/ft_fuzzwrapper/echoDispatch.cpp
  src/terminal/parser/ft_fuzzwrapper/echoDispatch.hpp
  src/terminal/parser/ut_parser/OutputEngineTest.cpp
Labels: Area-VT, AutoMerge, Product-Meta, Issue-Task

#12444 Enable the 'automatic adjustment of indistinguishable text' setting for Dev builds
  src/features.xml
Labels: AutoMerge

#12449 Automate packaged submission into Windows
  .github/actions/spelling/expect/expect.txt
  build/config/GitCheckin.json
  build/pipelines/release.yml
Labels: Area-Build, Product-Terminal, Issue-Task, zStable-Service-Queued-1.12, zPreview-Service-Queued-1.13

#12448 Add tooltips for nav items in the SUI
  src/cascadia/TerminalSettingsEditor/MainPage.cpp
  src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw
Labels: AutoMerge

#12429 Update the cmdpal narrator message to include the number of results.
  src/cascadia/TerminalApp/CommandPalette.cpp
  src/cascadia/TerminalApp/Resources/en-US/Resources.resw
Labels: Issue-Bug, Area-User Interface, Area-Accessibility, Product-Terminal, AutoMerge, Priority-2, Impact-Compliance, Area-CmdPal

#12450 Source index the public symbols too
  build/pipelines/release.yml
Labels: Area-Build, Product-Terminal, AutoMerge, Issue-Task, Needs-Second, zStable-Service-Queued-1.12, zPreview-Service-Queued-1.13

#12415 AtlasEngine: Fix leak check report for OpenConsole
  src/interactivity/base/ServiceLocator.cpp
  src/interactivity/inc/ServiceLocator.hpp
  src/interactivity/win32/window.cpp
  src/interactivity/win32/window.hpp
Labels: Product-Conhost, Issue-Bug, AutoMerge, Priority-3, Area-AtlasEngine

#12469 Updates all our icons to use Segoe Fluent
  src/cascadia/TerminalApp/CommandPalette.xaml
  src/cascadia/TerminalApp/SettingsTab.cpp
  src/cascadia/TerminalApp/TabBase.cpp
  src/cascadia/TerminalApp/TabHeaderControl.xaml
  src/cascadia/TerminalApp/TabRowControl.xaml
  src/cascadia/TerminalApp/TerminalPage.cpp
  src/cascadia/TerminalApp/TerminalTab.cpp
  src/cascadia/TerminalControl/SearchBoxControl.xaml
  src/cascadia/TerminalSettingsEditor/Profiles_Base.xaml
  src/cascadia/TerminalSettingsEditor/SettingContainerStyle.xaml
  src/cascadia/TerminalSettingsModel/IconPathConverter.cpp
Labels: Issue-Bug, Product-Terminal, AutoMerge, Issue-Task, Needs-Second, Priority-3, zPreview-Service-Queued-1.13, Area-Settings UI

#12462 Enable Segoe Variable
  src/cascadia/WindowsTerminal/WindowsTerminal.manifest
Labels: Issue-Bug, Area-User Interface, Product-Terminal, AutoMerge, Needs-Second, Priority-1, zPreview-Service-Queued-1.13

#12484 Fix off-by-one bug in NormalizeCommandLine
  src/cascadia/LocalTests_SettingsModel/TerminalSettingsTests.cpp
  src/cascadia/TerminalSettingsModel/CascadiaSettings.cpp
Labels: Issue-Bug, Product-Terminal, AutoMerge, Area-CodeHealth, Priority-3, zStable-Service-Queued-1.12, zPreview-Service-Queued-1.13

#12460 Manually set the colors of the TabViewBackground
  src/cascadia/TerminalApp/App.xaml
  src/cascadia/TerminalApp/TerminalPage.cpp
Labels: Issue-Bug, Area-TerminalControl, Product-Terminal, AutoMerge, Priority-1

#12463 DON'T default-construct the `MediaPlayer`
  src/cascadia/TerminalApp/Pane.cpp
  src/cascadia/TerminalApp/Pane.h
Labels: Issue-Bug, Severity-Crash, Product-Terminal, AutoMerge, zPreview-Service-Queued-1.13

#12340 Fix a memory leak in onecore interactivity
  src/interactivity/onecore/ConIoSrvComm.cpp
Labels: Product-Conhost, Issue-Bug, AutoMerge, Area-CodeHealth, Priority-2

#12491 Copy localized strings from ContextMenu into the resource root
  build/pipelines/release.yml
  build/scripts/Copy-ContextMenuResourcesToCascadiaPackage.ps1
  src/cascadia/CascadiaPackage/Package-Dev.appxmanifest
  src/cascadia/CascadiaPackage/Package-Pre.appxmanifest
  src/cascadia/CascadiaPackage/Package.appxmanifest
  src/cascadia/CascadiaPackage/Resources/en-US/Resources.resw
Labels: Issue-Bug, Area-User Interface, Product-Terminal, AutoMerge, Priority-1, zStable-Service-Queued-1.12, zPreview-Service-Queued-1.13

#12489 Potentially fix Submit OneFuzz CI Job
  build/pipelines/fuzz.yml
Labels: AutoMerge

#12492 Fix font axes/features not working on DPI change
  src/cascadia/TerminalControl/ControlCore.cpp
Labels: Area-Rendering, Issue-Bug, Product-Terminal, AutoMerge, Priority-3, zStable-Service-Queued-1.12, zPreview-Service-Queued-1.13

#12499 Remove "Window Persistence" feature flag
  src/cascadia/TerminalApp/TerminalPage.cpp
  src/cascadia/TerminalSettingsEditor/Launch.cpp
  src/cascadia/TerminalSettingsEditor/Launch.h
  src/cascadia/TerminalSettingsEditor/Launch.idl
  src/cascadia/TerminalSettingsEditor/Launch.xaml
  src/features.xml
Labels: Product-Terminal, Issue-Task, Area-CodeHealth, zPreview-Service-Queued-1.13

#12505 Replace "acrylic" with "acrylic material" in i18n strings
  doc/cascadia/profiles.schema.json
  src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw
Labels: Product-Terminal, AutoMerge, Issue-Task, Area-Localization, Area-Settings UI

#12517 No longer load content dialogs when there is already one being shown
  src/cascadia/TerminalApp/AppLogic.cpp
  src/cascadia/TerminalApp/AppLogic.h
  src/cascadia/TerminalApp/AppLogic.idl
  src/cascadia/TerminalApp/TerminalPage.cpp
  src/cascadia/TerminalApp/TerminalPage.h
  src/cascadia/TerminalApp/TerminalPage.idl
  src/cascadia/TerminalApp/TerminalPage.xaml
Labels: Issue-Bug, Product-Terminal, AutoMerge, Priority-1, Area-Settings UI

#12538 Don't crash trying to parse a command line that's a directory
  src/cascadia/LocalTests_SettingsModel/TerminalSettingsTests.cpp
  src/cascadia/TerminalSettingsModel/CascadiaSettings.cpp
Labels: Issue-Bug, AutoMerge, Area-Commandline, zStable-Service-Queued-1.12, zPreview-Service-Queued-1.13

#12549 Commit updated TerminalApp.Unit.Tests.manifest file
  src/cascadia/ut_app/TerminalApp.Unit.Tests.manifest
Labels: Issue-Bug, AutoMerge

#12528 Protect the command palette against being paged with no items
  src/cascadia/TerminalApp/CommandPalette.cpp
Labels: AutoMerge, zStable-Service-Queued-1.12, zPreview-Service-Queued-1.13

#12548 AtlasEngine: Fix inverted cursor alpha
  src/renderer/atlas/shader_ps.hlsl
Labels: Issue-Bug, Product-Terminal, AutoMerge, Priority-3, Area-AtlasEngine

#12529 Update light theme tab background for greater contrast.
  src/cascadia/TerminalApp/App.xaml
Labels: Issue-Bug, Area-User Interface, Product-Terminal, AutoMerge, Priority-3, zPreview-Service-Queued-1.13

#12560 build: ship a Win11 build of Terminal that's <=half the size
  .github/actions/spelling/allow/microsoft.txt
  build/pipelines/release.yml
  build/scripts/Patch-ManifestsToWindowsVersion.ps1
  common.openconsole.props
  custom.props
  scratch/ScratchIslandApp/Package/Package.wapproj
  scratch/ScratchIslandApp/SampleApp/SampleAppLib.vcxproj
  scratch/ScratchIslandApp/SampleApp/dll/SampleApp.vcxproj
  scratch/ScratchIslandApp/SampleApp/packages.config
  scratch/ScratchIslandApp/WindowExe/WindowExe.vcxproj
  scratch/ScratchIslandApp/WindowExe/packages.config
  src/cascadia/CascadiaPackage/CascadiaPackage.wapproj
  src/cascadia/LocalTests_SettingsModel/SettingsModel.LocalTests.vcxproj
  src/cascadia/LocalTests_TerminalApp/TerminalApp.LocalTests.vcxproj
  src/cascadia/LocalTests_TerminalApp/TestHostApp/TestHostApp.vcxproj
  src/cascadia/TerminalApp/TerminalAppLib.vcxproj
  src/cascadia/TerminalApp/dll/TerminalApp.vcxproj
  src/cascadia/TerminalApp/packages.config
  src/cascadia/TerminalSettingsEditor/Microsoft.Terminal.Settings.Editor.vcxproj
  src/cascadia/TerminalSettingsEditor/packages.config
  src/cascadia/TerminalSettingsModel/Microsoft.Terminal.Settings.ModelLib.vcxproj
  src/cascadia/TerminalSettingsModel/dll/Microsoft.Terminal.Settings.Model.vcxproj
  src/cascadia/WindowsTerminal/WindowsTerminal.vcxproj
  src/cascadia/WindowsTerminal/packages.config
  src/cascadia/ut_app/TerminalApp.UnitTests.vcxproj
  src/cppwinrt.build.pre.props
Labels: zStable-Service-Queued-1.12, zPreview-Service-Queued-1.13, this-will-be-a-breaking-change

#7414 Default Terminal Spec
  doc/specs/#492 - Default Terminal/spec.md
Labels: Product-Conhost, Issue-Docs, Product-Conpty, Area-Server, Product-Terminal
