Repository microsoft/terminal, pull requests merged in 2022-10, with the labels that each got.

#14122 Update jsoncpp from 1.9.3 to 1.9.5
  dep/jsoncpp/README.md
  dep/jsoncpp/cgmanifest.json
  dep/jsoncpp/json/json-forwards.h
  dep/jsoncpp/json/json.h
  dep/jsoncpp/jsoncpp.cpp
Labels: AutoMerge

#13605 Implement InitialPosition and CenterOnLaunch in the SUI
  .github/actions/spelling/allow/allow.txt
  src/cascadia/TerminalSettingsEditor/Launch.cpp
  src/cascadia/TerminalSettingsEditor/Launch.xaml
  src/cascadia/TerminalSettingsEditor/LaunchViewModel.cpp
  src/cascadia/TerminalSettingsEditor/LaunchViewModel.h
  src/cascadia/TerminalSettingsEditor/LaunchViewModel.idl
  src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw
Labels: Product-Terminal, AutoMerge, Issue-Task, Area-Settings UI

#14097 [wpf] Add UIA events
  OpenConsole.sln
  src/cascadia/PublicTerminalCore/HwndTerminal.cpp
  src/cascadia/PublicTerminalCore/HwndTerminal.hpp
  src/cascadia/PublicTerminalCore/HwndTerminalAutomationPeer.cpp
  src/cascadia/PublicTerminalCore/HwndTerminalAutomationPeer.hpp
  src/cascadia/PublicTerminalCore/PublicTerminalCore.vcxproj
  src/cascadia/PublicTerminalCore/PublicTerminalCore.vcxproj.filters
  src/cascadia/PublicTerminalCore/pch.h
  src/cascadia/WpfTerminalControl/TerminalContainer.cs
  src/cascadia/WpfTerminalControl/TerminalControl.xaml.cs
  src/types/TermControlUiaProvider.cpp
  src/types/TermControlUiaProvider.hpp
Labels: Issue-Bug, Area-Accessibility, Product-Terminal, AutoMerge, Priority-1, Area-WPFControl

#14148 Update IntervalTree.h dependency
  oss/interval_tree/IntervalTree.h
  oss/interval_tree/MAINTAINER_README.md
  oss/interval_tree/cgmanifest.json
Labels: AutoMerge

#14140 Update libpopcnt to 2.5
  oss/libpopcnt/cgmanifest.json
  oss/libpopcnt/libpopcnt.h
Labels: AutoMerge

#14135 Upgrade to Windows SDK 22621
  .vsconfig
  README.md
  build/scripts/Create-AppxBundle.ps1
  build/scripts/Test-WindowsTerminalPackage.ps1
  doc/cascadia/Unittesting-CppWinRT-Xaml.md
  samples/ConPTY/EchoCon/EchoCon/EchoCon.vcxproj
  scratch/ScratchIslandApp/Package/Package.appxmanifest
  src/cascadia/CascadiaPackage/Package-Dev.appxmanifest
  src/cascadia/CascadiaPackage/Package-Pre.appxmanifest
  src/cascadia/CascadiaPackage/Package.appxmanifest
  src/cascadia/LocalTests_TerminalApp/TerminalApp.LocalTests.AppxManifest.prototype.xml
  src/cascadia/LocalTests_TerminalApp/TestHostApp/Package.appxmanifest
  src/cascadia/WindowsTerminal/WindowsTerminal.manifest
  src/cascadia/ut_app/TerminalApp.Unit.Tests.AppxManifest.xml
  src/cascadia/ut_app/TerminalApp.Unit.Tests.manifest
  src/common.build.pre.props
  src/tools/MonarchPeasantPackage/MonarchPeasantPackage.wapproj
  src/wap-common.build.pre.props
Labels: AutoMerge

#14123 Update to XAML 2.7.3
  scratch/ScratchIslandApp/SampleApp/packages.config
  scratch/ScratchIslandApp/WindowExe/packages.config
  src/cascadia/TerminalApp/packages.config
  src/cascadia/TerminalSettingsEditor/packages.config
  src/cascadia/WindowsTerminal/packages.config
Labels: AutoMerge

#14046 Add support for selective erase operations
  src/buffer/out/TextAttribute.cpp
  src/buffer/out/TextAttribute.hpp
  src/host/ut_host/ScreenBufferTests.cpp
  src/inc/conattrs.hpp
  src/terminal/adapter/DispatchTypes.hpp
  src/terminal/adapter/ITermDispatch.hpp
  src/terminal/adapter/adaptDispatch.cpp
  src/terminal/adapter/adaptDispatch.hpp
  src/terminal/adapter/adaptDispatchGraphics.cpp
  src/terminal/adapter/termDispatch.hpp
  src/terminal/adapter/ut_adapter/adapterTest.cpp
  src/terminal/parser/OutputStateMachineEngine.cpp
  src/terminal/parser/OutputStateMachineEngine.hpp
  src/terminal/parser/telemetry.cpp
  src/terminal/parser/telemetry.hpp
Labels: Product-Conhost, Area-VT, AutoMerge, Issue-Task

#14159 Update scratch projects to XAML 2.7.3
  scratch/ScratchIslandApp/Package/Package.wapproj
  scratch/ScratchIslandApp/SampleApp/SampleAppLib.vcxproj
  scratch/ScratchIslandApp/SampleApp/dll/SampleApp.vcxproj
  scratch/ScratchIslandApp/WindowExe/WindowExe.vcxproj
Labels: AutoMerge

#13730 Add `--pos` and `--size` cmdline args
  src/cascadia/TerminalApp/AppCommandlineArgs.cpp
  src/cascadia/TerminalApp/AppCommandlineArgs.h
  src/cascadia/TerminalApp/AppLogic.cpp
  src/cascadia/TerminalApp/Resources/en-US/Resources.resw
  src/cascadia/TerminalControl/TermControl.cpp
  src/cascadia/TerminalControl/TermControl.h
  src/cascadia/TerminalControl/TermControl.idl
  src/cascadia/TerminalSettingsModel/Microsoft.Terminal.Settings.ModelLib.vcxproj
  src/cascadia/TerminalSettingsModel/ModelSerializationHelpers.h
  src/cascadia/TerminalSettingsModel/TerminalSettingsSerializationHelpers.h
Labels: Issue-Feature, Product-Terminal, AutoMerge, Needs-Second, Area-Commandline

#14167 Fix clipped progress ring in tab when tab title is too long
  src/cascadia/TerminalApp/TabHeaderControl.xaml
  src/cascadia/TerminalApp/TerminalTab.cpp
Labels: Issue-Bug, Area-User Interface, Product-Terminal, AutoMerge, Priority-3

#13981 Add support for DECARM (Auto Repeat Mode)
  src/terminal/adapter/DispatchTypes.hpp
  src/terminal/adapter/adaptDispatch.cpp
  src/terminal/adapter/ut_adapter/inputTest.cpp
  src/terminal/input/terminalInput.cpp
  src/terminal/input/terminalInput.hpp
Labels: Product-Conhost, Area-VT, Product-Terminal, AutoMerge, Issue-Task, Needs-Second

#14180 Make SUI breadcrumb readable by screen readers
  src/cascadia/TerminalSettingsEditor/MainPage.h
  src/cascadia/TerminalSettingsEditor/MainPage.idl
Labels: Issue-Bug, Area-Accessibility, Product-Terminal, AutoMerge, Needs-Second, Priority-1

#13964 Fix duplication issue for unfocused tabs
  src/cascadia/LocalTests_TerminalApp/TabTests.cpp
  src/cascadia/TerminalApp/AppActionHandlers.cpp
  src/cascadia/TerminalApp/TabManagement.cpp
  src/cascadia/TerminalApp/TerminalPage.cpp
  src/cascadia/TerminalApp/TerminalPage.h
Labels: Issue-Bug, Area-User Interface, Product-Terminal, AutoMerge, Priority-2

#14186 Fix some issues with the launch parameters in the SUI
  src/cascadia/TerminalSettingsEditor/LaunchViewModel.cpp
  src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw
Labels: AutoMerge, Needs-Second

#14092 Generally tidy the Commandline class
  src/host/cmdline.cpp
  src/host/cmdline.h
  src/host/scrolling.cpp
Labels: AutoMerge, Area-CodeHealth

#14190 Update LaunchPosition to use int32_t instead of int64_t
  src/cascadia/TerminalSettingsEditor/LaunchViewModel.cpp
  src/cascadia/TerminalSettingsModel/GlobalAppSettings.idl
Labels: AutoMerge

#14198 Add a maximum OSC 8 URI length of 2MB following iTerm2
  src/cascadia/TerminalControl/ControlCore.cpp
  src/terminal/parser/OutputStateMachineEngine.cpp
  src/terminal/parser/OutputStateMachineEngine.hpp
Labels: AutoMerge, Needs-Second

#14160 Fix a deadlock during ConPTY shutdown
  src/host/VtInputThread.cpp
  src/host/VtInputThread.hpp
  src/host/VtIo.cpp
  src/host/VtIo.hpp
  src/interactivity/base/ServiceLocator.cpp
  src/interactivity/inc/ServiceLocator.hpp
  src/renderer/vt/paint.cpp
  src/renderer/vt/state.cpp
  src/renderer/vt/vtrenderer.hpp
  src/winconpty/ft_pty/ConPtyTests.cpp
Labels: Issue-Bug, Product-Terminal, AutoMerge, Severity-Blocking, Needs-Second, Area-Remoting

#14216 Make sure VT reports still work when DECARM is disabled
  src/terminal/input/terminalInput.cpp
  src/terminal/input/terminalInput.hpp
Labels: Issue-Bug, AutoMerge

#14221 Pipe DirectKey events into TerminalPage for Alt+Space
  src/cascadia/TerminalApp/TerminalPage.cpp
  src/cascadia/TerminalApp/TerminalPage.h
  src/cascadia/TerminalApp/TerminalPage.idl
Labels: Issue-Bug, Area-Accessibility, Product-Terminal, AutoMerge

#14210 Fix a missing entry for intenseTextStyle in the Profile schema
  doc/cascadia/profiles.schema.json
Labels: Issue-Bug, Product-Terminal, Priority-3, Area-Schema

#14195 Disallow a window waiting on system() to block DefTerm startup
  src/cascadia/WindowsTerminal/IslandWindow.cpp
Labels: Product-Terminal, AutoMerge, Severity-Blocking, Priority-1, Area-DefApp

#14224 Stop freeing BSTRs that do not belong to us
  src/cascadia/TerminalConnection/ConptyConnection.cpp
Labels: Issue-Bug, Area-TerminalConnection, Product-Terminal, AutoMerge, Needs-Second, Priority-1

#14225 Fix the Release build ProxyStubClsids from #13570
  src/cascadia/CascadiaPackage/Package.appxmanifest
Labels: Issue-Bug, Area-Build, Product-Terminal, AutoMerge, Needs-Second, Priority-0

#14099 AtlasEngine: Block chars done right-er
  src/renderer/atlas/AtlasEngine.api.cpp
  src/renderer/atlas/AtlasEngine.cpp
  src/renderer/atlas/AtlasEngine.h
  src/renderer/atlas/AtlasEngine.r.cpp
Labels: Issue-Bug, Product-Terminal, AutoMerge, Needs-Second, Priority-3, Area-AtlasEngine

#14229 Override center on launch setting when position specified on cmdline
  src/cascadia/TerminalApp/AppLogic.cpp
Labels: Issue-Bug, Area-Settings, Product-Terminal, AutoMerge, Priority-3

#14230 Update XamlStyler version
  .config/dotnet-tools.json
  build/pipelines/templates/check-formatting.yml
Labels: AutoMerge

#14248 Remove vestigial submodule entry
  .gitmodules
Labels: AutoMerge

#14277 Fix a test failure in HashTests
  src/til/ut_til/HashTests.cpp
Labels: Area-CodeHealth

#14266 Use float throughout ColorFix
  src/types/ColorFix.cpp
  src/types/inc/ColorFix.hpp
Labels: Area-Performance, AutoMerge, Area-CodeHealth

#14244 Remove redundant tooltips from settings UI
  src/cascadia/TerminalSettingsEditor/MainPage.cpp
  src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw
  src/cascadia/TerminalSettingsEditor/SettingContainer.cpp
Labels: Issue-Bug, Area-User Interface, Product-Terminal, AutoMerge, Needs-Second

#14290 Add support for private options in DSR queries
  src/terminal/adapter/DispatchTypes.hpp
  src/terminal/adapter/ITermDispatch.hpp
  src/terminal/adapter/adaptDispatch.cpp
  src/terminal/adapter/adaptDispatch.hpp
  src/terminal/adapter/termDispatch.hpp
  src/terminal/adapter/ut_adapter/adapterTest.cpp
  src/terminal/parser/OutputStateMachineEngine.cpp
  src/terminal/parser/OutputStateMachineEngine.hpp
  src/terminal/parser/ut_parser/OutputEngineTest.cpp
Labels: Product-Conhost, Area-VT, AutoMerge, Issue-Task

#14222 Respect the "/max" parameter when starting console apps with defterm enabled
  src/cascadia/TerminalApp/TerminalPage.cpp
  src/cascadia/TerminalConnection/ConptyConnection.cpp
  src/cascadia/TerminalConnection/ConptyConnection.h
  src/cascadia/TerminalConnection/ConptyConnection.idl
  src/host/srvinit.cpp
Labels: AutoMerge

#14107 Allow for exe/dll paths for the Icon setting
  src/cascadia/LocalTests_SettingsModel/pch.h
  src/cascadia/TerminalApp/CommandPalette.xaml
  src/cascadia/TerminalApp/PaletteItem.cpp
  src/cascadia/TerminalApp/PaletteItem.h
  src/cascadia/TerminalApp/PaletteItem.idl
  src/cascadia/TerminalApp/TerminalPage.cpp
  src/cascadia/TerminalSettingsEditor/MainPage.cpp
  src/cascadia/TerminalSettingsModel/IconPathConverter.cpp
  src/cascadia/TerminalSettingsModel/IconPathConverter.h
  src/cascadia/TerminalSettingsModel/IconPathConverter.idl
  src/cascadia/TerminalSettingsModel/pch.h
Labels: Area-Settings, Product-Terminal, AutoMerge, Issue-Task

#14267 Disable /fp:fast by default
  src/cascadia/TerminalControl/TermControl.cpp
  src/common.build.pre.props
  src/inc/til.h
  src/project.inc
  src/til/ut_til/SizeTests.cpp
  src/types/ColorFix.cpp
Labels: AutoMerge, Area-CodeHealth

#14193 Disable acrylic material (temporarily) when opacity is set to 100%
  src/cascadia/TerminalControl/ControlCore.cpp
  src/cascadia/UnitTests_Control/ControlCoreTests.cpp
  src/cascadia/UnitTests_Control/ControlInteractivityTests.cpp
Labels: Issue-Bug, Area-TerminalControl, Product-Terminal, AutoMerge, Priority-3

#14214 Skip DECPS/MIDI output on Ctrl+C/Break
  src/audio/midi/MidiAudio.cpp
  src/audio/midi/MidiAudio.hpp
  src/audio/midi/precomp.h
  src/cascadia/TerminalControl/ControlCore.cpp
  src/cascadia/TerminalControl/ControlCore.h
  src/host/consoleInformation.cpp
  src/host/globals.cpp
  src/host/input.cpp
  src/host/output.cpp
  src/host/outputStream.cpp
  src/host/server.h
  src/interactivity/base/ServiceLocator.cpp
Labels: Product-Conhost, Area-VT, Issue-Bug, Product-Terminal, AutoMerge, Priority-1

#13746 Add recursive_ticket_lock and use it for Terminal
  .github/actions/spelling/allow/allow.txt
  src/cascadia/TerminalControl/ControlCore.cpp
  src/cascadia/TerminalCore/Terminal.cpp
  src/cascadia/TerminalCore/Terminal.hpp
  src/cascadia/TerminalCore/terminalrenderdata.cpp
  src/host/consoleInformation.cpp
  src/host/server.h
  src/inc/til/ticket_lock.h
Labels: AutoMerge, Area-CodeHealth, Needs-Second
