Repository microsoft/terminal, pull requests merged in 2023-12, with the labels that each got.

#16400 Fix backspacing over control visualizers
  doc/COOKED_READ_DATA.md
  src/host/readDataCooked.cpp
Labels: Product-Conhost, Issue-Bug, Priority-0, Area-CookedRead, zInbox-Bug

#16412 Fix a coroutine AV crash
  src/cascadia/TerminalApp/TerminalTab.cpp
Labels: Issue-Bug, Area-TerminalControl, Product-Terminal, Priority-1

#16407 Avoid encoding VT via win32 input mode
  src/host/inputBuffer.cpp
  src/host/inputBuffer.hpp
  src/host/outputStream.cpp
Labels: Product-Conpty, Issue-Bug, Priority-0, zInbox-Bug

#16411 Fix scroll-forward-disable setting
  src/host/outputStream.cpp
Labels: Product-Conhost, Area-VT, AutoMerge, Priority-0, zInbox-Bug

#16408 Disable win32 input mode on exit
  src/cascadia/UnitTests_TerminalCore/ConptyRoundtripTests.cpp
  src/renderer/vt/VtSequences.cpp
  src/renderer/vt/invalidate.cpp
  src/renderer/vt/state.cpp
  src/renderer/vt/vtrenderer.hpp
  src/terminal/adapter/adaptDispatch.cpp
Labels: Product-Conpty, Issue-Bug, Priority-0, zInbox-Bug

#16333 Improve conhost's scrolling performance
  src/host/consoleInformation.cpp
  src/host/renderData.cpp
  src/host/screenInfo.cpp
  src/host/screenInfo.hpp
  src/host/server.h
  src/interactivity/inc/IConsoleWindow.hpp
  src/interactivity/onecore/ConsoleWindow.cpp
  src/interactivity/onecore/ConsoleWindow.hpp
  src/interactivity/win32/window.cpp
  src/interactivity/win32/window.hpp
  src/interactivity/win32/windowproc.cpp
Labels: Product-Conhost, Area-Performance, zInbox-Bug

#16352 Fix ConPTY inputs incorrectly being treated as plain text
  src/terminal/parser/stateMachine.cpp
  src/terminal/parser/ut_parser/InputEngineTest.cpp
Labels: Product-Conpty, Issue-Bug, Priority-0, zInbox-Bug

#16188 Minor grammar fixes for the vintage AddASetting.md doc
  doc/AddASetting.md
Labels: Issue-Docs, Needs-Attention

#16444 Fix curlyline rendering in `AtlasEngine` and `GDIRenderer`
  src/renderer/atlas/BackendD3D.cpp
  src/renderer/atlas/BackendD3D.h
  src/renderer/gdi/paint.cpp
  src/renderer/gdi/state.cpp
Labels: Product-Conhost, Area-Rendering, Issue-Bug, Product-Terminal, Priority-2

#16470 Increase VtInputThread buffer size
  src/host/VtInputThread.cpp
  src/host/VtInputThread.hpp
Labels: Product-Conpty, Area-Quality

#16227 Highlight all search results while the search box is open
  src/buffer/out/search.cpp
  src/buffer/out/search.h
  src/cascadia/TerminalControl/ControlCore.cpp
  src/cascadia/TerminalCore/Terminal.hpp
  src/cascadia/TerminalCore/TerminalSelection.cpp
  src/cascadia/TerminalCore/terminalrenderdata.cpp
  src/cascadia/UnitTests_TerminalCore/ScrollTest.cpp
  src/host/renderData.cpp
  src/host/renderData.hpp
  src/host/ut_host/VtIoTests.cpp
  src/interactivity/onecore/BgfxEngine.cpp
  src/interactivity/onecore/BgfxEngine.hpp
  src/renderer/atlas/AtlasEngine.cpp
  src/renderer/atlas/AtlasEngine.h
  src/renderer/base/renderer.cpp
  src/renderer/base/renderer.hpp
  src/renderer/dx/DxRenderer.cpp
  src/renderer/dx/DxRenderer.hpp
  src/renderer/gdi/gdirenderer.hpp
  src/renderer/gdi/paint.cpp
  src/renderer/inc/IRenderData.hpp
  src/renderer/inc/IRenderEngine.hpp
  src/renderer/uia/UiaRenderer.cpp
  src/renderer/uia/UiaRenderer.hpp
  src/renderer/vt/paint.cpp
  src/renderer/vt/vtrenderer.hpp
  src/renderer/wddmcon/WddmConRenderer.cpp
  src/renderer/wddmcon/WddmConRenderer.hpp
Labels: Area-Rendering, Area-TerminalControl, Product-Terminal, Issue-Task

#16475 Put the final touches on GDI's underlines
  .github/actions/spelling/expect/expect.txt
  src/renderer/gdi/gdirenderer.hpp
  src/renderer/gdi/paint.cpp
  src/renderer/gdi/state.cpp
  src/tools/RenderingTests/main.cpp
Labels: Product-Conhost, Area-Rendering

#16467 Add missing TraceLoggingRegister calls
  src/host/exe/exemain.cpp
  src/host/telemetry.cpp
  src/host/tracing.cpp
  src/terminal/parser/tracing.cpp
Labels: Product-Conhost, Area-Interop, Issue-Bug, Priority-2, zInbox-Bug

#16463 COOKED_READ: A minor cleanup
  src/host/readDataCooked.cpp
  src/host/readDataCooked.hpp
Labels: Area-CodeHealth, Area-CookedRead

#16466 Fix parsing of chunked win32-input-mode sequences
  src/terminal/parser/IStateMachineEngine.hpp
  src/terminal/parser/InputStateMachineEngine.cpp
  src/terminal/parser/InputStateMachineEngine.hpp
  src/terminal/parser/OutputStateMachineEngine.cpp
  src/terminal/parser/OutputStateMachineEngine.hpp
  src/terminal/parser/stateMachine.cpp
  src/terminal/parser/ut_parser/StateMachineTest.cpp
Labels: Product-Conhost, Area-VT, Issue-Bug, Priority-0, zInbox-Bug

#16441 Wrap word-wise selection when the word is actually wrapped
  .github/actions/spelling/expect/04cdb9b77d6827c0202f51acd4205b017015bfff.txt
  src/buffer/out/textBuffer.cpp
  src/host/ut_host/TextBufferTests.cpp
Labels: Area-Output, Area-TerminalControl, Product-Terminal, Issue-Task
