Repository microsoft/terminal, pull requests merged in 2023-11, with the labels that each got.

#16196 Fix the fix for the fix of nearby font loading
  src/renderer/atlas/AtlasEngine.api.cpp
  src/renderer/atlas/common.h
  src/renderer/dx/DxFontInfo.cpp
Labels: Area-Fonts, Issue-Bug, Product-Terminal

#16253 Remove conhost telemetry
  .github/actions/spelling/expect/expect.txt
  src/host/consoleInformation.cpp
  src/host/directio.cpp
  src/host/exe/exemain.cpp
  src/host/getset.cpp
  src/host/init.cpp
  src/host/input.cpp
  src/host/screenInfo.cpp
  src/host/selectionInput.cpp
  src/host/srvinit.cpp
  src/host/telemetry.cpp
  src/host/telemetry.hpp
  src/host/tracing.cpp
  src/interactivity/win32/consoleKeyInfo.cpp
  src/interactivity/win32/window.cpp
  src/interactivity/win32/windowio.cpp
  src/interactivity/win32/windowproc.cpp
  src/server/ApiDispatchers.cpp
  src/server/ApiDispatchersInternal.cpp
  src/server/IoDispatchers.cpp
  src/server/ProcessHandle.cpp
Labels: AutoMerge, Area-CodeHealth

#16267 Another theoretical fix for a crash
  src/cascadia/WindowsTerminal/AppHost.cpp
Labels: Issue-Bug, Product-Terminal, Area-Windowing

#16273 Fix tabs being printed in cmd.exe prompts
  doc/COOKED_READ_DATA.md
  src/host/readDataCooked.cpp
Labels: Product-Conhost, Issue-Bug, Priority-0, Area-CookedRead

#16250 Defer package updates while the Terminal is running
  src/cascadia/CascadiaPackage/Package-Can.appxmanifest
  src/cascadia/CascadiaPackage/Package-Dev.appxmanifest
  src/cascadia/CascadiaPackage/Package-Pre.appxmanifest
  src/cascadia/CascadiaPackage/Package.appxmanifest
Labels: Product-Terminal

#16224 Fix deadlocks due to holding locks across WriteFile calls
  src/cascadia/TerminalControl/ControlCore.cpp
  src/cascadia/TerminalControl/HwndTerminal.cpp
  src/cascadia/TerminalCore/ITerminalInput.hpp
  src/cascadia/TerminalCore/Terminal.cpp
  src/cascadia/TerminalCore/Terminal.hpp
  src/cascadia/UnitTests_TerminalCore/ConptyRoundtripTests.cpp
  src/cascadia/UnitTests_TerminalCore/InputTest.cpp
  src/cascadia/UnitTests_TerminalCore/ScreenSizeLimitsTest.cpp
  src/cascadia/UnitTests_TerminalCore/ScrollTest.cpp
  src/cascadia/UnitTests_TerminalCore/SelectionTest.cpp
  src/cascadia/UnitTests_TerminalCore/TerminalApiTest.cpp
  src/cascadia/UnitTests_TerminalCore/TerminalBufferTests.cpp
Labels: Area-Input, Issue-Bug, Product-Terminal, Priority-1

#16247 Update Azure Cloud Shell for their new URI format
  .github/actions/spelling/allow/allow.txt
  src/cascadia/TerminalConnection/AzureConnection.cpp
  src/cascadia/TerminalConnection/AzureConnection.h
Labels: Issue-Bug, Product-Terminal, Area-AzureShell

#16272 Change DisclaimerStyle to be non-italic
  src/cascadia/TerminalSettingsEditor/CommonResources.xaml
Labels: Product-Terminal, Issue-Task, Needs-Second, Area-Settings UI

#16097 Support rendering of underline style and color
  .github/actions/spelling/expect/expect.txt
  src/cascadia/UnitTests_TerminalCore/ScrollTest.cpp
  src/interactivity/onecore/BgfxEngine.cpp
  src/interactivity/onecore/BgfxEngine.hpp
  src/renderer/atlas/AtlasEngine.cpp
  src/renderer/atlas/AtlasEngine.h
  src/renderer/atlas/BackendD2D.cpp
  src/renderer/atlas/BackendD3D.cpp
  src/renderer/atlas/BackendD3D.h
  src/renderer/atlas/common.h
  src/renderer/atlas/shader_common.hlsl
  src/renderer/atlas/shader_ps.hlsl
  src/renderer/atlas/shader_vs.hlsl
  src/renderer/base/RenderSettings.cpp
  src/renderer/base/renderer.cpp
  src/renderer/dx/DxRenderer.cpp
  src/renderer/dx/DxRenderer.hpp
  src/renderer/gdi/gdirenderer.hpp
  src/renderer/gdi/paint.cpp
  src/renderer/gdi/state.cpp
  src/renderer/inc/IRenderEngine.hpp
  src/renderer/inc/RenderSettings.hpp
  src/renderer/uia/UiaRenderer.cpp
  src/renderer/uia/UiaRenderer.hpp
  src/renderer/vt/paint.cpp
  src/renderer/vt/vtrenderer.hpp
  src/renderer/wddmcon/WddmConRenderer.cpp
  src/renderer/wddmcon/WddmConRenderer.hpp
  src/types/UiaTextRangeBase.cpp
Labels: Product-Conhost, Area-Rendering, Area-VT, Issue-Task

#16251 Fix leak in buffering text for UIA when unfocused
  src/renderer/uia/UiaRenderer.cpp
Labels: Issue-Bug, Area-TerminalControl, Area-Accessibility, Product-Terminal, Severity-Blocking

#16317 canary: include the correct handoff CLSIDs
  src/cascadia/CascadiaPackage/Package-Can.appxmanifest
Labels: Issue-Bug

#16323 Fix nearby fonts for DxEngine again
  src/renderer/dx/DxFontInfo.cpp
Labels: Issue-Bug

#16325 Hotfix recent AuditMode failures on CI
  src/common.build.pre.props
Labels: Area-Build

#16340 ConPTY: Fix a shutdown deadlock with WSL
  src/host/VtInputThread.cpp
  src/host/VtInputThread.hpp
  src/host/VtIo.cpp
Labels: Product-Conpty, Area-Input, Issue-Bug, AutoMerge, Priority-2, zInbox-Bug

#16349 Fix chunked soft fonts not working
  src/host/VtIo.cpp
  src/renderer/vt/state.cpp
Labels: Product-Conpty, Area-VT, Issue-Bug, AutoMerge

#16313 Fix input buffering for A APIs
  src/host/inputBuffer.cpp
Labels: Product-Conhost, Area-Input, Area-Server, Issue-Bug, AutoMerge, Priority-1

#16324 Fix font preview for conhost
  src/propsheet/misc.cpp
Labels: Product-Conhost, Area-Fonts, Issue-Bug, AutoMerge, Severity-Blocking

#16298 Fix Control+Space not sent to program running in terminal
  src/host/inputBuffer.cpp
Labels: Area-Input, Issue-Bug, Product-Terminal, Priority-2, Needs-Discussion

#16334 Fix scrolling with SetConsoleWindowInfo
  src/renderer/base/renderer.cpp
Labels: Product-Conhost, Area-Output, Issue-Bug

#16358 Update paths to use linking within repo instead of github URL
  CONTRIBUTING.md
  README.md
  SUPPORT.md
  doc/roadmap-2022.md
  doc/roadmap-2023.md
  doc/specs/#1571 - New Tab Menu Customization/#1571 - New Tab Menu Customization.md
  doc/specs/#1595 - Suggestions UI/Suggestions-UI.md
  doc/specs/#2046 - Unified keybindings and commands, and synthesized action names.md
  doc/specs/#5000 - Process Model 2.0/#1032 - Elevation Quality of Life Improvements.md
  doc/specs/#5000 - Process Model 2.0/#4472 - Windows Terminal Session Management.md
  doc/specs/#653 - Quake Mode/#653 - Quake Mode.md
  doc/specs/#6899 - Action IDs/#6899 - Action IDs.md
  doc/terminal-v2-roadmap.md
Labels: Issue-Docs, Priority-3

#16335 Fix dwControlKeyState always including ENHANCED_KEY
  src/terminal/parser/InputStateMachineEngine.cpp
Labels: Product-Conpty, Area-Input, Issue-Bug, Priority-1, Impact-Correctness, Automerge-Not-Compatible
