Repository microsoft/terminal, pull requests merged in 2023-07, with the labels that each got.

#15499 Add an ASCII fast-pass to ROW
  src/buffer/out/Row.cpp
  src/buffer/out/Row.hpp
Labels: Product-Conhost, Area-Performance

#15552 Added: Copy text without dismissing the selection
  doc/cascadia/profiles.schema.json
  src/cascadia/TerminalApp/AppActionHandlers.cpp
  src/cascadia/TerminalApp/TerminalPage.cpp
  src/cascadia/TerminalApp/TerminalPage.h
  src/cascadia/TerminalControl/TermControl.cpp
  src/cascadia/TerminalControl/TermControl.h
  src/cascadia/TerminalControl/TermControl.idl
  src/cascadia/TerminalSettingsModel/ActionArgs.cpp
  src/cascadia/TerminalSettingsModel/ActionArgs.h
  src/cascadia/TerminalSettingsModel/ActionArgs.idl
Labels: Area-TerminalControl, Area-Settings, Needs-Author-Feedback, Product-Terminal, AutoMerge, Issue-Task

#15671 Clean up InputBuffer coalescing and preprocessing
  src/host/inputBuffer.cpp
  src/host/inputBuffer.hpp
  src/host/ut_host/InputBufferTests.cpp
Labels: Product-Conhost, Area-Input, Issue-Bug, AutoMerge, Area-CodeHealth, Priority-3

#15692 Add ConsoleMonitor: A tool for displaying ConPTY contents
  .github/actions/spelling/allow/apis.txt
  OpenConsole.sln
  src/tools/ConsoleMonitor/ConsoleMonitor.exe.manifest
  src/tools/ConsoleMonitor/ConsoleMonitor.vcxproj
  src/tools/ConsoleMonitor/ConsoleMonitor.vcxproj.filters
  src/tools/ConsoleMonitor/main.cpp
  src/tools/ConsoleMonitor/pch.cpp
  src/tools/ConsoleMonitor/pch.h
Labels: Product-Conpty, AutoMerge, Area-Quality

#15714 Fix C2664 errors
  src/cascadia/TerminalApp/TabManagement.cpp
  src/cascadia/TerminalControl/TermControl.cpp
Labels: Issue-Bug, AutoMerge, Product-Meta, Area-CodeHealth

#15677 Added background to CommandKeyChord
  src/cascadia/TerminalApp/CommandPalette.xaml
Labels: AutoMerge

#15672 Clean up WriteConsoleInputA conversion
  src/host/directio.cpp
  src/host/ft_host/CJK_DbcsTests.cpp
Labels: AutoMerge, Area-CodeHealth

#15648 Add support for colon separated sub-parameters
  src/terminal/adapter/DispatchTypes.hpp
  src/terminal/adapter/adaptDispatch.hpp
  src/terminal/adapter/adaptDispatchGraphics.cpp
  src/terminal/parser/OutputStateMachineEngine.cpp
  src/terminal/parser/OutputStateMachineEngine.hpp
  src/terminal/parser/stateMachine.cpp
  src/terminal/parser/stateMachine.hpp
  src/terminal/parser/ut_parser/OutputEngineTest.cpp
Labels: Product-Conhost, Area-VT, Issue-Task, Priority-2

#15686 Let marks be cleared by `clear` (and friends)
  src/buffer/out/textBuffer.cpp
  src/buffer/out/textBuffer.hpp
  src/cascadia/TerminalControl/ControlCore.cpp
  src/cascadia/TerminalControl/ControlCore.h
  src/cascadia/TerminalCore/Terminal.cpp
  src/cascadia/TerminalCore/Terminal.hpp
  src/cascadia/TerminalCore/TerminalApi.cpp
  src/host/outputStream.cpp
  src/host/outputStream.hpp
  src/terminal/adapter/DispatchTypes.hpp
  src/terminal/adapter/ITerminalApi.hpp
  src/terminal/adapter/adaptDispatch.cpp
  src/terminal/adapter/ut_adapter/adapterTest.cpp
Labels: Issue-Bug, Area-TerminalControl, Product-Terminal

#14393 Add support for broadcasting to all panes in a tab
  .github/actions/spelling/expect/expect.txt
  src/cascadia/TerminalApp/App.xaml
  src/cascadia/TerminalApp/AppActionHandlers.cpp
  src/cascadia/TerminalApp/CommandPalette.xaml
  src/cascadia/TerminalApp/Pane.cpp
  src/cascadia/TerminalApp/Pane.h
  src/cascadia/TerminalApp/TabHeaderControl.xaml
  src/cascadia/TerminalApp/TerminalPage.cpp
  src/cascadia/TerminalApp/TerminalTab.cpp
  src/cascadia/TerminalApp/TerminalTab.h
  src/cascadia/TerminalApp/TerminalTabStatus.h
  src/cascadia/TerminalApp/TerminalTabStatus.idl
  src/cascadia/TerminalControl/EventArgs.cpp
  src/cascadia/TerminalControl/EventArgs.h
  src/cascadia/TerminalControl/EventArgs.idl
  src/cascadia/TerminalControl/TermControl.cpp
  src/cascadia/TerminalControl/TermControl.h
  src/cascadia/TerminalControl/TermControl.idl
  src/cascadia/TerminalSettingsModel/ActionAndArgs.cpp
  src/cascadia/TerminalSettingsModel/AllShortcutActions.h
  src/cascadia/TerminalSettingsModel/Resources/en-US/Resources.resw
Labels: Issue-Feature, Area-Input, Area-User Interface, Product-Terminal

#15424 Refrigerate our threads for later reuse
  src/cascadia/WindowsTerminal/AppHost.cpp
  src/cascadia/WindowsTerminal/AppHost.h
  src/cascadia/WindowsTerminal/BaseWindow.h
  src/cascadia/WindowsTerminal/IslandWindow.cpp
  src/cascadia/WindowsTerminal/IslandWindow.h
  src/cascadia/WindowsTerminal/NonClientIslandWindow.cpp
  src/cascadia/WindowsTerminal/NonClientIslandWindow.h
  src/cascadia/WindowsTerminal/WindowEmperor.cpp
  src/cascadia/WindowsTerminal/WindowEmperor.h
  src/cascadia/WindowsTerminal/WindowThread.cpp
  src/cascadia/WindowsTerminal/WindowThread.h
  src/types/inc/utils.hpp
  src/types/utils.cpp
Labels: Issue-Bug

#15282 Add an action to display toast with the CWD of the Terminal
  src/cascadia/TerminalApp/AppActionHandlers.cpp
  src/cascadia/TerminalApp/TerminalPage.cpp
  src/cascadia/TerminalApp/TerminalPage.h
  src/cascadia/TerminalApp/TerminalPage.xaml
  src/cascadia/TerminalSettingsModel/ActionAndArgs.cpp
  src/cascadia/TerminalSettingsModel/AllShortcutActions.h
  src/cascadia/TerminalSettingsModel/Resources/en-US/Resources.resw
Labels: Area-Commandline, zBugBash-Consider

#15679 Add support for running profiles from Add tab menu as admin without a keyboard
  src/cascadia/TerminalApp/Resources/en-US/Resources.resw
  src/cascadia/TerminalApp/TerminalPage.cpp
  src/cascadia/TerminalApp/TerminalPage.h
Labels: Area-User Interface, Product-Terminal, Issue-Task

#14792 Spec for shell integration marks
  doc/specs/#11000 - Marks/Shell-Integration-Marks.md
  doc/specs/#11000 - Marks/ftcs-diagram.png
  doc/specs/#11000 - Marks/vscode-shell-integration-gutter-mark.png
Labels: Issue-Feature, Issue-Docs

#15725 Replace deprecated await winrt::apartment_context pattern
  src/cascadia/WindowsTerminal/AppHost.cpp
Labels: Product-Terminal, Issue-Task, Area-CodeHealth

#15729 Add support for ITU's T.416 - ODA SGR (38/48) sequence
  src/terminal/adapter/DispatchTypes.hpp
  src/terminal/adapter/adaptDispatch.cpp
  src/terminal/adapter/adaptDispatch.hpp
  src/terminal/adapter/adaptDispatchGraphics.cpp
  src/terminal/adapter/ut_adapter/adapterTest.cpp
Labels: Product-Conhost, Area-VT, Issue-Task

#15737 Consolidate and clean up all API logging
  src/host/tracing.cpp
  src/host/tracing.hpp
  src/server/ApiDispatchers.cpp
  src/server/ApiSorter.cpp
  src/server/ProcessHandle.cpp
  src/server/ProcessHandle.h
Labels: AutoMerge

#15756 Add UIA element grouping to SettingsContainer
  src/cascadia/TerminalSettingsEditor/SettingContainerStyle.xaml
Labels: Issue-Bug, Area-Accessibility, Product-Terminal

#15762 Fix Default Terminal and Color Scheme ComboBoxes cropping at 200% Text Size
  src/cascadia/TerminalSettingsEditor/Appearances.xaml
  src/cascadia/TerminalSettingsEditor/Launch.xaml
Labels: Issue-Bug, Area-Accessibility, Product-Terminal
