Repository microsoft/terminal, pull requests merged in 2024-07, with the labels that each got.

#16479 Theme for settings
  src/cascadia/TerminalSettingsEditor/MainPage.cpp
  src/cascadia/TerminalSettingsModel/MTSMSettings.h
  src/cascadia/TerminalSettingsModel/Theme.cpp
  src/cascadia/TerminalSettingsModel/Theme.h
  src/cascadia/TerminalSettingsModel/Theme.idl
Labels: Product-Terminal, Issue-Task, Area-Settings UI, Area-Theming

#17497 Initialize all SixelParser members
  src/terminal/adapter/SixelParser.hpp
Labels: Area-CodeHealth

#16513 Add ability to save input action from command line
  src/cascadia/TerminalApp/AppActionHandlers.cpp
  src/cascadia/TerminalApp/AppCommandlineArgs.cpp
  src/cascadia/TerminalApp/AppCommandlineArgs.h
  src/cascadia/TerminalApp/Resources/en-US/Resources.resw
  src/cascadia/TerminalApp/TerminalAppLib.vcxproj
  src/cascadia/TerminalApp/TerminalPage.h
  src/cascadia/TerminalApp/TerminalPage.idl
  src/cascadia/TerminalApp/TerminalPage.xaml
  src/cascadia/TerminalSettingsModel/ActionAndArgs.cpp
  src/cascadia/TerminalSettingsModel/ActionArgs.cpp
  src/cascadia/TerminalSettingsModel/ActionArgs.h
  src/cascadia/TerminalSettingsModel/ActionArgs.idl
  src/cascadia/TerminalSettingsModel/ActionMap.cpp
  src/cascadia/TerminalSettingsModel/ActionMap.h
  src/cascadia/TerminalSettingsModel/ActionMap.idl
  src/cascadia/TerminalSettingsModel/AllShortcutActions.h
  src/cascadia/TerminalSettingsModel/Resources/en-US/Resources.resw
  src/features.xml
Labels: Area-Settings, Product-Terminal, Issue-Task

#17143 Improve Viewport and Viewport::WalkInBounds
  src/buffer/out/textBuffer.cpp
  src/cascadia/TerminalControl/ControlCore.cpp
  src/cascadia/TerminalControl/HwndTerminal.cpp
  src/cascadia/TerminalCore/Terminal.cpp
  src/cascadia/TerminalCore/TerminalSelection.cpp
  src/cascadia/UnitTests_TerminalCore/ConptyRoundtripTests.cpp
  src/host/VtIo.cpp
  src/host/_output.cpp
  src/host/outputStream.cpp
  src/host/screenInfo.cpp
  src/host/selectionInput.cpp
  src/host/ut_host/ScreenBufferTests.cpp
  src/host/ut_host/TextBufferTests.cpp
  src/host/ut_host/ViewportTests.cpp
  src/renderer/base/renderer.cpp
  src/terminal/adapter/adaptDispatch.cpp
  src/types/UiaTextRangeBase.cpp
  src/types/inc/viewport.hpp
  src/types/viewport.cpp
Labels: Area-CodeHealth

#17526 Fix qps-ploc generation for store translations
  build/scripts/Generate-PseudoLocalizations.ps1
  tools/ConvertTo-PseudoLocalization.ps1
Labels: Area-Build

#17530 Fix more PDP ploc related issues
  build/scripts/Copy-ContextMenuResourcesToCascadiaPackage.ps1
  build/scripts/Generate-PseudoLocalizations.ps1
  tools/ConvertTo-PseudoLocalization.ps1
Labels: Area-Build

#17536 AtlasEngine: Fix a buffer overrun
  src/renderer/atlas/BackendD3D.cpp
Labels: Issue-Bug, Product-Terminal, Priority-1, Area-AtlasEngine

#17544 Fix cursor invalidation with horizontal scrolling
  src/renderer/base/renderer.cpp
Labels: Product-Conhost, Area-Rendering, Issue-Bug, Priority-3

#17445 Use VT for COOKED_READ_DATA
  doc/COOKED_READ_DATA.md
  src/buffer/out/cursor.cpp
  src/buffer/out/cursor.h
  src/cascadia/TerminalCore/terminalrenderdata.cpp
  src/host/VtIo.cpp
  src/host/VtIo.hpp
  src/host/_stream.cpp
  src/host/_stream.h
  src/host/readDataCooked.cpp
  src/host/readDataCooked.hpp
  src/host/renderData.cpp
  src/host/screenInfo.cpp
  src/host/screenInfo.hpp
  src/host/utils.cpp
  src/host/utils.hpp
Labels: Product-Conhost, Area-VT, Area-CookedRead

#17543 Fix double paste when CF_UNICODETEXT & CF_HDROP are present
  src/interactivity/win32/Clipboard.cpp
Labels: Product-Conhost, Issue-Bug, Area-User Interface, Priority-3

#17537 Create a base class for all pane content events
  src/cascadia/TerminalApp/BasicPaneEvents.h
  src/cascadia/TerminalApp/ScratchpadContent.h
  src/cascadia/TerminalApp/SettingsPaneContent.h
  src/cascadia/TerminalApp/SnippetsPaneContent.h
  src/cascadia/TerminalApp/TerminalPaneContent.h
Labels: Area-CodeHealth

#17571 Make til/rand noexcept-correct
  src/cascadia/UnitTests_SettingsModel/TerminalSettingsTests.cpp
  src/inc/til/rand.h
  src/terminal/parser/ut_parser/Base64Test.cpp
Labels: Area-CodeHealth

#17573 Abstract Write/FillOutput APIs with FillConsoleImpl
  src/buffer/out/OutputCellIterator.hpp
  src/buffer/out/OutputCellView.hpp
  src/host/ApiRoutines.h
  src/host/_output.cpp
  src/server/ApiDispatchers.cpp
  src/server/IApiRoutines.h
Labels: Product-Conpty

#17566 Add helper functions for pipes
  .github/actions/spelling/expect/expect.txt
  src/types/inc/utils.hpp
  src/types/utils.cpp
Labels: Product-Conpty

#17569 Remove CleanupGlobalFont from tests
  src/cascadia/UnitTests_TerminalCore/ConptyRoundtripTests.cpp
  src/host/ut_host/ApiRoutinesTests.cpp
  src/host/ut_host/ClipboardTests.cpp
  src/host/ut_host/ConptyOutputTests.cpp
  src/host/ut_host/ObjectTests.cpp
  src/host/ut_host/ScreenBufferTests.cpp
  src/host/ut_host/SearchTests.cpp
  src/host/ut_host/SelectionTests.cpp
  src/host/ut_host/TextBufferIteratorTests.cpp
  src/host/ut_host/TextBufferTests.cpp
  src/host/ut_host/UtilsTests.cpp
  src/inc/test/CommonState.hpp
  src/interactivity/win32/ut_interactivity_win32/UiaTextRangeTests.cpp
Labels: Product-Conpty, Area-CodeHealth

#17570 Move FindActionableControlCharacter to Types
  src/terminal/parser/stateMachine.cpp
  src/types/inc/utils.hpp
  src/types/utils.cpp
Labels: Product-Conpty, Area-CodeHealth

#17572 Remove the --vtmode flag
  src/host/ConsoleArguments.cpp
  src/host/ConsoleArguments.hpp
  src/host/VtIo.cpp
  src/host/VtIo.hpp
  src/host/ut_host/ConsoleArgumentsTests.cpp
  src/host/ut_host/VtIoTests.cpp
  src/inc/VtIoModes.hpp
Labels: Product-Conpty

#17574 Implement a timeout for PSEUDOCONSOLE_INHERIT_CURSOR
  src/host/VtInputThread.cpp
  src/host/VtInputThread.hpp
  src/host/VtIo.cpp
  src/terminal/parser/InputStateMachineEngine.cpp
  src/terminal/parser/InputStateMachineEngine.hpp
Labels: Product-Conpty, Area-Server, Issue-Bug, Priority-1

#17575 Add ITerminalHandoff3 in preparation for overlapped pipes
  src/cascadia/CascadiaPackage/Package-Can.appxmanifest
  src/cascadia/CascadiaPackage/Package-Dev.appxmanifest
  src/cascadia/CascadiaPackage/Package-Pre.appxmanifest
  src/cascadia/CascadiaPackage/Package.appxmanifest
  src/cascadia/TerminalConnection/CTerminalHandoff.cpp
  src/cascadia/TerminalConnection/CTerminalHandoff.h
  src/cascadia/TerminalConnection/ConptyConnection.cpp
  src/cascadia/TerminalConnection/ConptyConnection.h
  src/cascadia/UnitTests_Remoting/RemotingTests.cpp
  src/host/proxy/IConsoleHandoff.idl
  src/host/proxy/ITerminalHandoff.idl
  src/host/srvinit.cpp
  src/inc/til/u8u16convert.h
Labels: Product-Conpty

#17567 Fix various Read/WriteConsoleOutput bugs
  src/host/directio.cpp
  src/host/directio.h
  src/host/ft_host/API_OutputTests.cpp
  src/host/ut_host/ViewportTests.cpp
  src/types/viewport.cpp
  tools/OpenConsole.psm1
Labels: Product-Conpty, Issue-Bug

#17582 AtlasEngine: Generate shader PDBs in Release builds
  src/renderer/atlas/atlas.vcxproj
Labels: Area-Build

#17586 Use a PasswordBox instead of a TextBox for the AzureOpenAI key
  .github/actions/spelling/allow/allow.txt
  src/cascadia/TerminalSettingsEditor/AISettings.cpp
  src/cascadia/TerminalSettingsEditor/AISettings.xaml
Labels: AutoMerge

#17583 AtlasEngine: Fix dirty rects during scrolling
  src/renderer/atlas/AtlasEngine.api.cpp
  src/renderer/atlas/AtlasEngine.cpp
  src/renderer/atlas/AtlasEngine.h
  src/renderer/atlas/common.h
Labels: Issue-Bug, Product-Terminal, Priority-3, Area-AtlasEngine

#17581 AtlasEngine: Implement sixels
  src/buffer/out/ImageSlice.cpp
  src/buffer/out/ImageSlice.hpp
  src/buffer/out/Row.cpp
  src/buffer/out/Row.hpp
  src/buffer/out/textBuffer.cpp
  src/renderer/atlas/AtlasEngine.cpp
  src/renderer/atlas/AtlasEngine.r.cpp
  src/renderer/atlas/BackendD2D.cpp
  src/renderer/atlas/BackendD2D.h
  src/renderer/atlas/BackendD3D.cpp
  src/renderer/atlas/BackendD3D.h
  src/renderer/atlas/common.h
  src/renderer/base/renderer.cpp
  src/terminal/adapter/SixelParser.cpp
Labels: Product-Terminal, Area-AtlasEngine

#17553 Add an "export chat history" button to Terminal Chat
  src/cascadia/QueryExtension/ExtensionPalette.cpp
  src/cascadia/QueryExtension/ExtensionPalette.h
  src/cascadia/QueryExtension/ExtensionPalette.idl
  src/cascadia/QueryExtension/ExtensionPalette.xaml
  src/cascadia/QueryExtension/Resources/en-US/Resources.resw
  src/cascadia/TerminalApp/Resources/en-US/Resources.resw
  src/cascadia/TerminalApp/TabManagement.cpp
  src/cascadia/TerminalApp/TerminalPage.cpp
  src/cascadia/TerminalApp/TerminalPage.h
Labels: AutoMerge

#17568 Fix colors getting lost on reflow
  src/buffer/out/textBuffer.cpp
  src/buffer/out/ut_textbuffer/ReflowTests.cpp
Labels: Area-Output, Issue-Bug, Priority-3

#17635 Fix alt-numpad events
  src/interactivity/base/EventSynthesis.cpp
Labels: Product-Conhost, Issue-Bug, Priority-0

#17636 Fix sixels in BackendD2D
  src/renderer/atlas/BackendD2D.cpp
Labels: Issue-Bug, Area-AtlasEngine
