Repository microsoft/terminal, pull requests merged in 2024-08, with the labels that each got.

#17644 Potential hotfix for a MSVC 14.40.33807 miscompilation
  src/cascadia/TerminalSettingsEditor/Utils.cpp
Labels: Issue-Bug, Severity-Crash, Product-Terminal, Priority-0, Area-Settings UI

#17653 wint_t is not wchar_t
  src/cascadia/TerminalSettingsEditor/Utils.cpp
Labels: Issue-Bug, Product-Terminal, Area-Settings UI

#17674 atlas,d2d: overdraw the background bitmap by one cell on all sides
  src/renderer/atlas/BackendD2D.cpp
  src/renderer/atlas/BackendD2D.h
Labels: Issue-Bug

#17648 Update scratch project dependencies
  scratch/ScratchIslandApp/Package/Package.wapproj
  scratch/ScratchIslandApp/SampleApp/SampleAppLib.vcxproj
  scratch/ScratchIslandApp/SampleApp/dll/SampleApp.vcxproj
  scratch/ScratchIslandApp/SampleApp/packages.config
  scratch/ScratchIslandApp/WindowExe/WindowExe.vcxproj
  scratch/ScratchIslandApp/WindowExe/packages.config
Labels: Area-CodeHealth

#17667 Return strings directly from read_file_as_utf8_string_if_exists
  src/cascadia/TerminalSettingsModel/ActionMap.cpp
  src/cascadia/TerminalSettingsModel/ApplicationState.cpp
  src/cascadia/TerminalSettingsModel/ApplicationState.h
  src/cascadia/TerminalSettingsModel/CascadiaSettingsSerialization.cpp
  src/inc/til/io.h
Labels: Area-CodeHealth

#17646 Be less strict about trivialities
  src/inc/til/small_vector.h
Labels: Area-CodeHealth

#17645 Address feedback from #17510
  src/host/VtIo.cpp
  src/host/VtIo.hpp
  src/host/_output.cpp
  src/host/_stream.cpp
  src/host/consoleInformation.cpp
  src/host/getset.cpp
  src/host/ut_host/VtIoTests.cpp
  src/interactivity/base/InteractivityFactory.cpp
  src/terminal/adapter/adaptDispatch.cpp
  src/terminal/parser/stateMachine.hpp
Labels: Area-CodeHealth

#17516 Avoid covering current search highlight with search box
  src/cascadia/TerminalControl/ControlCore.cpp
  src/cascadia/TerminalControl/ControlCore.h
  src/cascadia/TerminalControl/ControlCore.idl
  src/cascadia/TerminalControl/TermControl.cpp
  src/cascadia/TerminalControl/TermControl.h
  src/cascadia/TerminalCore/Terminal.cpp
  src/cascadia/TerminalCore/Terminal.hpp
Labels: Area-TerminalControl, Product-Terminal, Issue-Task, Priority-3

#17668 Fix cooked read reflow under ConPTY
  src/host/readDataCooked.cpp
  src/host/readDataCooked.hpp
Labels: Product-Conpty, Issue-Bug, Product-Terminal, Priority-2

#17679 AtlasEngine: Fix curly line rendering on rows with line renditions
  src/renderer/atlas/shader_ps.hlsl
Labels: Issue-Bug, Priority-3, Area-AtlasEngine

#17660 Add support for the VT answerback capability
  .github/actions/spelling/expect/expect.txt
  dep/Console/winconp.h
  doc/cascadia/profiles.schema.json
  src/cascadia/TerminalCore/ICoreSettings.idl
  src/cascadia/TerminalCore/Terminal.cpp
  src/cascadia/TerminalCore/Terminal.hpp
  src/cascadia/TerminalCore/TerminalApi.cpp
  src/cascadia/TerminalSettingsModel/MTSMSettings.h
  src/cascadia/TerminalSettingsModel/Profile.idl
  src/cascadia/TerminalSettingsModel/TerminalSettings.cpp
  src/cascadia/TerminalSettingsModel/TerminalSettings.h
  src/cascadia/inc/ControlProperties.h
  src/host/outputStream.cpp
  src/host/outputStream.hpp
  src/host/settings.cpp
  src/host/settings.hpp
  src/propslib/RegistrySerialization.cpp
  src/terminal/adapter/ITermDispatch.hpp
  src/terminal/adapter/ITerminalApi.hpp
  src/terminal/adapter/adaptDispatch.cpp
  src/terminal/adapter/adaptDispatch.hpp
  src/terminal/adapter/termDispatch.hpp
  src/terminal/adapter/ut_adapter/adapterTest.cpp
  src/terminal/parser/OutputStateMachineEngine.cpp
Labels: Product-Conhost, Area-VT, Issue-Task

#16007 Upgrade fmt to 11.0.2
  .github/actions/spelling/expect/expect.txt
  src/cascadia/TerminalApp/AppActionHandlers.cpp
  src/cascadia/TerminalApp/AppLogic.cpp
  src/cascadia/TerminalApp/CommandPalette.cpp
  src/cascadia/TerminalApp/Jumplist.cpp
  src/cascadia/TerminalApp/SnippetsPaneContent.h
  src/cascadia/TerminalApp/SuggestionsControl.cpp
  src/cascadia/TerminalApp/TabManagement.cpp
  src/cascadia/TerminalApp/TerminalPage.cpp
  src/cascadia/TerminalApp/TerminalTab.cpp
  src/cascadia/TerminalApp/TerminalWindow.cpp
  src/cascadia/TerminalConnection/AzureConnection.cpp
  src/cascadia/TerminalConnection/ConptyConnection.cpp
  src/cascadia/TerminalConnection/ConptyConnection.h
  src/cascadia/TerminalControl/SearchBoxControl.cpp
  src/cascadia/TerminalControl/TermControl.cpp
  src/cascadia/TerminalSettingsEditor/ColorSchemeViewModel.cpp
  src/cascadia/TerminalSettingsEditor/ColorSchemesPageViewModel.cpp
  src/cascadia/TerminalSettingsEditor/LaunchViewModel.cpp
  src/cascadia/TerminalSettingsEditor/SettingContainer.cpp
  src/cascadia/TerminalSettingsModel/ActionAndArgs.cpp
  src/cascadia/TerminalSettingsModel/ActionAndArgs.h
  src/cascadia/TerminalSettingsModel/ActionArgs.cpp
  src/cascadia/TerminalSettingsModel/ActionMap.cpp
  src/cascadia/TerminalSettingsModel/CascadiaSettings.cpp
  src/cascadia/TerminalSettingsModel/CascadiaSettingsSerialization.cpp
  src/cascadia/TerminalSettingsModel/Command.cpp
  src/cascadia/TerminalSettingsModel/DefaultTerminal.cpp
  src/cascadia/TerminalSettingsModel/DefaultTerminal.h
  src/cascadia/WinRTUtils/inc/LibraryResources.h
  src/cascadia/WinRTUtils/inc/WtExeUtils.h
  src/cascadia/WindowsTerminal/AppHost.cpp
  src/cascadia/WindowsTerminal/WindowEmperor.cpp
  src/cascadia/inc/cppwinrt_utils.h
  src/inc/LibraryIncludes.h
  src/renderer/atlas/pch.h
  src/terminal/adapter/DispatchTypes.hpp
  src/terminal/adapter/adaptDispatch.cpp
  src/types/UiaTracing.cpp
  src/types/utils.cpp
  vcpkg.json
Labels: Product-Meta, Issue-Task, Area-CodeHealth

#17654 Fix session restoration of full buffers
  src/cascadia/TerminalControl/ControlCore.cpp
  src/cascadia/TerminalCore/TerminalApi.cpp
Labels: Issue-Bug, Area-TerminalControl, Needs-Attention, Product-Terminal, Priority-2

#17681 Remove CHAR_INFO munging for raster fonts
  src/buffer/out/OutputCellIterator.cpp
  src/host/dbcs.cpp
  src/host/dbcs.h
  src/host/directio.cpp
  src/host/ft_host/CJK_DbcsTests.cpp
  src/host/ut_host/DbcsTests.cpp
  src/host/ut_host/Host.UnitTests.vcxproj
  src/host/ut_host/Host.UnitTests.vcxproj.filters
  src/host/ut_host/sources
Labels: Product-Conhost, Area-Output

#17706 Switch to the new and beautiful VS Dev Shell icons
  src/cascadia/CascadiaPackage/ProfileIcons/vs-cmd.scale-100.png
  src/cascadia/CascadiaPackage/ProfileIcons/vs-cmd.scale-150.png
  src/cascadia/CascadiaPackage/ProfileIcons/vs-cmd.scale-200.png
  src/cascadia/CascadiaPackage/ProfileIcons/vs-powershell.scale-100.png
  src/cascadia/CascadiaPackage/ProfileIcons/vs-powershell.scale-150.png
  src/cascadia/CascadiaPackage/ProfileIcons/vs-powershell.scale-200.png
  src/cascadia/CascadiaPackage/ProfileIcons/vs-pwsh.scale-100.png
  src/cascadia/CascadiaPackage/ProfileIcons/vs-pwsh.scale-150.png
  src/cascadia/CascadiaPackage/ProfileIcons/vs-pwsh.scale-200.png
  src/cascadia/TerminalSettingsModel/CascadiaSettingsSerialization.cpp
  src/cascadia/TerminalSettingsModel/Profile.cpp
  src/cascadia/TerminalSettingsModel/VisualStudioGenerator.cpp
  src/cascadia/TerminalSettingsModel/VisualStudioGenerator.h
  src/cascadia/TerminalSettingsModel/VsDevCmdGenerator.h
  src/cascadia/TerminalSettingsModel/VsDevShellGenerator.h
Labels: Issue-Feature, Area-User Interface, Product-Terminal

#17710 Use a plain char array to pass connection input
  src/cascadia/TerminalApp/DebugTapConnection.cpp
  src/cascadia/TerminalApp/DebugTapConnection.h
  src/cascadia/TerminalAzBridge/main.cpp
  src/cascadia/TerminalConnection/AzureConnection.cpp
  src/cascadia/TerminalConnection/AzureConnection.h
  src/cascadia/TerminalConnection/ConptyConnection.cpp
  src/cascadia/TerminalConnection/ConptyConnection.h
  src/cascadia/TerminalConnection/EchoConnection.cpp
  src/cascadia/TerminalConnection/EchoConnection.h
  src/cascadia/TerminalConnection/ITerminalConnection.idl
  src/cascadia/TerminalControl/ControlCore.cpp
  src/cascadia/TerminalSettingsEditor/PreviewConnection.cpp
  src/cascadia/TerminalSettingsEditor/PreviewConnection.h
  src/cascadia/UnitTests_Control/ControlCoreTests.cpp
  src/cascadia/UnitTests_Control/ControlInteractivityTests.cpp
  src/cascadia/UnitTests_Control/MockConnection.h
  src/cascadia/inc/cppwinrt_utils.h
Labels: Issue-Bug, Area-TerminalConnection, Product-Terminal, Priority-3

#17704 Align the OSS ConPTY API with Windows 11 24H2
  src/cascadia/TerminalConnection/ConptyConnection.cpp
  src/inc/conpty-static.h
  src/winconpty/dll/winconpty.def
  src/winconpty/ft_pty/ConPtyTests.cpp
  src/winconpty/winconpty.cpp
  src/winconpty/winconpty.h
Labels: Product-Conpty, Area-CodeHealth

#17696 schema: add reloadEnvironmentVariables to newTerminalArgs
  doc/cascadia/profiles.schema.json
Labels: Issue-Docs, Product-Terminal, Priority-3, Area-Schema

#17723 Fix a misdiagnosis in MSVC 17.11
  src/buffer/out/OutputCell.cpp
  src/buffer/out/OutputCellIterator.cpp
  src/buffer/out/OutputCellView.cpp
  src/buffer/out/textBuffer.cpp
Labels: Area-Build

#17724 Fix misalignment of Sixel image slices
  src/buffer/out/ImageSlice.cpp
  src/renderer/gdi/paint.cpp
Labels: Area-Rendering, Issue-Bug, Product-Terminal

#16595 chore: Update to TAEF 10.93.240607003
  build/packages.config
  dep/nuget/packages.config
  src/cascadia/WindowsTerminal_UIATests/WindowsTerminal.UIA.Tests.csproj
  src/common.nugetversions.props
  src/common.nugetversions.targets
  src/host/ft_uia/Host.Tests.UIA.csproj
  tools/OpenConsole.psm1
  tools/razzle.cmd
Labels: Tracking-External

#17725 atlas: draw selection colors as background/foreground instead of alpha overlay
  src/cascadia/TerminalControl/HwndTerminal.cpp
  src/cascadia/TerminalControl/HwndTerminal.hpp
  src/cascadia/WpfTerminalControl/TerminalTheme.cs
  src/cascadia/WpfTerminalTestNetCore/MainWindow.xaml.cs
  src/renderer/atlas/AtlasEngine.api.cpp
  src/renderer/atlas/AtlasEngine.cpp
  src/renderer/atlas/AtlasEngine.h
  src/renderer/atlas/BackendD2D.cpp
  src/renderer/atlas/BackendD3D.cpp
  src/renderer/atlas/BackendD3D.h
  src/renderer/atlas/common.h
  src/renderer/atlas/shader_common.hlsl
Labels: Area-Rendering, Area-Fonts, Product-Terminal, Issue-Task

#17731 Restore the ability to disable checking for URLs
  src/cascadia/TerminalCore/Terminal.cpp
  src/cascadia/UnitTests_TerminalCore/TerminalBufferTests.cpp
Labels: Issue-Bug, Area-TerminalControl, Product-Terminal, Priority-3

#17738 Fix input sequences split across the buffer boundary
  src/terminal/parser/stateMachine.cpp
Labels: Product-Conhost, Area-Input, Area-VT, Issue-Bug, Priority-1

#17714 Fix session persistence when the session ends
  src/cascadia/Remoting/Monarch.cpp
  src/cascadia/Remoting/Monarch.h
  src/cascadia/Remoting/Monarch.idl
  src/cascadia/Remoting/Peasant.cpp
  src/cascadia/Remoting/Peasant.h
  src/cascadia/Remoting/Peasant.idl
  src/cascadia/Remoting/WindowManager.cpp
  src/cascadia/Remoting/WindowManager.h
  src/cascadia/Remoting/WindowManager.idl
  src/cascadia/UnitTests_Remoting/RemotingTests.cpp
  src/cascadia/WindowsTerminal/AppHost.cpp
  src/cascadia/WindowsTerminal/AppHost.h
Labels: Issue-Bug, Product-Terminal, Area-Windowing

#17751 Fix a crash during settings update
  src/cascadia/TerminalApp/TerminalWindow.cpp
Labels: Issue-Bug, Severity-Crash, Product-Terminal, Priority-1, Area-Windowing

#17748 Fix a crash when disabling the ASB
  src/host/_stream.cpp
Labels: Area-Output, Issue-Bug, Severity-Crash, Product-Terminal

#17695 Fix UIA RangeFromPoint API
  src/interactivity/win32/uiaTextRange.cpp
  src/interactivity/win32/uiaTextRange.hpp
  src/types/TermControlUiaTextRange.cpp
  src/types/TermControlUiaTextRange.hpp
  src/types/UiaTextRangeBase.cpp
  src/types/UiaTextRangeBase.hpp
Labels: Issue-Bug, Area-Accessibility, Product-Terminal

#17750 Fix pane event handlers being unbound
  src/cascadia/TerminalApp/Pane.cpp
Labels: Issue-Bug, Area-User Interface, Product-Terminal, Priority-2

#17757 ConPTY: Inject W32IM sequences
  src/host/_stream.cpp
  src/terminal/adapter/adaptDispatch.cpp
  src/terminal/parser/stateMachine.hpp
Labels: Area-Input, Area-VT, Issue-Bug

#17758 `x-save` the commandline in the current window
  src/cascadia/TerminalApp/AppCommandlineArgs.cpp
  src/cascadia/TerminalApp/AppLogic.cpp
Labels: Issue-Bug, Product-Terminal, Severity-Blocking, Area-Remoting

#17761 Set the default for `autoMarkPrompts` to `true`
  doc/cascadia/profiles.schema.json
  src/cascadia/TerminalSettingsModel/MTSMSettings.h
Labels: Product-Terminal, Issue-Task, Area-Suggestions

#17763 Fix overwrite key binding warning in the SUI
  src/cascadia/TerminalSettingsEditor/ActionsViewModel.cpp
Labels: Issue-Bug, Product-Terminal, Area-Settings UI

#17729 Add support for querying Xterm dynamic colors and palette
  .github/actions/spelling/patterns/patterns.txt
  src/terminal/adapter/ITermDispatch.hpp
  src/terminal/adapter/adaptDispatch.cpp
  src/terminal/adapter/adaptDispatch.hpp
  src/terminal/adapter/termDispatch.hpp
  src/terminal/adapter/ut_adapter/adapterTest.cpp
  src/terminal/parser/InputStateMachineEngine.cpp
  src/terminal/parser/InputStateMachineEngine.hpp
  src/terminal/parser/OutputStateMachineEngine.cpp
  src/terminal/parser/ut_parser/OutputEngineTest.cpp
Labels: Product-Conhost, Area-VT, Issue-Task

#17768 ConPTY: Raise the MAX_PATH limit
  src/winconpty/winconpty.cpp
Labels: Product-Conpty, Area-Server, Issue-Bug

#17770 Guard Control UpdateAppearance/Settings against UAF
  src/cascadia/TerminalControl/TermControl.cpp
Labels: Issue-Bug, Area-Settings, Severity-Crash, Product-Terminal, Severity-Blocking, Priority-1

#17742 Allow OSC 17 to set the selection background color
  src/buffer/out/TextColor.h
  src/cascadia/TerminalControl/ControlCore.cpp
  src/cascadia/TerminalControl/HwndTerminal.cpp
  src/cascadia/TerminalControl/IControlAppearance.idl
  src/cascadia/TerminalCore/ICoreAppearance.idl
  src/cascadia/TerminalCore/Terminal.cpp
  src/cascadia/inc/ControlProperties.h
  src/renderer/atlas/AtlasEngine.api.cpp
  src/renderer/atlas/AtlasEngine.cpp
  src/renderer/atlas/AtlasEngine.h
  src/renderer/base/RenderSettings.cpp
  src/renderer/base/renderer.cpp
  src/renderer/inc/IRenderEngine.hpp
  src/terminal/adapter/adaptDispatch.cpp
  src/terminal/parser/OutputStateMachineEngine.cpp
  src/terminal/parser/OutputStateMachineEngine.hpp
Labels: Needs-Second

#17741 ConPTY: Flush unhandled sequences to the buffer
  src/host/VtInputThread.cpp
  src/inc/til.h
  src/terminal/adapter/DispatchTypes.hpp
  src/terminal/adapter/FontBuffer.cpp
  src/terminal/adapter/IInteractDispatch.hpp
  src/terminal/adapter/ITermDispatch.hpp
  src/terminal/adapter/InteractDispatch.cpp
  src/terminal/adapter/InteractDispatch.hpp
  src/terminal/adapter/adaptDispatch.cpp
  src/terminal/adapter/adaptDispatch.hpp
  src/terminal/adapter/adaptDispatchGraphics.cpp
  src/terminal/adapter/termDispatch.hpp
  src/terminal/adapter/terminalOutput.cpp
  src/terminal/adapter/terminalOutput.hpp
  src/terminal/adapter/ut_adapter/adapterTest.cpp
  src/terminal/parser/IStateMachineEngine.hpp
  src/terminal/parser/InputStateMachineEngine.cpp
  src/terminal/parser/InputStateMachineEngine.hpp
  src/terminal/parser/OutputStateMachineEngine.cpp
  src/terminal/parser/OutputStateMachineEngine.hpp
  src/terminal/parser/stateMachine.cpp
  src/terminal/parser/stateMachine.hpp
  src/terminal/parser/ut_parser/InputEngineTest.cpp
  src/terminal/parser/ut_parser/OutputEngineTest.cpp
  src/terminal/parser/ut_parser/StateMachineTest.cpp
Labels: Product-Conpty, Issue-Bug, Priority-1

#17774 During Alt+Numpad composition, stash keys in case we bail out
  src/cascadia/TerminalControl/TermControl.cpp
  src/cascadia/TerminalControl/TermControl.h
Labels: Area-Input, Issue-Bug, Product-Terminal

#17779 Restore off-the-top behavior for VT mouse mode
  src/cascadia/TerminalControl/ControlInteractivity.cpp
  src/cascadia/TerminalControl/ControlInteractivity.h
  src/cascadia/TerminalControl/ControlInteractivity.idl
  src/cascadia/TerminalControl/TermControl.cpp
  src/cascadia/UnitTests_Control/ControlInteractivityTests.cpp
Labels: Area-Input, Issue-Bug, Product-Terminal

#17614 Use WinGet API to improve Quick Fix results
  build/rules/Microsoft.WindowsPackageManager.ComInterop.Additional.targets
  dep/nuget/packages.config
  src/cascadia/TerminalApp/SuggestionsControl.cpp
  src/cascadia/TerminalApp/TerminalAppLib.vcxproj
  src/cascadia/TerminalApp/TerminalPage.cpp
  src/cascadia/TerminalApp/TerminalPage.h
  src/cascadia/TerminalApp/WindowsPackageManagerFactory.h
  src/cascadia/TerminalControl/ControlCore.cpp
  src/cascadia/TerminalControl/ControlCore.h
  src/cascadia/TerminalControl/EventArgs.h
  src/cascadia/TerminalControl/EventArgs.idl
  src/cascadia/TerminalControl/TermControl.cpp
  src/cascadia/TerminalControl/TermControl.h
  src/cascadia/TerminalCore/Terminal.cpp
  src/cascadia/TerminalCore/Terminal.hpp
  src/cascadia/TerminalCore/TerminalApi.cpp
  src/cascadia/WindowsTerminal/WindowsTerminal.vcxproj
  src/common.nugetversions.props
  src/common.nugetversions.targets
Labels: Area-VT, Issue-Bug, Area-TerminalControl, Product-Terminal, Issue-Task

#17790 Don't emit raw escape sequences in the test log output
  src/host/ut_host/ScreenBufferTests.cpp
Labels: Issue-Bug, Product-Terminal, Area-Quality

#17788 Prevent a crash when holding enter when creating a tab
  src/cascadia/TerminalCore/Terminal.cpp
Labels: Area-TerminalControl, Severity-Crash, Product-Terminal, Priority-2

#17786 Improve reliability of VT responses
  src/cascadia/TerminalControl/ControlCore.cpp
  src/cascadia/TerminalControl/ControlCore.h
  src/cascadia/TerminalCore/TerminalApi.cpp
Labels: Product-Conpty, Area-Input, Issue-Bug, Priority-1

#17783 Make fire_and_forget exception safe
  src/cascadia/Remoting/WindowManager.cpp
  src/cascadia/Remoting/WindowManager.h
  src/cascadia/TerminalApp/AboutDialog.cpp
  src/cascadia/TerminalApp/AboutDialog.h
  src/cascadia/TerminalApp/AppActionHandlers.cpp
  src/cascadia/TerminalApp/AppLogic.cpp
  src/cascadia/TerminalApp/AppLogic.h
  src/cascadia/TerminalApp/DebugTapConnection.cpp
  src/cascadia/TerminalApp/Jumplist.cpp
  src/cascadia/TerminalApp/Jumplist.h
  src/cascadia/TerminalApp/SnippetsPaneContent.cpp
  src/cascadia/TerminalApp/SnippetsPaneContent.h
  src/cascadia/TerminalApp/TabManagement.cpp
  src/cascadia/TerminalApp/TerminalPage.cpp
  src/cascadia/TerminalApp/TerminalPage.h
  src/cascadia/TerminalApp/TerminalPaneContent.cpp
  src/cascadia/TerminalApp/TerminalPaneContent.h
  src/cascadia/TerminalApp/TerminalTab.cpp
  src/cascadia/TerminalApp/TerminalWindow.cpp
  src/cascadia/TerminalApp/TerminalWindow.h
  src/cascadia/TerminalApp/TitlebarControl.cpp
  src/cascadia/TerminalApp/TitlebarControl.h
  src/cascadia/TerminalConnection/ConptyConnection.cpp
  src/cascadia/TerminalConnection/ConptyConnection.h
  src/cascadia/TerminalControl/ControlCore.cpp
  src/cascadia/TerminalControl/ControlCore.h
  src/cascadia/TerminalControl/TermControl.cpp
  src/cascadia/TerminalControl/TermControl.h
  src/cascadia/TerminalSettingsEditor/Appearances.cpp
  src/cascadia/TerminalSettingsEditor/Appearances.h
  src/cascadia/TerminalSettingsEditor/Profiles_Base.cpp
  src/cascadia/TerminalSettingsEditor/Profiles_Base.h
  src/cascadia/TerminalSettingsModel/CascadiaSettings.cpp
  src/cascadia/TerminalSettingsModel/CascadiaSettingsSerialization.cpp
  src/cascadia/WindowsTerminal/AppHost.cpp
  src/cascadia/WindowsTerminal/AppHost.h
  src/cascadia/WindowsTerminal/IslandWindow.cpp
  src/cascadia/WindowsTerminal/IslandWindow.h
  src/cascadia/WindowsTerminal/WindowEmperor.cpp
  src/cascadia/WindowsTerminal/WindowEmperor.h
  src/cascadia/inc/cppwinrt_utils.h
Labels: Area-CodeHealth

#17747 Use DECCRA/DECFRA for ScrollConsoleScreenBuffer
  .github/actions/spelling/expect/expect.txt
  src/host/VtInputThread.cpp
  src/host/VtInputThread.hpp
  src/host/VtIo.cpp
  src/host/VtIo.hpp
  src/host/getset.cpp
  src/host/ut_host/VtIoTests.cpp
  src/inc/til/enumset.h
  src/terminal/parser/InputStateMachineEngine.cpp
  src/terminal/parser/InputStateMachineEngine.hpp
  src/types/viewport.cpp
  src/winconpty/ft_pty/ConPtyTests.cpp
  tools/OpenConsole.psm1
  tools/tests.xml
Labels: Product-Conpty

#17802 Make sure a blank title string resets the title
  src/cascadia/TerminalCore/TerminalApi.cpp
Labels: Issue-Bug

#17795 Remove unnecessary FMT
  src/cascadia/TerminalSettingsModel/Command.cpp
Labels: Area-CodeHealth

#17821 Add action IDs to the color selection commands
  src/cascadia/TerminalSettingsModel/enableColorSelection.json
Labels: Issue-Bug, Area-Settings, Product-Terminal

#17826 Give spacing marks space
  src/tools/GraphemeTableGen/Program.cs
  src/types/CodepointWidthDetector.cpp
Labels: Area-Rendering, Issue-Bug, Product-Terminal

#17828 Fix two ConPTY HWND focus issues
  src/cascadia/WindowsTerminal/IslandWindow.cpp
  src/interactivity/base/InteractivityFactory.cpp
Labels: Product-Conpty, Issue-Bug, Area-Windowing
