Repository microsoft/terminal, pull requests merged in 2024-01, with the labels that each got.

#16535 Enable alternate scroll mode by default
  src/terminal/input/mouseInput.cpp
  src/terminal/input/terminalInput.cpp
  src/terminal/input/terminalInput.hpp
Labels: Issue-Feature, Area-VT, Area-TerminalControl, Product-Terminal, Issue-Task

#16544 Update SUI Color Scheme colors' AutoProp.Name and ToolTip
  src/cascadia/TerminalSettingsEditor/ColorSchemeViewModel.cpp
  src/cascadia/TerminalSettingsEditor/ColorSchemeViewModel.h
  src/cascadia/TerminalSettingsEditor/ColorSchemeViewModel.idl
  src/cascadia/TerminalSettingsEditor/EditColorScheme.xaml
Labels: Issue-Bug, Area-Accessibility, Product-Terminal

#16559 Change the SUB control glyph to U+2426
  src/terminal/parser/OutputStateMachineEngine.cpp
Labels: Issue-Feature

#16587 Avoid timer ticks on frozen windows
  src/cascadia/LocalTests_TerminalApp/pch.h
  src/cascadia/TerminalApp/ColorHelper.cpp
  src/cascadia/TerminalApp/ColorHelper.h
  src/cascadia/TerminalApp/TerminalAppLib.vcxproj
  src/cascadia/TerminalApp/TerminalTab.cpp
  src/cascadia/TerminalApp/TerminalTab.h
  src/cascadia/TerminalApp/Toast.h
  src/cascadia/TerminalApp/pch.h
  src/cascadia/TerminalControl/TermControl.cpp
  src/cascadia/TerminalControl/TermControl.h
  src/cascadia/TerminalControl/pch.h
  src/cascadia/WinRTUtils/WinRTUtils.vcxproj
  src/cascadia/WinRTUtils/WinRTUtils.vcxproj.filters
  src/cascadia/WinRTUtils/inc/SafeDispatcherTimer.h
  src/cascadia/WindowsTerminal/AppHost.cpp
  src/cascadia/WindowsTerminal/AppHost.h
  src/cascadia/WindowsTerminal/pch.h
Labels: Issue-Bug, Product-Terminal, Area-Windowing

#16480 Avoid generating extra formatted copies when no action specific `copyFormatting` is set
  src/cascadia/TerminalApp/TerminalPage.cpp
  src/cascadia/TerminalControl/ControlCore.cpp
  src/cascadia/TerminalControl/IControlSettings.idl
  src/cascadia/TerminalSettingsModel/TerminalSettings.cpp
  src/cascadia/TerminalSettingsModel/TerminalSettings.h
  src/cascadia/inc/ControlProperties.h
Labels: AutoMerge

#16525 Add support for more DSR queries.
  src/terminal/adapter/DispatchTypes.hpp
  src/terminal/adapter/adaptDispatch.cpp
  src/terminal/adapter/adaptDispatch.hpp
  src/terminal/adapter/ut_adapter/adapterTest.cpp
  src/terminal/parser/ut_parser/OutputEngineTest.cpp
Labels: Product-Conhost, Area-VT, AutoMerge, Issue-Task

#16594 Revert "Add magic incantation to tell Store we support Server"
  src/cascadia/CascadiaPackage/Package-Dev.appxmanifest
  src/cascadia/CascadiaPackage/Package-Pre.appxmanifest
  src/cascadia/CascadiaPackage/Package.appxmanifest
Labels: Needs-Attention

#16534 Add support for the DECST8C escape sequence
  .github/actions/spelling/expect/expect.txt
  src/host/ut_host/ScreenBufferTests.cpp
  src/terminal/adapter/DispatchTypes.hpp
  src/terminal/adapter/ITermDispatch.hpp
  src/terminal/adapter/adaptDispatch.cpp
  src/terminal/adapter/adaptDispatch.hpp
  src/terminal/adapter/termDispatch.hpp
  src/terminal/parser/OutputStateMachineEngine.cpp
  src/terminal/parser/OutputStateMachineEngine.hpp
Labels: Issue-Feature, Product-Conhost, Area-VT, AutoMerge

#16592 Simplify WindowEmperor::HandleCommandlineArgs
  src/cascadia/WindowsTerminal/WindowEmperor.cpp
  src/cascadia/WindowsTerminal/WindowEmperor.h
  src/cascadia/WindowsTerminal/main.cpp
Labels: Area-CodeHealth

#16377 Refactor `TextBuffer::GenHTML/RTF` to read the buffer directly
  .github/actions/spelling/expect/expect.txt
  src/buffer/out/Row.cpp
  src/buffer/out/Row.hpp
  src/buffer/out/textBuffer.cpp
  src/buffer/out/textBuffer.hpp
  src/cascadia/TerminalApp/AppActionHandlers.cpp
  src/cascadia/TerminalControl/ControlCore.cpp
  src/cascadia/TerminalControl/ControlCore.h
  src/cascadia/TerminalControl/HwndTerminal.cpp
  src/cascadia/TerminalControl/HwndTerminal.hpp
  src/cascadia/TerminalControl/ICoreState.idl
  src/cascadia/TerminalControl/TermControl.cpp
  src/cascadia/TerminalControl/TermControl.h
  src/cascadia/TerminalCore/Terminal.hpp
  src/cascadia/TerminalCore/TerminalSelection.cpp
  src/host/selection.hpp
  src/host/selectionState.cpp
  src/host/ut_host/ClipboardTests.cpp
  src/host/ut_host/TextBufferTests.cpp
  src/inc/test/CommonState.hpp
  src/interactivity/win32/Clipboard.cpp
  src/interactivity/win32/clipboard.hpp
  src/types/UiaTextRangeBase.cpp
Labels: Issue-Bug, Area-TerminalControl, Product-Terminal

#16610 Reset _wrapForced when erasing scrollback
  src/buffer/out/textBuffer.cpp
  src/buffer/out/textBuffer.hpp
  src/host/ut_host/ScreenBufferTests.cpp
  src/terminal/adapter/adaptDispatch.cpp
Labels: Product-Conhost, Area-VT, Issue-Bug

#16457 Fix conhost clipboard handling bugs
  src/interactivity/win32/Clipboard.cpp
  src/interactivity/win32/clipboard.hpp
Labels: Product-Conhost, Area-Interaction, Issue-Bug, Priority-3

#16511 Refactor VT terminal input
  .github/actions/spelling/expect/expect.txt
  src/cascadia/TerminalControl/TermControl.cpp
  src/terminal/adapter/ut_adapter/inputTest.cpp
  src/terminal/input/mouseInput.cpp
  src/terminal/input/terminalInput.cpp
  src/terminal/input/terminalInput.hpp
Labels: Issue-Feature, Product-Conhost, Product-Conpty, Area-Input, Area-VT, Issue-Bug, Product-Terminal, Priority-2

#16617 Upgrade Microsoft.Windows.ImplementationLibrary to 1.0.240122.1
  dep/nuget/packages.config
  src/common.nugetversions.targets
  src/renderer/atlas/BackendD3D.cpp
Labels: Issue-Bug, Product-Terminal, Area-Remoting, Area-Windowing

#16624 Fix a bug caused by #16592
  src/cascadia/WindowsTerminal/WindowEmperor.cpp
Labels: Issue-Bug, Product-Terminal, Severity-Blocking, Priority-0
