Repository microsoft/terminal, pull requests merged in 2024-02, with the labels that each got.

#16634 Restore support for pasting files
  src/cascadia/TerminalApp/TerminalPage.cpp
  src/interactivity/win32/Clipboard.cpp
  src/interactivity/win32/clipboard.hpp
  src/interactivity/win32/windowproc.cpp
Labels: Issue-Bug, Area-TerminalControl, Product-Terminal, Priority-2

#16670 Port clipboard improvements from inbox to oss
  src/interactivity/win32/Clipboard.cpp
Labels: Area-CodeHealth

#16601 General improvements in preparation for #16598
  .github/actions/spelling/expect/expect.txt
  src/cascadia/TerminalApp/AppLogic.cpp
  src/cascadia/TerminalApp/AppLogic.h
  src/cascadia/TerminalApp/DebugTapConnection.cpp
  src/cascadia/TerminalApp/DebugTapConnection.h
  src/cascadia/TerminalApp/TerminalPage.cpp
  src/cascadia/TerminalConnection/AzureConnection.cpp
  src/cascadia/TerminalConnection/AzureConnection.h
  src/cascadia/TerminalConnection/BaseTerminalConnection.h
  src/cascadia/TerminalConnection/ConptyConnection.cpp
  src/cascadia/TerminalConnection/ConptyConnection.h
  src/cascadia/TerminalConnection/ConptyConnection.idl
  src/cascadia/TerminalConnection/EchoConnection.h
  src/cascadia/TerminalConnection/ITerminalConnection.idl
  src/cascadia/TerminalConnection/TerminalConnection.vcxproj
  src/cascadia/TerminalConnection/TerminalConnection.vcxproj.filters
  src/cascadia/TerminalSettingsEditor/PreviewConnection.h
  src/cascadia/TerminalSettingsEditor/ProfileViewModel.h
  src/cascadia/TerminalSettingsModel/ApplicationState.cpp
  src/cascadia/TerminalSettingsModel/ApplicationState.h
  src/cascadia/TerminalSettingsModel/ApplicationState.idl
  src/cascadia/TerminalSettingsModel/CascadiaSettingsSerialization.cpp
  src/cascadia/TerminalSettingsModel/GlobalAppSettings.h
  src/cascadia/UnitTests_Control/MockConnection.h
  src/cascadia/WindowsTerminal/WindowEmperor.cpp
  src/cascadia/WindowsTerminal/WindowEmperor.h
  src/types/inc/utils.hpp
  src/types/ut_types/UtilsTests.cpp
  src/types/utils.cpp
Labels: Product-Terminal

#16645 Improve handling of Space key combinations
  src/terminal/input/terminalInput.cpp
Labels: Area-Input, Area-VT, Issue-Bug, Product-Terminal

#16675 Disable DECKPAM mode behind velocity
  src/features.xml
  src/terminal/input/terminalInput.cpp
Labels: Product-Conhost, Area-Input, Area-VT, Issue-Bug, Product-Terminal

#7337 Add a spec for #7335, "console allocation policy"
  .github/actions/spelling/allow/allow.txt
  .github/actions/spelling/allow/apis.txt
  .github/actions/spelling/allow/microsoft.txt
  doc/specs/#7335 - Console Allocation Policy.md
Labels: Product-Conhost, Issue-Docs, Area-Server, Needs-Attention, Product-Meta, Issue-Scenario

#14292 Implement MVVM for the Actions page
  src/cascadia/TerminalSettingsEditor/Actions.cpp
  src/cascadia/TerminalSettingsEditor/Actions.h
  src/cascadia/TerminalSettingsEditor/Actions.idl
  src/cascadia/TerminalSettingsEditor/Actions.xaml
  src/cascadia/TerminalSettingsEditor/ActionsViewModel.cpp
  src/cascadia/TerminalSettingsEditor/ActionsViewModel.h
  src/cascadia/TerminalSettingsEditor/ActionsViewModel.idl
  src/cascadia/TerminalSettingsEditor/MainPage.cpp
  src/cascadia/TerminalSettingsEditor/Microsoft.Terminal.Settings.Editor.vcxproj
  src/cascadia/TerminalSettingsEditor/Microsoft.Terminal.Settings.Editor.vcxproj.filters
Labels: AutoMerge

#16718 COOKED_READ: Fix tab not erasing the prompt
  src/host/readDataCooked.cpp
Labels: Product-Conhost, Issue-Bug, Needs-Second, Priority-3, Area-CookedRead

#16742 Fix an apparent x86 miscompilation on MSVC 19.38
  src/inc/til/bitmap.h
Labels: Issue-Bug, Area-Build

#16547 Complete the 8-bit interface architecture
  .github/actions/spelling/expect/expect.txt
  src/terminal/adapter/DispatchTypes.hpp
  src/terminal/adapter/FontBuffer.cpp
  src/terminal/adapter/FontBuffer.hpp
  src/terminal/adapter/ITermDispatch.hpp
  src/terminal/adapter/adaptDispatch.cpp
  src/terminal/adapter/adaptDispatch.hpp
  src/terminal/adapter/termDispatch.hpp
  src/terminal/adapter/terminalOutput.cpp
  src/terminal/adapter/terminalOutput.hpp
  src/terminal/adapter/ut_adapter/adapterTest.cpp
  src/terminal/parser/OutputStateMachineEngine.cpp
  src/terminal/parser/OutputStateMachineEngine.hpp
Labels: Issue-Feature, Product-Conhost, Area-VT, AutoMerge

#16719 AtlasEngine: Improve dotted, dashed and curly underlines
  src/renderer/atlas/BackendD3D.cpp
  src/renderer/atlas/BackendD3D.h
  src/renderer/atlas/shader_ps.hlsl
Labels: Area-Rendering, Issue-Bug, Product-Terminal

#16729 Add support for custom box drawing and powerline glyphs
  src/cascadia/TerminalControl/ControlCore.cpp
  src/cascadia/TerminalControl/ControlCore.h
  src/cascadia/TerminalControl/IControlSettings.idl
  src/cascadia/TerminalSettingsEditor/Appearances.h
  src/cascadia/TerminalSettingsEditor/Appearances.idl
  src/cascadia/TerminalSettingsEditor/Appearances.xaml
  src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw
  src/cascadia/TerminalSettingsModel/FontConfig.idl
  src/cascadia/TerminalSettingsModel/MTSMSettings.h
  src/cascadia/TerminalSettingsModel/TerminalSettings.cpp
  src/cascadia/TerminalSettingsModel/TerminalSettings.h
  src/cascadia/inc/ControlProperties.h
  src/host/screenInfo.cpp
  src/host/settings.cpp
  src/host/settings.hpp
  src/inc/til/flat_set.h
  src/inc/til/unicode.h
  src/propslib/RegistrySerialization.cpp
  src/renderer/atlas/AtlasEngine.api.cpp
  src/renderer/atlas/AtlasEngine.cpp
  src/renderer/atlas/AtlasEngine.h
  src/renderer/atlas/AtlasEngine.r.cpp
  src/renderer/atlas/Backend.h
  src/renderer/atlas/BackendD3D.cpp
  src/renderer/atlas/BackendD3D.h
  src/renderer/atlas/BuiltinGlyphs.cpp
  src/renderer/atlas/BuiltinGlyphs.h
  src/renderer/atlas/atlas.vcxproj
  src/renderer/atlas/common.h
  src/renderer/base/FontInfoDesired.cpp
  src/renderer/inc/FontInfoDesired.hpp
  src/til/ut_til/FlatSetTests.cpp
Labels: Issue-Feature, Area-Rendering, Product-Terminal, Priority-1

#16185 Add support for actions in fragments
  src/cascadia/LocalTests_SettingsModel/DeserializationTests.cpp
  src/cascadia/LocalTests_SettingsModel/SerializationTests.cpp
  src/cascadia/TerminalSettingsModel/ActionMap.h
  src/cascadia/TerminalSettingsModel/ActionMapSerialization.cpp
  src/cascadia/TerminalSettingsModel/CascadiaSettingsSerialization.cpp
  src/cascadia/TerminalSettingsModel/Command.cpp
  src/cascadia/TerminalSettingsModel/Command.h
  src/cascadia/TerminalSettingsModel/GlobalAppSettings.cpp
  src/cascadia/TerminalSettingsModel/GlobalAppSettings.h
Labels: Issue-Feature, Area-Settings, Product-Terminal

#15843 When the profile icon is set to null, fall back to the icon of the commandline
  src/cascadia/LocalTests_SettingsModel/TerminalSettingsTests.cpp
  src/cascadia/TerminalApp/TabManagement.cpp
  src/cascadia/TerminalApp/TerminalPage.cpp
  src/cascadia/TerminalSettingsEditor/MainPage.cpp
  src/cascadia/TerminalSettingsEditor/ProfileViewModel.cpp
  src/cascadia/TerminalSettingsEditor/ProfileViewModel.h
  src/cascadia/TerminalSettingsEditor/ProfileViewModel.idl
  src/cascadia/TerminalSettingsEditor/Profiles_Base.xaml
  src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw
  src/cascadia/TerminalSettingsModel/CascadiaSettings.cpp
  src/cascadia/TerminalSettingsModel/CascadiaSettings.h
  src/cascadia/TerminalSettingsModel/Command.cpp
  src/cascadia/TerminalSettingsModel/MTSMSettings.h
  src/cascadia/TerminalSettingsModel/Profile.cpp
  src/cascadia/TerminalSettingsModel/Profile.h
  src/cascadia/TerminalSettingsModel/Profile.idl
Labels: Issue-Feature, Area-User Interface, Product-Terminal, zBugBash-Consider

#16775 Fix the hyperlink detection when there are leading wide glyph in the row
  src/buffer/out/Row.cpp
Labels: Area-Output, Issue-Bug, Product-Terminal, AutoMerge, Priority-2

#16772 Add new and extend existing til::string helpers
  src/cascadia/TerminalConnection/ConptyConnection.cpp
  src/cascadia/TerminalSettingsEditor/Appearances.h
  src/cascadia/TerminalSettingsEditor/ProfileViewModel.cpp
  src/cascadia/TerminalSettingsEditor/ProfileViewModel.h
  src/cascadia/TerminalSettingsModel/CascadiaSettings.cpp
  src/cascadia/TerminalSettingsModel/KeyChordSerialization.cpp
  src/inc/til/env.h
  src/inc/til/string.h
  src/til/ut_til/string.cpp
Labels: Area-CodeHealth

#16104 Allow editing font axes in the Settings UI
  .github/actions/spelling/allow/allow.txt
  src/cascadia/TerminalSettingsEditor/Appearances.cpp
  src/cascadia/TerminalSettingsEditor/Appearances.h
  src/cascadia/TerminalSettingsEditor/Appearances.idl
  src/cascadia/TerminalSettingsEditor/Appearances.xaml
  src/cascadia/TerminalSettingsEditor/ProfileViewModel.cpp
  src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw
  src/cascadia/TerminalSettingsEditor/SettingContainer.cpp
  src/cascadia/TerminalSettingsEditor/SettingContainer.h
  src/cascadia/TerminalSettingsEditor/SettingContainer.idl
  src/cascadia/TerminalSettingsModel/FontConfig.cpp
Labels: AutoMerge

#16678 Allow editing font features in the Settings UI
  .github/actions/spelling/allow/apis.txt
  src/cascadia/TerminalSettingsEditor/Appearances.cpp
  src/cascadia/TerminalSettingsEditor/Appearances.h
  src/cascadia/TerminalSettingsEditor/Appearances.idl
  src/cascadia/TerminalSettingsEditor/Appearances.xaml
  src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw
  src/cascadia/TerminalSettingsModel/FontConfig.cpp
Labels: AutoMerge

#16788 A minor cleanup of ProfileViewModel
  src/cascadia/TerminalSettingsEditor/Appearances.h
  src/cascadia/TerminalSettingsEditor/ProfileViewModel.cpp
Labels: Area-CodeHealth

#16787 Fix bugs in CharToColumnMapper
  src/buffer/out/Row.cpp
  src/buffer/out/Row.hpp
  src/buffer/out/ut_textbuffer/TextBuffer.Unit.Tests.vcxproj
  src/buffer/out/ut_textbuffer/UTextAdapterTests.cpp
  src/buffer/out/ut_textbuffer/sources
  src/inc/til/point.h
Labels: Product-Conhost, Area-Output, Issue-Bug, Priority-1
