Repository microsoft/terminal, pull requests merged in 2024-09, with the labels that each got.

#17845 Pass through DCS responses when VT input mode is disabled
  src/terminal/parser/InputStateMachineEngine.cpp
  src/terminal/parser/InputStateMachineEngine.hpp
Labels: Product-Conpty, Issue-Bug, AutoMerge

#17833 Avoid dropping Esc characters from VT responses
  src/terminal/adapter/IInteractDispatch.hpp
  src/terminal/adapter/InteractDispatch.cpp
  src/terminal/adapter/InteractDispatch.hpp
  src/terminal/parser/InputStateMachineEngine.cpp
  src/terminal/parser/ut_parser/InputEngineTest.cpp
  src/tools/vtpipeterm/main.cpp
Labels: Product-Conpty, Area-Input, Issue-Bug, Product-Terminal, Priority-2

#17849 Fix ScrollRect to DECCRA translation
  src/host/getset.cpp
Labels: Product-Conpty, Area-VT, Issue-Bug

#17853 Restore contents when a screen info is closed
  src/host/VtIo.cpp
  src/host/VtIo.hpp
  src/host/getset.cpp
  src/server/ObjectHandle.cpp
Labels: Product-Conpty, Area-VT, Issue-Bug

#17848 Fix crash in AppHost::_QuitRequested
  src/cascadia/WindowsTerminal/AppHost.cpp
Labels: Issue-Bug, Severity-Crash, Product-Terminal, Area-Windowing

#17886 Fix a crash on pane close
  src/cascadia/TerminalApp/Pane.cpp
Labels: Issue-Bug, Area-TerminalControl, Product-Terminal, Priority-1

#17910 Fix text scaling issues in settings UI
  src/cascadia/TerminalSettingsEditor/Actions.xaml
  src/cascadia/TerminalSettingsEditor/ActionsViewModel.cpp
  src/cascadia/TerminalSettingsEditor/CommonResources.xaml
  src/cascadia/TerminalSettingsEditor/EditColorScheme.xaml
Labels: Issue-Bug, Area-Accessibility, Product-Terminal, Priority-3

#17954 Check EnableHexNumpad before enabling it
  src/cascadia/TerminalControl/TermControl.cpp
Labels: Area-Input, Issue-Bug, Product-Terminal

#17951 Fix a sixel crash when the buffer is reflowed
  src/terminal/adapter/SixelParser.cpp
Labels: Issue-Bug

#17905 Fix a cooked read deadlock
  src/buffer/out/textBuffer.cpp
  src/host/readDataCooked.cpp
Labels: Product-Conhost, Issue-Bug, Product-Terminal, Priority-2, Area-CookedRead

#17885 Stop scrolling on output when search is open
  src/buffer/out/search.cpp
  src/buffer/out/search.h
  src/cascadia/TerminalControl/ControlCore.cpp
  src/cascadia/TerminalControl/ControlCore.h
  src/cascadia/TerminalControl/ControlCore.idl
  src/cascadia/TerminalControl/TermControl.cpp
  src/cascadia/TerminalCore/Terminal.cpp
  src/cascadia/TerminalCore/Terminal.hpp
  src/interactivity/win32/find.cpp
Labels: Issue-Bug, Area-User Interface, Product-Terminal, Priority-1

#17884 Fix clear buffer command
  src/cascadia/TerminalControl/ControlCore.cpp
  src/cascadia/TerminalCore/Terminal.cpp
  src/cascadia/TerminalCore/Terminal.hpp
  src/cascadia/UnitTests_Control/ControlCoreTests.cpp
  src/host/PtySignalInputThread.cpp
  src/host/screenInfo.cpp
  src/host/screenInfo.hpp
Labels: Issue-Bug, Area-Accessibility

#17953 Add input scope startup setting
  .github/actions/spelling/expect/expect.txt
  src/cascadia/TerminalControl/EventArgs.idl
  src/cascadia/TerminalControl/IControlSettings.idl
  src/cascadia/TerminalControl/TermControl.cpp
  src/cascadia/TerminalSettingsEditor/GlobalAppearance.xaml
  src/cascadia/TerminalSettingsEditor/GlobalAppearanceViewModel.cpp
  src/cascadia/TerminalSettingsEditor/GlobalAppearanceViewModel.h
  src/cascadia/TerminalSettingsEditor/GlobalAppearanceViewModel.idl
  src/cascadia/TerminalSettingsEditor/Launch.xaml
  src/cascadia/TerminalSettingsEditor/LaunchViewModel.cpp
  src/cascadia/TerminalSettingsEditor/LaunchViewModel.h
  src/cascadia/TerminalSettingsEditor/LaunchViewModel.idl
  src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw
  src/cascadia/TerminalSettingsModel/EnumMappings.cpp
  src/cascadia/TerminalSettingsModel/EnumMappings.h
  src/cascadia/TerminalSettingsModel/EnumMappings.idl
  src/cascadia/TerminalSettingsModel/GlobalAppSettings.cpp
  src/cascadia/TerminalSettingsModel/GlobalAppSettings.idl
  src/cascadia/TerminalSettingsModel/MTSMSettings.h
  src/cascadia/TerminalSettingsModel/TerminalSettings.cpp
  src/cascadia/TerminalSettingsModel/TerminalSettings.h
  src/cascadia/TerminalSettingsModel/TerminalSettingsSerializationHelpers.h
  src/cascadia/inc/ControlProperties.h
  src/tsf/Handle.cpp
  src/tsf/Handle.h
  src/tsf/Implementation.cpp
  src/tsf/Implementation.h
  src/tsf/precomp.h
Labels: Area-TerminalControl, Product-Terminal, Issue-Task

#17912 Improve color contrast of reset button in SUI
  src/cascadia/TerminalSettingsEditor/SettingContainerStyle.xaml
Labels: Issue-Bug, Area-Accessibility, Product-Terminal

#17960 Fix an exception on startup
  src/cascadia/WinRTUtils/inc/WtExeUtils.h
Labels: Area-CodeHealth

#17961 Stop updating AutoSuggestBox on selection
  src/cascadia/TerminalSettingsEditor/Appearances.cpp
  src/cascadia/TerminalSettingsEditor/Appearances.h
  src/cascadia/TerminalSettingsEditor/Appearances.xaml
Labels: AutoMerge

#17958 Localization Updates - main - 09/26/2024 19:14:21
  src/cascadia/CascadiaPackage/Resources/cs-CZ/Resources.resw
  src/cascadia/TerminalApp/Resources/cs-CZ/ContextMenu.resw
  src/cascadia/TerminalApp/Resources/ko-KR/Resources.resw
  src/cascadia/TerminalSettingsEditor/Resources/de-DE/Resources.resw
  src/cascadia/TerminalSettingsEditor/Resources/es-ES/Resources.resw
  src/cascadia/TerminalSettingsEditor/Resources/fr-FR/Resources.resw
  src/cascadia/TerminalSettingsEditor/Resources/it-IT/Resources.resw
  src/cascadia/TerminalSettingsEditor/Resources/ja-JP/Resources.resw
  src/cascadia/TerminalSettingsEditor/Resources/ko-KR/Resources.resw
  src/cascadia/TerminalSettingsEditor/Resources/pt-BR/Resources.resw
  src/cascadia/TerminalSettingsEditor/Resources/qps-ploc/Resources.resw
  src/cascadia/TerminalSettingsEditor/Resources/qps-ploca/Resources.resw
  src/cascadia/TerminalSettingsEditor/Resources/qps-plocm/Resources.resw
  src/cascadia/TerminalSettingsEditor/Resources/ru-RU/Resources.resw
  src/cascadia/TerminalSettingsEditor/Resources/zh-CN/Resources.resw
  src/cascadia/TerminalSettingsEditor/Resources/zh-TW/Resources.resw
Labels: Needs-Author-Feedback
