Repository microsoft/terminal, pull requests merged in 2025-01, with the labels that each got.

#18345 Fix multiple regressions since #18215
  src/cascadia/TerminalControl/TermControl.cpp
  src/cascadia/WindowsTerminal/AppHost.cpp
  src/cascadia/WindowsTerminal/WindowEmperor.cpp
  src/cascadia/WindowsTerminal/WindowEmperor.h
Labels: Issue-Bug, Area-TerminalControl, Product-Terminal, Priority-1, Priority-2, Area-Windowing

#18334 Remove dependencies on unstable MSVC/STL extensions,
  src/host/VtIo.cpp
  src/inc/LibraryIncludes.h
  src/renderer/atlas/pch.h
  src/renderer/gdi/gdirenderer.hpp
  src/renderer/gdi/paint.cpp
  src/server/WaitBlock.h
  src/terminal/adapter/SixelParser.hpp
  src/types/colorTable.cpp
  src/types/inc/colorTable.hpp
Labels: AutoMerge, Area-CodeHealth

#18268 [conhost] Fix WM_GETDPISCALEDSIZE handler, use provided size instead of current window size
  src/cascadia/ut_app/TerminalApp.Unit.Tests.manifest
  src/interactivity/win32/window.cpp
  src/interactivity/win32/window.hpp
  src/interactivity/win32/windowproc.cpp
Labels: Needs-Author-Feedback

#18445 Fix cursor hiding on input
  .github/actions/spelling/expect/expect.txt
  src/cascadia/TerminalControl/TermControl.cpp
  src/cascadia/WindowsTerminal/IslandWindow.cpp
  src/cascadia/WindowsTerminal/IslandWindow.h
  src/cascadia/WindowsTerminal/WindowEmperor.cpp
Labels: Issue-Bug

#18444 Fix dispatching of system keys
  src/cascadia/WindowsTerminal/WindowEmperor.cpp
  src/cascadia/WindowsTerminal/WindowEmperor.h
Labels: Issue-Bug, Product-Terminal, AutoMerge, Priority-2, Area-Windowing

#18418 Make SUI previews readable by screen readers
  src/cascadia/TerminalSettingsEditor/Appearances.cpp
  src/cascadia/TerminalSettingsEditor/Appearances.h
  src/cascadia/TerminalSettingsEditor/Appearances.idl
  src/cascadia/TerminalSettingsEditor/Appearances.xaml
  src/cascadia/TerminalSettingsEditor/Launch.xaml
  src/cascadia/TerminalSettingsEditor/LaunchViewModel.cpp
  src/cascadia/TerminalSettingsEditor/LaunchViewModel.h
  src/cascadia/TerminalSettingsEditor/LaunchViewModel.idl
  src/cascadia/TerminalSettingsEditor/ProfileViewModel.cpp
  src/cascadia/TerminalSettingsEditor/ProfileViewModel.h
  src/cascadia/TerminalSettingsEditor/ProfileViewModel.idl
  src/cascadia/TerminalSettingsEditor/Profiles_Base.xaml
  src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw
  src/cascadia/TerminalSettingsEditor/SettingContainer.cpp
  src/cascadia/TerminalSettingsEditor/SettingContainer.h
  src/cascadia/TerminalSettingsEditor/SettingContainer.idl
  src/cascadia/TerminalSettingsEditor/SettingContainerStyle.xaml
Labels: zBugBash-Consider

#18424 [Windows 10] Fix layout in New Tab Menu page
  src/cascadia/TerminalSettingsEditor/NewTabMenu.xaml
Labels: zBugBash-Consider

#18434 Fix 'closeWindow' ignoring confirmation
  src/cascadia/TerminalApp/AppActionHandlers.cpp
  src/cascadia/TerminalApp/TerminalPage.h
  src/cascadia/TerminalApp/TerminalPage.idl
  src/cascadia/TerminalApp/TerminalWindow.h
  src/cascadia/TerminalApp/TerminalWindow.idl
  src/cascadia/WindowsTerminal/AppHost.cpp
  src/cascadia/WindowsTerminal/AppHost.h
Labels: Issue-Bug, Area-UserInterface, Product-Terminal, zBugBash-Consider

#18326 Reduce likelihood of races between stdout and cooked stdin reads
  src/host/readDataCooked.cpp
  src/host/readDataCooked.hpp
  src/host/selectionInput.cpp
Labels: Area-CookedRead

#18106 Make selection an exclusive range
  .github/actions/spelling/expect/expect.txt
  src/buffer/out/Row.cpp
  src/buffer/out/Row.hpp
  src/buffer/out/UTextAdapter.cpp
  src/buffer/out/textBuffer.cpp
  src/buffer/out/textBuffer.hpp
  src/buffer/out/ut_textbuffer/UTextAdapterTests.cpp
  src/cascadia/TerminalControl/ControlCore.cpp
  src/cascadia/TerminalControl/ControlInteractivity.cpp
  src/cascadia/TerminalControl/ControlInteractivity.h
  src/cascadia/TerminalCore/Terminal.cpp
  src/cascadia/TerminalCore/Terminal.hpp
  src/cascadia/TerminalCore/TerminalSelection.cpp
  src/cascadia/TerminalCore/terminalrenderdata.cpp
  src/cascadia/UnitTests_Control/ControlCoreTests.cpp
  src/cascadia/UnitTests_Control/ControlInteractivityTests.cpp
  src/cascadia/UnitTests_TerminalCore/SelectionTest.cpp
  src/host/selection.cpp
  src/host/ut_host/ClipboardTests.cpp
  src/host/ut_host/SearchTests.cpp
  src/host/ut_host/SelectionTests.cpp
  src/host/ut_host/TextBufferTests.cpp
  src/inc/til/point.h
  src/renderer/atlas/AtlasEngine.api.cpp
  src/renderer/atlas/AtlasEngine.cpp
  src/renderer/base/renderer.cpp
  src/types/TermControlUiaProvider.cpp
  src/types/UiaTextRangeBase.cpp
  src/types/inc/viewport.hpp
  src/types/viewport.cpp
Labels: Issue-Feature, Issue-Bug, Area-TerminalControl, Area-Accessibility, Product-Terminal, Issue-Task, Priority-3, zBugBash-Consider

#18388 Fix schema description
  doc/cascadia/profiles.schema.json
Labels: Needs-Attention

#18481 Fix SUI crash when image alignment not centered
  src/cascadia/TerminalSettingsEditor/Appearances.cpp
Labels: Issue-Bug

#18171 Add the ability to show the tab bar in fullscreen
  doc/cascadia/profiles.schema.json
  src/cascadia/TerminalApp/TabManagement.cpp
  src/cascadia/TerminalApp/TerminalPage.cpp
  src/cascadia/TerminalApp/TerminalPage.h
  src/cascadia/TerminalApp/TerminalWindow.cpp
  src/cascadia/TerminalApp/TerminalWindow.h
  src/cascadia/TerminalApp/TerminalWindow.idl
  src/cascadia/TerminalApp/TitlebarControl.cpp
  src/cascadia/TerminalApp/TitlebarControl.h
  src/cascadia/TerminalApp/TitlebarControl.idl
  src/cascadia/TerminalSettingsEditor/GlobalAppearance.xaml
  src/cascadia/TerminalSettingsEditor/GlobalAppearanceViewModel.h
  src/cascadia/TerminalSettingsEditor/GlobalAppearanceViewModel.idl
  src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw
  src/cascadia/TerminalSettingsModel/GlobalAppSettings.idl
  src/cascadia/TerminalSettingsModel/MTSMSettings.h
  src/cascadia/WindowsTerminal/AppHost.cpp
  src/cascadia/WindowsTerminal/IslandWindow.cpp
  src/cascadia/WindowsTerminal/IslandWindow.h
  src/cascadia/WindowsTerminal/NonClientIslandWindow.cpp
  src/cascadia/WindowsTerminal/NonClientIslandWindow.h
Labels: Area-UserInterface, Product-Terminal, Issue-Task
