Repository microsoft/terminal, pull requests merged in 2025-07, with the labels that each got.

#19117 Improve TSF color filtering logic (re: QQPinyin)
  src/tsf/Implementation.cpp
Labels: Issue-Bug, Product-Terminal, Priority-3, Area-i18n

#19166 Filter the Command Palette in English in addition to locale
  src/cascadia/LocalTests_TerminalApp/FilteredCommandTests.cpp
  src/cascadia/TerminalApp/CommandPalette.xaml
  src/cascadia/TerminalApp/CommandPaletteItems.h
  src/cascadia/TerminalApp/FilteredCommand.cpp
  src/cascadia/TerminalApp/FilteredCommand.h
  src/cascadia/TerminalApp/FilteredCommand.idl
  src/cascadia/TerminalApp/IPaletteItem.idl
  src/cascadia/TerminalSettingsModel/ActionAndArgs.cpp
  src/cascadia/TerminalSettingsModel/ActionAndArgs.h
  src/cascadia/TerminalSettingsModel/ActionArgs.cpp
  src/cascadia/TerminalSettingsModel/ActionArgs.h
  src/cascadia/TerminalSettingsModel/ActionArgs.idl
  src/cascadia/TerminalSettingsModel/ActionArgsMagic.h
  src/cascadia/TerminalSettingsModel/Command.cpp
  src/cascadia/TerminalSettingsModel/Command.h
  src/cascadia/TerminalSettingsModel/Command.idl
  src/cascadia/TerminalSettingsModel/pch.h
  src/cascadia/WinRTUtils/inc/ScopedResourceLoader.h
Labels: Issue-Feature, Area-UserInterface, Product-Terminal, Priority-1, Area-Localization, Area-CmdPal

#19048 Update dependencies
  build/config/template.appinstaller
Labels: Needs-Attention
